include("${CMAKE_CURRENT_LIST_DIR}/../source_fixture.cmake")
cmake_minimum_required(VERSION 3.21)
if (NOT DEFINED COMPILER OR NOT DEFINED OUTPUT_DIR)
    message(FATAL_ERROR "COMPILER and OUTPUT_DIR are required")
endif ()
file(MAKE_DIRECTORY "${OUTPUT_DIR}")

function(expect_compile name source)
    set(input "${OUTPUT_DIR}/${name}/${name}.dmm")
    set(assembly "${OUTPUT_DIR}/${name}.s")
    dmm_test_write("${input}" "${source}")
    execute_process(COMMAND "${COMPILER}" --emit=asm --deterministic -o "${assembly}" "${input}"
            RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE errors TIMEOUT 30)
    if (NOT result EQUAL 0 OR NOT EXISTS "${assembly}")
        message(FATAL_ERROR "${name}: boundary program should compile: ${output}${errors}")
    endif ()
endfunction()

function(expect_reject name source diagnostic)
    set(input "${OUTPUT_DIR}/${name}/${name}.dmm")
    set(assembly "${OUTPUT_DIR}/${name}.s")
    dmm_test_write("${input}" "${source}")
    execute_process(COMMAND "${COMPILER}" --emit=asm --deterministic -o "${assembly}" "${input}"
            RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE errors TIMEOUT 30)
    string(FIND "${errors}" "${diagnostic}" diagnostic_position)
    if (result EQUAL 0 OR diagnostic_position EQUAL -1 OR EXISTS "${assembly}")
        message(FATAL_ERROR "${name}: expected clean rejection containing '${diagnostic}': ${output}${errors}")
    endif ()
endfunction()

# Token bytes: 510 (limit-1), 511 (limit), 512 (limit+1).
foreach (length 510 511)
    string(REPEAT "a" ${length} identifier)
    expect_compile("token_${length}" "func main() -> void { var ${identifier}:int; }\n")
endforeach ()
string(REPEAT "a" 512 identifier)
expect_reject(token_512 "func main() -> void { var ${identifier}:int; }\n" "Token exceeds maximum length")

# Expression tokens: unary operators plus one literal give exact boundaries.
foreach (operator_count 510 511)
    math(EXPR token_count "${operator_count} + 1")
    string(REPEAT "!" ${operator_count} operators)
    expect_compile("expression_${token_count}" "func main() -> void { var x:bit=${operators}true; }\n")
endforeach ()
string(REPEAT "!" 512 operators)
expect_reject(expression_513 "func main() -> void { var x:bit=${operators}true; }\n" "Expression tree exceeds")

# Function storage is dynamic; exercise the former 200-function boundary.
foreach (helper_count 198 199 200)
    set(source "")
    foreach (index RANGE 1 ${helper_count})
        string(APPEND source "func f${index}() -> void {}\n")
    endforeach ()
    string(APPEND source "func main() -> void {}\n")
    math(EXPR total "${helper_count} + 1")
    expect_compile("functions_${total}" "${source}")
endforeach ()

# Local declaration storage is dynamic as well.
foreach (variable_count 399 400 401)
    set(body "")
    foreach (index RANGE 1 ${variable_count})
        string(APPEND body "var v${index}:int;\n")
    endforeach ()
    set(source "func main() -> void {\n${body}}\n")
    expect_compile("variables_${variable_count}" "${source}")
endforeach ()

# Structured control-flow lowering has no legacy 100-loop table.
foreach (depth 99 100 101)
    string(REPEAT "while(false){" ${depth} openings)
    string(REPEAT "}" ${depth} closings)
    set(source "func main() -> void { ${openings}${closings} }\n")
    expect_compile("loops_${depth}" "${source}")
endforeach ()
