"""Reproduce DMM tables from the checked-in Unicode 17.0.0 UCD (no host UCD)."""
from pathlib import Path
import hashlib
import struct
import argparse
import sys

ROOT = Path(__file__).resolve().parent
DATA = ROOT / "data" / "17.0.0"
sys.path.insert(0, str(ROOT.parent.parent / "tools"))
from format_dmm import format_source
CATEGORIES = "Cn Lu Ll Lt Lm Lo Mn Mc Me Nd Nl No Pc Pd Ps Pe Pi Pf Po Sm Sc Sk So Zs Zl Zp Cc Cf Cs Co".split()

def records(name):
    for line in (DATA / name).read_text(encoding="utf-8").splitlines():
        body = line.split("#", 1)[0].strip()
        if body:
            yield [s.strip() for s in body.split(";")]

def interval(value):
    parts = value.split("..")
    return int(parts[0], 16), int(parts[-1], 16)

def hx(value, width=6):
    return f"{value:0{width}x}"

def generated(path, content, check):
    data = content.encode("utf-8") if isinstance(content, str) else content
    if check:
        if not path.exists() or path.read_bytes() != data:
            raise SystemExit(f"Generated file is stale: {path}")
    else:
        path.write_bytes(data)

def generate(check=False):
    properties = [(0, 0)] * 0x110000
    flags = [0] * 0x110000
    maps = {name: {} for name in ("lower", "upper", "title", "fold")}
    decompositions = {}
    pending = None
    for row in records("UnicodeData.txt"):
        cp = int(row[0], 16)
        prop = (CATEGORIES.index(row[2]), int(row[3]))
        if row[1].endswith(", First>"):
            pending = cp
        elif row[1].endswith(", Last>"):
            properties[pending:cp + 1] = [prop] * (cp + 1 - pending)
            pending = None
        else:
            properties[cp] = prop
        for name, field in (("upper", 12), ("lower", 13), ("title", 14)):
            if row[field]:
                maps[name][cp] = [int(row[field], 16)]
        if row[5]:
            tokens = row[5].split()
            compat = tokens[0].startswith("<")
            decompositions[cp] = (compat, [int(x, 16) for x in tokens[int(compat):]])
    for row in records("SpecialCasing.txt"):
        if not row[4]:  # Locale-independent unconditional full mappings.
            for name, field in (("lower", 1), ("title", 2), ("upper", 3)):
                maps[name][int(row[0], 16)] = [int(x, 16) for x in row[field].split()]
    for row in records("CaseFolding.txt"):
        if row[1] in ("C", "F"):
            maps["fold"][int(row[0], 16)] = [int(x, 16) for x in row[2].split()]
    bits = {"Alphabetic": 1, "White_Space": 2, "Cased": 4, "Case_Ignorable": 8}
    for filename in ("DerivedCoreProperties.txt", "PropList.txt"):
        for row in records(filename):
            if row[1] in bits:
                start, end = interval(row[0])
                for cp in range(start, end + 1):
                    flags[cp] |= bits[row[1]]
    excluded = set()
    for row in records("DerivedNormalizationProps.txt"):
        if row[1] == "Full_Composition_Exclusion":
            a, b = interval(row[0])
            excluded.update(range(a, b + 1))
    compositions = sorted((parts[0], parts[1], cp)
                          for cp, (compat, parts) in decompositions.items()
                          if not compat and len(parts) == 2 and cp not in excluded)
    declarations = ['package unicode;', '// Generated by generate.py; Unicode 17.0.0. Do not edit.',
                    'pub const VERSION:string="17.0.0";']
    def table(name, data, width):
        # Lexer tokens are bounded to 511 bytes. ASCII chunks retain static
        # byte offsets without concatenation or runtime decoding allocations.
        chunks = [data[i:i + 480] for i in range(0, len(data), 480)] or [""]
        def branch(start, end):
            if end - start == 1:
                return f'return "{chunks[start]}";'
            middle = (start + end) // 2
            return f"if(index<{middle}) {{ {branch(start,middle)} }} else {{ {branch(middle,end)} }}"
        declarations.append(f"func {name}(index:usize)->string {{ {branch(0,len(chunks))} }}")
        declarations.append(f"const {name}_COUNT:usize={len(data) // width};")
    ranges = []
    start = 0
    for cp in range(1, 0x110001):
        if cp == 0x110000 or properties[cp] != properties[start] or flags[cp] != flags[start]:
            category, ccc = properties[start]
            if category or ccc or flags[start]:
                ranges.append(hx(start) + hx(cp - 1) + hx(category, 2) + hx(ccc, 2) + hx(flags[start], 2))
            start = cp
    table("PROPERTIES", "".join(ranges), 18)
    for name, mapping in maps.items():
        entries, values = [], []
        for cp, sequence in sorted(mapping.items()):
            entries.append(hx(cp) + hx(len(values)) + hx(len(sequence), 2))
            values.extend(sequence)
        table(name.upper() + "_MAP", "".join(entries), 14)
        table(name.upper() + "_VALUES", "".join(map(hx, values)), 6)
    entries, values = [], []
    for cp, (compat, sequence) in sorted(decompositions.items()):
        entries.append(hx(cp) + hx(len(values)) + hx(len(sequence), 2) + hx(int(compat), 2))
        values.extend(sequence)
    table("DECOMPOSITIONS", "".join(entries), 16)
    table("DECOMPOSITION_VALUES", "".join(map(hx, values)), 6)
    table("COMPOSITIONS", "".join(hx(a) + hx(b) + hx(cp) for a, b, cp in compositions), 18)
    generated(ROOT / "tables.dmm", format_source("\n".join(declarations) + "\n"), check)
    manifest = "\n".join(f"{hashlib.sha256(p.read_bytes()).hexdigest()}  {p.name}"
                         for p in sorted(DATA.glob("*.txt"))) + "\n"
    generated(DATA / "SHA256SUMS", manifest, check)
    # Compact official conformance vectors: five length-prefixed UTF-8 fields.
    vectors = bytearray()
    count = 0
    for row in records("NormalizationTest.txt"):
        if row[0].startswith("@"):
            continue
        for field in row[:5]:
            encoded = "".join(chr(int(cp,16)) for cp in field.split()).encode("utf-8")
            vectors.extend(struct.pack("<H",len(encoded)))
            vectors.extend(encoded)
        count += 1
    destination = ROOT.parent.parent / "tests" / "unicode"
    destination.mkdir(parents=True,exist_ok=True)
    generated(destination / "normalization.bin", struct.pack("<I",count)+vectors, check)
    cases = bytearray()
    points = sorted(set().union(*(mapping.keys() for mapping in maps.values())))
    for cp in points:
        for sequence in ([cp], *(maps[name].get(cp, [cp]) for name in ("lower", "upper", "title", "fold"))):
            encoded = "".join(chr(value) for value in sequence).encode("utf-8")
            cases.extend(struct.pack("<H", len(encoded)))
            cases.extend(encoded)
    generated(destination / "casing.bin", struct.pack("<I", len(points)) + cases, check)

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="verify generated files without modifying them")
    generate(parser.parse_args().check)
