cmake_minimum_required(VERSION 3.21)
file(MAKE_DIRECTORY "${OUTPUT_DIR}")

function(run_case name program expected input)
    execute_process(COMMAND "${program}" ${ARGN} INPUT_FILE "${input}"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE errors ENCODING UTF8 TIMEOUT 30)
    if(NOT result STREQUAL "${expected}")
        message(FATAL_ERROR "${name}: expected exit ${expected}, got ${result}\n${output}\n${errors}")
    endif()
    string(REPLACE "\r\n" "\n" output "${output}")
    set(case_output "${output}" PARENT_SCOPE)
endfunction()

function(expect_output name expected)
    if(NOT case_output STREQUAL "${expected}")
        message(FATAL_ERROR "${name}: unexpected output\nExpected: ${expected}\nActual: ${case_output}")
    endif()
endfunction()

file(WRITE "${OUTPUT_DIR}/empty" "")
file(WRITE "${OUTPUT_DIR}/todo.in" "add Read examples\nadd Try server\nlist\ndone 1\nremove 2\nadd Write JSON\nlist\ndone 99\ndone bad\nunknown\nquit\n")
file(WRITE "${OUTPUT_DIR}/grep.txt" "first\nERROR: unavailable\nlast error")
string(REPEAT "x" 4094 prefix)
file(WRITE "${OUTPUT_DIR}/grep-boundary.txt" "${prefix}needle\n")
file(WRITE "${OUTPUT_DIR}/valid.json" "{\"empty\":[],\"object\":{},\"values\":[true,false,null,-0,1.25e+2],\"emoji\":\"\\uD83D\\uDE80\"}")
set(invalid_json "" "01" "-" "1." "1e" "[1,]" "{\"x\":}" "{\"x\" 1}" "true false" "\"\\q\"" "\"\\uD800\"" "\"unterminated")
string(REPEAT "[" 64 opening)
string(REPEAT "]" 64 closing)
file(WRITE "${OUTPUT_DIR}/depth64.json" "${opening}0${closing}")
file(WRITE "${OUTPUT_DIR}/depth65.json" "[${opening}0${closing}]")

execute_process(COMMAND "${C_DRIVER}" -std=c11 -Wall -Wextra -Werror -c
    "${SOURCE_DIR}/examples/c_interop/sensor.c" -o "${OUTPUT_DIR}/sensor.o"
    RESULT_VARIABLE status ERROR_VARIABLE errors TIMEOUT 30)
if(NOT status EQUAL 0)
    message(FATAL_ERROR "C example build: ${errors}")
endif()

foreach(level 0 1)
    foreach(example http_server todo_cli json_parser mini_grep c_interop)
        set(native_options)
        if(example STREQUAL "c_interop")
            set(native_options --native-library "sensor=${OUTPUT_DIR}/sensor.o" --linker-driver "${C_DRIVER}")
        endif()
        set(source "${SOURCE_DIR}/examples/${example}/${example}.dmm")
        set(program "${OUTPUT_DIR}/${example}_${level}.exe")
        execute_process(COMMAND "${COMPILER}" "-O${level}" ${native_options} "${source}" -o "${program}"
            RESULT_VARIABLE status ERROR_VARIABLE errors TIMEOUT 90)
        if(NOT status EQUAL 0)
            message(FATAL_ERROR "${example}/O${level}: ${errors}")
        endif()
        foreach(target elf coff)
            execute_process(COMMAND "${COMPILER}" "-O${level}" --emit=obj "--target=${target}"
                "${source}" -o "${OUTPUT_DIR}/${example}_${level}_${target}.o"
                RESULT_VARIABLE status ERROR_VARIABLE errors TIMEOUT 90)
            if(NOT status EQUAL 0)
                message(FATAL_ERROR "${example}/${target}/O${level}: ${errors}")
            endif()
        endforeach()
    endforeach()

    run_case(todo "${OUTPUT_DIR}/todo_cli_${level}.exe" 0 "${OUTPUT_DIR}/todo.in")
    expect_output(todo "Todo — tasks exist only during this session. Type help.\nAdded 1\nAdded 2\n1 [ ] Read examples\n2 [ ] Try server\nDone\nRemoved\nAdded 3\n1 [x] Read examples\n3 [ ] Write JSON\nTask not found\nExpected a positive task ID\nUnknown command; type help\n")
    file(WRITE "${OUTPUT_DIR}/restart.in" "list\nquit\n")
    run_case(todo_restart "${OUTPUT_DIR}/todo_cli_${level}.exe" 0 "${OUTPUT_DIR}/restart.in")
    expect_output(todo_restart "Todo — tasks exist only during this session. Type help.\nNo tasks\n")

    run_case(grep_file "${OUTPUT_DIR}/mini_grep_${level}.exe" 0 "${OUTPUT_DIR}/empty" error "${OUTPUT_DIR}/grep.txt" --ignore-case)
    expect_output(grep_file "2:ERROR: unavailable\n3:last error\n")
    run_case(grep_stdin "${OUTPUT_DIR}/mini_grep_${level}.exe" 0 "${OUTPUT_DIR}/grep.txt" error -)
    expect_output(grep_stdin "3:last error\n")
    run_case(grep_missing "${OUTPUT_DIR}/mini_grep_${level}.exe" 1 "${OUTPUT_DIR}/grep.txt" absent -)
    expect_output(grep_missing "")
    run_case(grep_boundary "${OUTPUT_DIR}/mini_grep_${level}.exe" 0 "${OUTPUT_DIR}/empty" needle "${OUTPUT_DIR}/grep-boundary.txt")
    expect_output(grep_boundary "1:${prefix}needle\n")
    run_case(grep_option "${OUTPUT_DIR}/mini_grep_${level}.exe" 2 "${OUTPUT_DIR}/empty" error - --unknown)

    run_case(json_sample "${OUTPUT_DIR}/json_parser_${level}.exe" 0 "${OUTPUT_DIR}/empty" "${SOURCE_DIR}/examples/json_parser/sample.json")
    if(NOT case_output MATCHES "key \"service\"" OR NOT case_output MATCHES "    8080")
        message(FATAL_ERROR "JSON sample tree lost keys or parent indentation")
    endif()
    run_case(json_valid "${OUTPUT_DIR}/json_parser_${level}.exe" 0 "${OUTPUT_DIR}/empty" "${OUTPUT_DIR}/valid.json")
    run_case(json_lookup "${OUTPUT_DIR}/json_parser_${level}.exe" 0 "${OUTPUT_DIR}/empty"
        "${SOURCE_DIR}/examples/json_parser/sample.json" ports 0)
    expect_output(json_lookup "8080\n")
    run_case(json_missing "${OUTPUT_DIR}/json_parser_${level}.exe" 3 "${OUTPUT_DIR}/empty"
        "${SOURCE_DIR}/examples/json_parser/sample.json" missing)
    run_case(json_depth64 "${OUTPUT_DIR}/json_parser_${level}.exe" 0 "${OUTPUT_DIR}/empty" "${OUTPUT_DIR}/depth64.json")
    run_case(json_depth65 "${OUTPUT_DIR}/json_parser_${level}.exe" 1 "${OUTPUT_DIR}/empty" "${OUTPUT_DIR}/depth65.json")
    foreach(invalid IN LISTS invalid_json)
        file(WRITE "${OUTPUT_DIR}/invalid.json" "${invalid}")
        run_case(json_rejection "${OUTPUT_DIR}/json_parser_${level}.exe" 1 "${OUTPUT_DIR}/empty" "${OUTPUT_DIR}/invalid.json")
        if(NOT case_output MATCHES "JSON error at byte")
            message(FATAL_ERROR "JSON rejection did not report an offset")
        endif()
    endforeach()
    run_case(interop "${OUTPUT_DIR}/c_interop_${level}.exe" 0 "${OUTPUT_DIR}/empty")
    expect_output(interop "Samples: 3\nMinimum (F): 68.000000\nMaximum (F): 75.200000\nMean (F): 71.600000\n")
    run_case(http_port "${OUTPUT_DIR}/http_server_${level}.exe" 2 "${OUTPUT_DIR}/empty" 65536)
    if(NODE_EXECUTABLE)
        execute_process(COMMAND "${NODE_EXECUTABLE}" "${SOURCE_DIR}/tests/json_example_test.cjs"
            "${OUTPUT_DIR}/json_parser_${level}.exe" "${OUTPUT_DIR}" RESULT_VARIABLE status
            OUTPUT_VARIABLE output ERROR_VARIABLE errors TIMEOUT 60)
        if(NOT status EQUAL 0)
            message(FATAL_ERROR "Generated JSON/O${level}: ${output}\n${errors}")
        endif()
        execute_process(COMMAND "${NODE_EXECUTABLE}" "${SOURCE_DIR}/tests/http_example_test.cjs"
            "${OUTPUT_DIR}/http_server_${level}.exe" RESULT_VARIABLE status
            OUTPUT_VARIABLE output ERROR_VARIABLE errors TIMEOUT 30)
        if(NOT status EQUAL 0)
            message(FATAL_ERROR "HTTP/O${level}: ${output}\n${errors}")
        endif()
    endif()
endforeach()
