cmake_minimum_required(VERSION 3.21)
get_filename_component(ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)

if(EXISTS "${ROOT}/src/compat" OR
   EXISTS "${ROOT}/src/backend/parser_core.c" OR
   EXISTS "${ROOT}/src/backend/parser_codegen.c" OR
   EXISTS "${ROOT}/src/backend/instruction_builder.c")
    message(FATAL_ERROR "removed compatibility backend sources have returned")
endif()

file(READ "${ROOT}/src/driver/main.c" main_source)
file(READ "${ROOT}/src/frontend/frontend.c" frontend_source)
file(READ "${ROOT}/src/backend/backend.h" backend_api)
file(READ "${ROOT}/src/backend/backend.c" backend_source)
file(READ "${ROOT}/src/ast/ast.h" ast_api)
file(READ "${ROOT}/src/sema/semantic.c" semantic_source)
file(READ "${ROOT}/src/ir/ir.c" ir_source)

if(main_source MATCHES "#[ \t]*include[ \t]*[<\"](lexer|parser|instruction_builder)\\.h")
    message(FATAL_ERROR "CLI crossed the frontend/backend boundary")
endif()
if(frontend_source MATCHES "#[ \t]*include[ \t]*[<\"](backend|parser|instruction_builder)\\.h")
    message(FATAL_ERROR "frontend depends on backend implementation")
endif()
if(backend_api MATCHES "lexer\\.h|parser\\.h|TokenStream|Parser")
    message(FATAL_ERROR "backend public API leaks frontend compiler state")
endif()
if(backend_source MATCHES "#[ \t]*include[ \t]*[<\"](lexer|parser|instruction_builder)\\.h|TokenStream|parse_program")
    message(FATAL_ERROR "typed backend implementation depends on a removed parser")
endif()
if(ast_api MATCHES "lexer\\.h|parser\\.h|backend\\.h|TokenStream|Parser")
    message(FATAL_ERROR "AST public API leaks a compiler layer")
endif()
if(semantic_source MATCHES "#[ \t]*include[ \t]*[<\"](lexer|parser|backend|instruction_builder)\\.h")
    message(FATAL_ERROR "semantic analysis depends on a compiler implementation layer")
endif()
if(ir_source MATCHES "#[ \t]*include[ \t]*[<\"](lexer|parser|backend|instruction_builder)\\.h")
    message(FATAL_ERROR "IR lowering depends on a compiler implementation layer")
endif()
