cmake_minimum_required(VERSION 3.21)
get_filename_component(ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)

file(READ "${ROOT}/src/driver/main.c" main_source)
file(READ "${ROOT}/src/frontend/frontend.c" frontend_source)
file(READ "${ROOT}/src/backend/backend.h" backend_api)
file(READ "${ROOT}/src/ast/ast.h" ast_api)

if(main_source MATCHES "#[ \t]*include[ \t]*[<\"](lexer|parser|instruction_builder)\\.h")
    message(FATAL_ERROR "CLI crossed the frontend/backend boundary")
endif()
if(frontend_source MATCHES "#[ \t]*include[ \t]*[<\"](backend|parser|instruction_builder)\\.h")
    message(FATAL_ERROR "frontend depends on backend implementation")
endif()
if(backend_api MATCHES "lexer\\.h|parser\\.h|TokenStream|Parser")
    message(FATAL_ERROR "backend public API leaks legacy compiler state")
endif()
if(ast_api MATCHES "lexer\\.h|parser\\.h|backend\\.h|TokenStream|Parser")
    message(FATAL_ERROR "AST public API leaks a compiler layer")
endif()
