cmake_minimum_required(VERSION 3.21)
include("${CMAKE_CURRENT_LIST_DIR}/source_fixture.cmake")
set(work "${OUTPUT_DIR}/async_runtime")
file(MAKE_DIRECTORY "${work}")
file(WRITE "${work}/dmm.manifest" "module async.test/runtime\ndmm 2026-09-22-dev\nfeatures = [\"async\"]\n")
configure_file("${CMAKE_CURRENT_LIST_DIR}/async/runtime.dmm" "${work}/runtime.dmm" COPYONLY)
if(WIN32)
    set(host coff)
else()
    set(host elf)
endif()
foreach(level 0 1)
    set(object "${work}/runtime_O${level}.s")
    execute_process(COMMAND "${COMPILER}" "-O${level}" "--target=${host}" --emit=asm
        "${work}/runtime.dmm" -o "${object}" RESULT_VARIABLE result ERROR_VARIABLE errors TIMEOUT 30)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "Async runtime fixture failed to compile: ${errors}")
    endif()
    dmm_test_abi_definitions("${object}" definitions)
    execute_process(COMMAND "${ASSEMBLER}" -std=c11 ${definitions}
        "${CMAKE_CURRENT_LIST_DIR}/async/poll_driver.c" "${object}" -o "${work}/driver_O${level}.exe"
        RESULT_VARIABLE result ERROR_VARIABLE errors TIMEOUT 30)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "Private poll driver failed to link: ${errors}")
    endif()
    execute_process(COMMAND "${work}/driver_O${level}.exe" RESULT_VARIABLE result ERROR_VARIABLE errors TIMEOUT 15)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "Private poll driver O${level} failed: ${result} ${errors}")
    endif()
endforeach()

# Execute the directly encoded native object as well. Renaming only the fixture
# main avoids colliding with the private C test entry; no production handoff API.
file(READ "${work}/runtime.dmm" source)
string(REPLACE "package async_fixture;" "package main;" source "${source}")
file(MAKE_DIRECTORY "${work}/native")
file(WRITE "${work}/native/runtime.dmm" "${source}\nfunc main() -> int { return 0; }\n")
get_filename_component(tool_directory "${ASSEMBLER}" DIRECTORY)
find_program(OBJCOPY NAMES objcopy HINTS "${tool_directory}" REQUIRED)
foreach(level 0 1)
    foreach(target elf coff)
        set(object "${work}/native_${level}_${target}.obj")
        execute_process(COMMAND "${COMPILER}" "-O${level}" "--target=${target}" --emit=obj
            "${work}/native/runtime.dmm" -o "${object}" RESULT_VARIABLE result ERROR_VARIABLE errors TIMEOUT 30)
        if(NOT result EQUAL 0)
            message(FATAL_ERROR "Async native ${target}/O${level} compilation failed: ${errors}")
        endif()
        if(NOT target STREQUAL host)
            continue()
        endif()
        set(renamed "${work}/native_${level}_driver.obj")
        execute_process(COMMAND "${OBJCOPY}" --redefine-sym main=__dmm_async_fixture_main
            "${object}" "${renamed}" RESULT_VARIABLE result ERROR_VARIABLE errors TIMEOUT 10)
        if(NOT result EQUAL 0)
            message(FATAL_ERROR "Cannot prepare private native poll driver: ${errors}")
        endif()
        dmm_test_abi_definitions("${renamed}" definitions)
        execute_process(COMMAND "${ASSEMBLER}" -std=c11 -DDRIVER_NATIVE ${definitions}
            "${CMAKE_CURRENT_LIST_DIR}/async/poll_driver.c" "${renamed}" -pthread -o "${work}/native_driver_O${level}.exe"
            RESULT_VARIABLE result ERROR_VARIABLE errors TIMEOUT 30)
        if(NOT result EQUAL 0)
            message(FATAL_ERROR "Native poll driver failed to link: ${errors}")
        endif()
        execute_process(COMMAND "${work}/native_driver_O${level}.exe" RESULT_VARIABLE result ERROR_VARIABLE errors TIMEOUT 15)
        if(NOT result EQUAL 0)
            message(FATAL_ERROR "Native poll driver O${level} failed: ${result} ${errors}")
        endif()
        foreach(invalid cleanup_pending poll_completed)
            execute_process(COMMAND "${work}/native_driver_O${level}.exe" "${invalid}"
                RESULT_VARIABLE result ERROR_VARIABLE errors TIMEOUT 10)
            if(result STREQUAL "0" OR result STREQUAL "99" OR result MATCHES "timeout")
                message(FATAL_ERROR "Invalid async transition did not trap: ${invalid}: ${result}")
            endif()
        endforeach()
    endforeach()
endforeach()
