cmake_minimum_required(VERSION 3.21)
set(work "${OUTPUT_DIR}/executor")
file(MAKE_DIRECTORY "${work}")
file(WRITE "${work}/dmm.manifest" "module async.test/executor\ndmm 2026-09-22-dev\nfeatures = [\"async\"]\n")
configure_file("${CMAKE_CURRENT_LIST_DIR}/async/executor.dmm" "${work}/executor.dmm" COPYONLY)
if(WIN32)
    set(host coff)
else()
    set(host elf)
endif()
foreach(level 0 1)
    foreach(target elf coff)
        set(executable "${work}/executor_${target}_O${level}.exe")
        set(emission obj)
        if(target STREQUAL host)
            set(emission exe)
        endif()
        execute_process(COMMAND "${COMPILER}" "-O${level}" "--target=${target}" "--emit=${emission}"
            "${work}/executor.dmm" -o "${executable}" RESULT_VARIABLE result ERROR_VARIABLE errors TIMEOUT 30)
        if(NOT result EQUAL 0)
            message(FATAL_ERROR "Executor ${target}/O${level} failed to compile: ${errors}")
        endif()
        if(target STREQUAL host)
            execute_process(COMMAND "${executable}" RESULT_VARIABLE result ERROR_VARIABLE errors TIMEOUT 20)
            if(NOT result EQUAL 0)
                message(FATAL_ERROR "Executor ${target}/O${level} failed: ${result} ${errors}")
            endif()
        endif()
    endforeach()
endforeach()
