cmake_minimum_required(VERSION 3.21)
file(MAKE_DIRECTORY "${OUTPUT_DIR}")
set(fixture "${SOURCE_DIR}/tests/language/auto_deref/auto_deref.dmm")
foreach(level 0 1)
    set(program "${OUTPUT_DIR}/auto_deref_${level}.exe")
    execute_process(COMMAND "${COMPILER}" "-O${level}" --emit=exe "${fixture}" -o "${program}"
        RESULT_VARIABLE status ERROR_VARIABLE errors TIMEOUT 60)
    if(NOT status EQUAL 0)
        message(FATAL_ERROR "Auto-deref O${level}: ${errors}")
    endif()
    execute_process(COMMAND "${program}" RESULT_VARIABLE status TIMEOUT 15)
    if(NOT status EQUAL 0)
        message(FATAL_ERROR "Auto-deref O${level} execution: ${status}")
    endif()
    foreach(target elf coff)
        foreach(mode obj intel att)
            set(options --emit=obj)
            if(NOT mode STREQUAL obj)
                set(options --emit=asm "--syntax=${mode}")
            endif()
            execute_process(COMMAND "${COMPILER}" "-O${level}" "--target=${target}" ${options}
                "${fixture}" -o "${OUTPUT_DIR}/${target}_${level}_${mode}.out"
                RESULT_VARIABLE status ERROR_VARIABLE errors TIMEOUT 30)
            if(NOT status EQUAL 0)
                message(FATAL_ERROR "Auto-deref ${target}/O${level}/${mode}: ${errors}")
            endif()
        endforeach()
    endforeach()
endforeach()

function(reject name body expected)
    set(work "${OUTPUT_DIR}/${name}")
    file(MAKE_DIRECTORY "${work}")
    file(WRITE "${work}/dmm.manifest" "module tests/autoderef/${name}\ndmm 2026-10-04-dev\nfeatures = [\"async\"]\n")
    file(WRITE "${work}/main.dmm" "package main; struct Point { var x:i32; func read()->i32 { return x; } func change()->void { x+=1; } } ${body}\n")
    execute_process(COMMAND "${COMPILER}" --emit=obj "${work}/main.dmm" -o "${work}/main.o"
        RESULT_VARIABLE status ERROR_VARIABLE errors TIMEOUT 15)
    if(status EQUAL 0 OR NOT errors MATCHES "${expected}")
        message(FATAL_ERROR "Expected rejection ${name} (${expected}): ${status}: ${errors}")
    endif()
endfunction()
set(shared "var point=Point{x:1}; var p=&point;")
set(mutable "var point=Point{x:1}; var p=&mut point;")
reject(shared_field "func main()->void { ${shared} p.x=2; }" "shared checked reference")
reject(shared_method "func main()->void { ${shared} p.change(); }" "shared checked reference")
reject(nested_shared_field "func main()->void { ${mutable} var outer=&p; outer.x=2; }" "shared checked reference")
reject(nested_shared_method "func main()->void { ${mutable} var outer=&p; outer.change(); }" "shared checked reference")
reject(inner_shared "func main()->void { ${shared} var outer=&mut p; outer.change(); }" "shared checked reference")
reject(shared_index "func main()->void { var storage:i32[2]=[1,2]; var view:i32[]=storage; var p=&view; p[0]=3; }" "shared checked reference")
reject(shared_element_mut_borrow "func main()->void { var storage:i32[2]=[1,2]; var view:i32[]=storage; var p=&view; var item=&mut p[0]; }" "shared checked reference")
reject(live_element "func main()->void { var storage:i32[2]=[1,2]; var view:i32[]=storage; var p=&mut view; var item=&p[0]; p[0]=3; var read=*item; }" "borrow")
reject(live_field "func main()->void { ${mutable} var item=&p.x; p.change(); var read=*item; }" "borrow")
reject(owner_move "struct Owner { var x:i32; destructor {} } func main()->void { var owner=Owner{x:1}; var p=&owner; var moved=*p; }" "consum|borrow|reference")
reject(owner_field_move "struct Owner { var x:i32; destructor {} } struct Container { var owner:Owner; } func main()->void { var container=Container{owner:Owner{x:1}}; var p=&container; var moved=p.owner; }" "consum|borrow|reference")
reject(owner_index_move "struct Owner { var x:i32; destructor {} } func main()->void { var storage:Owner[1]=[Owner{x:1}]; var view:Owner[]=storage; var p=&view; var moved=p[0]; }" "consum|borrow|reference")
reject(once_method "interface Finish { once func finish()->i32; } struct Value { var x:i32; func finish()->i32 { return x; } } func run<T:Finish>(p:&mut T)->i32 { return p.finish(); } func main()->void { var value=Value{x:1}; var result=run(&mut value); }" "consum|borrow|reference|once")
reject(local_escape "func escape()->&i32 { var point=Point{x:1}; var p=&point; return &p.x; } func main()->void {}" "outlive|local|borrow")
reject(projected_loan "func project(p:&Point)->&i32 { return &p.x; } func main()->void { var point=Point{x:1}; var p=&point; var item=project(p); point.x=2; var read=*item; }" "borrow")
reject(local_element_escape "func escape()->&i32 { var storage:i32[2]=[1,2]; var view:i32[]=storage; var p=&view; return &p[0]; } func main()->void {}" "outlive|local|borrow")
reject(raw_local_escape "func escape()->&i32 { var point=Point{x:1}; var p=(&point).(*Point); return &(*p).x; } func main()->void {}" "outlive|local|borrow")
reject(async_live_receiver "struct Worker { var x:i32; async func read()->i32 { return x; } } func main()->void { var worker=Worker{x:1}; var p=&mut worker; var future=p.read(); p.x=2; var result=block_on(future); }" "borrow")
reject(raw_field "func wrong(p:*Point)->i32 { return p.x; } func main()->void {}" "Raw pointer member/method access requires explicit dereference")
reject(raw_method "func wrong(p:*Point)->i32 { return p.read(); } func main()->void {}" "Raw pointer member/method access requires explicit dereference")
reject(raw_nested "func wrong(p:**Point)->i32 { return p.read(); } func main()->void {}" "Raw pointer member/method access requires explicit dereference")
reject(mixed_field "func wrong(p:&(*Point))->i32 { return p.x; } func main()->void {}" "Raw pointer member/method access requires explicit dereference")
reject(mixed_method "func wrong(p:&mut (*Point))->i32 { return p.read(); } func main()->void {}" "Raw pointer member/method access requires explicit dereference")
reject(raw_slice "func wrong(p:*(i32[]))->usize { return p.length; } func main()->void {}" "Raw pointer member/method access requires explicit dereference")
reject(operator "func wrong(p:&i32)->i32 { return p+5; } func main()->void {}" "numeric|incompatible|operator")
reject(initializer "func wrong(p:&i32)->void { var value:i32=p; } func main()->void {}" "convert|incompatible")
reject(assignment "func wrong(p:&i32)->void { var value:i32=0; value=p; } func main()->void {}" "convert|incompatible")
reject(return_value "func wrong(p:&i32)->i32 { return p; } func main()->void {}" "convert|incompatible")
reject(argument "func consume(value:i32)->void {} func wrong(p:&i32)->void { consume(p); } func main()->void {}" "overload|convert|incompatible")
reject(no_auto_borrow "func inspect(value:&i32)->void {} func main()->void { var value:i32=1; inspect(value); }" "overload|convert|incompatible")

# Access sugar must retain the checked array/slice bounds trap at both levels.
foreach(shape array slice)
    set(work "${OUTPUT_DIR}/bounds_${shape}")
    file(MAKE_DIRECTORY "${work}")
    file(WRITE "${work}/dmm.manifest" "module tests/autoderef/bounds_${shape}\ndmm 2026-10-04-dev\n")
    set(binding "var p=&storage;")
    if(shape STREQUAL slice)
        set(binding "var view:i32[]=storage; var p=&view;")
    endif()
    file(WRITE "${work}/main.dmm" "package main; func main()->int { var storage:i32[2]=[1,2]; ${binding} var index:usize=2; return p[index]; }\n")
    foreach(level 0 1)
        execute_process(COMMAND "${COMPILER}" "-O${level}" "${work}/main.dmm" -o "${work}/bounds_${level}.exe"
            RESULT_VARIABLE status ERROR_VARIABLE errors TIMEOUT 30)
        if(NOT status EQUAL 0)
            message(FATAL_ERROR "Auto-deref ${shape} bounds compilation: ${errors}")
        endif()
        execute_process(COMMAND "${work}/bounds_${level}.exe" RESULT_VARIABLE status TIMEOUT 15)
        if(status EQUAL 0)
            message(FATAL_ERROR "Auto-deref ${shape} O${level} omitted the bounds trap")
        endif()
    endforeach()
endforeach()
