cmake_minimum_required(VERSION 3.21)
if(NOT DEFINED COMPILER OR NOT DEFINED OUTPUT_DIR)
    message(FATAL_ERROR "COMPILER and OUTPUT_DIR are required")
endif()
file(MAKE_DIRECTORY "${OUTPUT_DIR}")
set(source "${OUTPUT_DIR}/input.dmm")
set(first "${OUTPUT_DIR}/first.s")
set(second "${OUTPUT_DIR}/second.s")
set(ast_first "${OUTPUT_DIR}/first.ast")
set(ast_second "${OUTPUT_DIR}/second.ast")
set(ir_first "${OUTPUT_DIR}/first.ir")
set(ir_second "${OUTPUT_DIR}/second.ir")
set(map_first "${OUTPUT_DIR}/first.map")
set(map_second "${OUTPUT_DIR}/second.map")
file(WRITE "${source}" "func main() -> int { var result:int=1; return result; }")
execute_process(COMMAND "${COMPILER}" --emit=asm -O0 --deterministic
    --dump-ast "${ast_first}" --dump-ir "${ir_first}" --source-map "${map_first}"
    -o "${first}" "${source}" RESULT_VARIABLE first_result)
execute_process(COMMAND "${COMPILER}" --emit=asm -O0 "${source}" --deterministic
    --dump-ast "${ast_second}" --dump-ir "${ir_second}" --source-map "${map_second}"
    -o "${second}" RESULT_VARIABLE second_result)
execute_process(COMMAND "${COMPILER}" --emit=asm --version RESULT_VARIABLE version_result OUTPUT_VARIABLE version)
if(NOT first_result EQUAL 0 OR NOT second_result EQUAL 0 OR NOT version_result EQUAL 0)
    message(FATAL_ERROR "CLI command failed")
endif()
file(SHA256 "${first}" first_hash)
file(SHA256 "${second}" second_hash)
if(NOT first_hash STREQUAL second_hash OR NOT version MATCHES "DMM Compiler [0-9]+\\.[0-9]+\\.[0-9]+")
    message(FATAL_ERROR "Deterministic output or version reporting failed")
endif()
foreach(kind ast ir map)
    file(SHA256 "${${kind}_first}" first_dump_hash)
    file(SHA256 "${${kind}_second}" second_dump_hash)
    if(NOT first_dump_hash STREQUAL second_dump_hash)
        message(FATAL_ERROR "${kind} dump is not deterministic")
    endif()
endforeach()
file(READ "${ast_first}" ast_dump)
file(READ "${ir_first}" ir_dump)
file(READ "${map_first}" source_map)
string(FIND "${ast_dump}" "dmm-ast-v2" ast_header)
string(FIND "${ast_dump}" "declaration function" ast_declaration)
string(FIND "${ast_dump}" "statement body block" ast_statement)
string(FIND "${ir_dump}" "dmm-ir-v3" ir_header)
string(FIND "${ir_dump}" "opcode=declare" ir_instruction)
string(FIND "${source_map}" "dmm-source-map-v1" map_header)
string(FIND "${source_map}" "function=\"main\" source=\"${source}\" ir=3 span=1:" map_instruction)
if(NOT ast_header EQUAL 0 OR ast_declaration LESS 0 OR ast_statement LESS 0 OR
   NOT ir_header EQUAL 0 OR ir_instruction LESS 0 OR NOT map_header EQUAL 0 OR
   map_instruction LESS 0)
    message(FATAL_ERROR "Stable dump/source-map schema is incomplete")
endif()
file(SHA256 "${source}" source_hash)
execute_process(COMMAND "${COMPILER}" --emit=asm -o "${source}" "${source}"
    RESULT_VARIABLE conflict_result ERROR_VARIABLE conflict_error)
file(SHA256 "${source}" protected_hash)
if(conflict_result EQUAL 0 OR NOT source_hash STREQUAL protected_hash)
    message(FATAL_ERROR "Compiler did not protect a source file from output overwrite")
endif()

# Aliases must fail before either destination is removed or truncated.
function(check_alias first second)
    file(WRITE "${source}" "func main() -> int { return 0; }")
    file(WRITE "${first}" "preserve-artifact")
    file(SHA256 "${first}" before)
    execute_process(COMMAND "${COMPILER}" --emit=asm --formatError -o "${first}" --dump-ast "${second}" "${source}"
        RESULT_VARIABLE result ERROR_VARIABLE diagnostic)
    file(SHA256 "${first}" after)
    string(JSON code GET "${diagnostic}" errors 0 errorCode)
    if(result EQUAL 0 OR NOT before STREQUAL after OR NOT code STREQUAL "C102")
        message(FATAL_ERROR "Aliased artifacts were modified: ${first}, ${second}: ${diagnostic}")
    endif()
endfunction()
file(MAKE_DIRECTORY "${OUTPUT_DIR}/alias-dir")
check_alias("${OUTPUT_DIR}/alias.s" "${OUTPUT_DIR}/./alias.s")
check_alias("${OUTPUT_DIR}/alias.s" "${OUTPUT_DIR}/alias-dir/../alias.s")
if(WIN32)
    check_alias("${OUTPUT_DIR}/alias.s" "${OUTPUT_DIR}/ALIAS.S")
endif()
execute_process(COMMAND "${COMPILER}" --emit=asm --formatError
    --dump-ast "${OUTPUT_DIR}/future.ast" --dump-ir "${OUTPUT_DIR}/alias-dir/../future.ast" "${source}"
    RESULT_VARIABLE result ERROR_VARIABLE diagnostic)
string(JSON code GET "${diagnostic}" errors 0 errorCode)
if(result EQUAL 0 OR NOT code STREQUAL "C102" OR EXISTS "${OUTPUT_DIR}/future.ast")
    message(FATAL_ERROR "Aliased missing artifact paths were written: ${diagnostic}")
endif()
execute_process(COMMAND "${CMAKE_COMMAND}" -E create_hardlink "${source}" "${OUTPUT_DIR}/source-link.dmm"
    RESULT_VARIABLE link_result ERROR_VARIABLE link_error)
if(link_result EQUAL 0)
    file(SHA256 "${source}" before)
    execute_process(COMMAND "${COMPILER}" --emit=asm --formatError -o "${OUTPUT_DIR}/source-link.dmm" "${source}"
        RESULT_VARIABLE result ERROR_VARIABLE diagnostic)
    file(SHA256 "${source}" after)
    string(JSON code GET "${diagnostic}" errors 0 errorCode)
    if(result EQUAL 0 OR NOT before STREQUAL after OR NOT code STREQUAL "C102")
        message(FATAL_ERROR "Hard-linked source was modified: ${diagnostic}")
    endif()
else()
    message(STATUS "Hardlink checks unavailable: ${link_error}")
endif()
execute_process(COMMAND "${CMAKE_COMMAND}" -E create_symlink "${OUTPUT_DIR}/alias-dir" "${OUTPUT_DIR}/directory-link"
    RESULT_VARIABLE link_result ERROR_VARIABLE link_error)
if(link_result EQUAL 0)
    # Neither output exists; canonicalization must resolve their shared parent.
    execute_process(COMMAND "${COMPILER}" --emit=asm --formatError
        -o "${OUTPUT_DIR}/alias-dir/future.s" --dump-ast "${OUTPUT_DIR}/directory-link/future.s" "${source}"
        RESULT_VARIABLE result ERROR_VARIABLE diagnostic)
    string(JSON code GET "${diagnostic}" errors 0 errorCode)
    if(result EQUAL 0 OR NOT code STREQUAL "C102" OR EXISTS "${OUTPUT_DIR}/alias-dir/future.s")
        message(FATAL_ERROR "Aliased non-existing artifacts were written: ${diagnostic}")
    endif()
else()
    message(STATUS "Directory symlink checks unavailable: ${link_error}")
endif()

# Every artifact must preserve imported units, including imports reached transitively.
set(imported "${OUTPUT_DIR}/imported.dmm")
set(nested "${OUTPUT_DIR}/nested.dmm")
file(WRITE "${nested}" "func nestedValue() -> int { return 7; }")
file(WRITE "${imported}" "import \"nested.dmm\"\nfunc importedValue() -> int { return nestedValue(); }")
file(WRITE "${source}" "import \"imported.dmm\"\nfunc main() -> int { return importedValue(); }")
foreach(protected "${source}" "${imported}" "${nested}")
    file(SHA256 "${protected}" before)
    foreach(option -o --dump-ast --dump-ir --source-map)
        execute_process(COMMAND "${COMPILER}" --emit=asm --formatError "${option}" "${protected}" "${source}"
            RESULT_VARIABLE result ERROR_VARIABLE diagnostic)
        file(SHA256 "${protected}" after)
        string(JSON code GET "${diagnostic}" errors 0 errorCode)
        if(result EQUAL 0 OR NOT before STREQUAL after OR NOT code STREQUAL "C102")
            message(FATAL_ERROR "${option} did not protect ${protected}: ${diagnostic}")
        endif()
    endforeach()
    execute_process(COMMAND "${COMPILER}" --emit=asm --ide --formatError --dump-ast "${protected}" "${source}"
        RESULT_VARIABLE result ERROR_VARIABLE diagnostic)
    file(SHA256 "${protected}" after)
    string(JSON code GET "${diagnostic}" errors 0 errorCode)
    if(result EQUAL 0 OR NOT before STREQUAL after OR NOT code STREQUAL "C102")
        message(FATAL_ERROR "IDE AST dump did not protect ${protected}: ${diagnostic}")
    endif()
endforeach()

# The implicit .s output may itself be an explicitly imported source unit.
file(WRITE "${source}.s" "func importedAssemblyPath() -> int { return 9; }")
file(WRITE "${source}" "import \"input.dmm.s\"\nfunc main() -> int { return importedAssemblyPath(); }")
file(SHA256 "${source}.s" before)
execute_process(COMMAND "${COMPILER}" --emit=asm --formatError "${source}"
    RESULT_VARIABLE result ERROR_VARIABLE diagnostic)
file(SHA256 "${source}.s" after)
string(JSON code GET "${diagnostic}" errors 0 errorCode)
if(result EQUAL 0 OR NOT before STREQUAL after OR NOT code STREQUAL "C102")
    message(FATAL_ERROR "Implicit assembly output destroyed an imported source: ${diagnostic}")
endif()

# A rejected imported lexer stream is still a loaded source, even without an AST.
file(WRITE "${source}.s" "func malformed() -> string { return \"bad\\q\"; }")
file(WRITE "${source}" "import \"input.dmm.s\"\nfunc main() -> int { return 0; }")
file(SHA256 "${source}.s" before)
foreach(mode normal ide)
    if(mode STREQUAL "ide")
        set(options --ide --dump-ast "${OUTPUT_DIR}/malformed-import.ast")
    else()
        set(options "")
    endif()
    execute_process(COMMAND "${COMPILER}" --emit=asm --formatError ${options} "${source}"
        RESULT_VARIABLE result ERROR_VARIABLE diagnostic)
    file(SHA256 "${source}.s" after)
    if(result EQUAL 0 OR NOT before STREQUAL after)
        message(FATAL_ERROR "Malformed loaded source was deleted during ${mode}: ${diagnostic}")
    endif()
endforeach()
execute_process(COMMAND "${COMPILER}" --emit=asm --formatError -o "${source}.s" "${source}"
    RESULT_VARIABLE result ERROR_VARIABLE diagnostic)
file(SHA256 "${source}.s" after)
string(FIND "${diagnostic}" "C102" collision)
if(result EQUAL 0 OR NOT before STREQUAL after OR collision LESS 0)
    message(FATAL_ERROR "Explicit output did not protect malformed import: ${diagnostic}")
endif()
