cmake_minimum_required(VERSION 3.21)
if(NOT DEFINED COMPILER OR NOT DEFINED OUTPUT_DIR)
    message(FATAL_ERROR "COMPILER and OUTPUT_DIR are required")
endif()
file(MAKE_DIRECTORY "${OUTPUT_DIR}")
set(source "${OUTPUT_DIR}/input.dmm")
set(first "${OUTPUT_DIR}/first.s")
set(second "${OUTPUT_DIR}/second.s")
set(ast_first "${OUTPUT_DIR}/first.ast")
set(ast_second "${OUTPUT_DIR}/second.ast")
set(ir_first "${OUTPUT_DIR}/first.ir")
set(ir_second "${OUTPUT_DIR}/second.ir")
set(map_first "${OUTPUT_DIR}/first.map")
set(map_second "${OUTPUT_DIR}/second.map")
file(WRITE "${source}" "func main() -> void { println(1); }")
execute_process(COMMAND "${COMPILER}" --deterministic
    --dump-ast "${ast_first}" --dump-ir "${ir_first}" --source-map "${map_first}"
    -o "${first}" "${source}" RESULT_VARIABLE first_result)
execute_process(COMMAND "${COMPILER}" "${source}" --deterministic
    --dump-ast "${ast_second}" --dump-ir "${ir_second}" --source-map "${map_second}"
    -o "${second}" RESULT_VARIABLE second_result)
execute_process(COMMAND "${COMPILER}" --version RESULT_VARIABLE version_result OUTPUT_VARIABLE version)
if(NOT first_result EQUAL 0 OR NOT second_result EQUAL 0 OR NOT version_result EQUAL 0)
    message(FATAL_ERROR "CLI command failed")
endif()
file(SHA256 "${first}" first_hash)
file(SHA256 "${second}" second_hash)
if(NOT first_hash STREQUAL second_hash OR NOT version MATCHES "DMM Compiler [0-9]+\\.[0-9]+\\.[0-9]+")
    message(FATAL_ERROR "Deterministic output or version reporting failed")
endif()
foreach(kind ast ir map)
    file(SHA256 "${${kind}_first}" first_dump_hash)
    file(SHA256 "${${kind}_second}" second_dump_hash)
    if(NOT first_dump_hash STREQUAL second_dump_hash)
        message(FATAL_ERROR "${kind} dump is not deterministic")
    endif()
endforeach()
file(READ "${ast_first}" ast_dump)
file(READ "${ir_first}" ir_dump)
file(READ "${map_first}" source_map)
string(FIND "${ast_dump}" "dmm-ast-v1" ast_header)
string(FIND "${ast_dump}" "declaration function" ast_declaration)
string(FIND "${ast_dump}" "statement body block" ast_statement)
string(FIND "${ir_dump}" "dmm-ir-v1" ir_header)
string(FIND "${ir_dump}" "opcode=print" ir_instruction)
string(FIND "${source_map}" "dmm-source-map-v1" map_header)
string(FIND "${source_map}" "function=\"main\" source=\"${source}\" ir=1 span=1:" map_instruction)
if(NOT ast_header EQUAL 0 OR ast_declaration LESS 0 OR ast_statement LESS 0 OR
   NOT ir_header EQUAL 0 OR ir_instruction LESS 0 OR NOT map_header EQUAL 0 OR
   map_instruction LESS 0)
    message(FATAL_ERROR "Stable dump/source-map schema is incomplete")
endif()
file(SHA256 "${source}" source_hash)
execute_process(COMMAND "${COMPILER}" -o "${source}" "${source}"
    RESULT_VARIABLE conflict_result ERROR_VARIABLE conflict_error)
file(SHA256 "${source}" protected_hash)
if(conflict_result EQUAL 0 OR NOT source_hash STREQUAL protected_hash)
    message(FATAL_ERROR "Compiler did not protect a source file from output overwrite")
endif()
