cmake_minimum_required(VERSION 3.21)
if(NOT DEFINED COMPILER OR NOT DEFINED OUTPUT_DIR)
    message(FATAL_ERROR "COMPILER and OUTPUT_DIR are required")
endif()
file(MAKE_DIRECTORY "${OUTPUT_DIR}")
set(source "${OUTPUT_DIR}/input.dmm")
set(first "${OUTPUT_DIR}/first.s")
set(second "${OUTPUT_DIR}/second.s")
file(WRITE "${source}" "func main() -> void { println(1); }")
execute_process(COMMAND "${COMPILER}" --deterministic -o "${first}" "${source}" RESULT_VARIABLE first_result)
execute_process(COMMAND "${COMPILER}" "${source}" --deterministic -o "${second}" RESULT_VARIABLE second_result)
execute_process(COMMAND "${COMPILER}" --version RESULT_VARIABLE version_result OUTPUT_VARIABLE version)
if(NOT first_result EQUAL 0 OR NOT second_result EQUAL 0 OR NOT version_result EQUAL 0)
    message(FATAL_ERROR "CLI command failed")
endif()
file(SHA256 "${first}" first_hash)
file(SHA256 "${second}" second_hash)
if(NOT first_hash STREQUAL second_hash OR NOT version MATCHES "DMM Compiler [0-9]+\\.[0-9]+\\.[0-9]+")
    message(FATAL_ERROR "Deterministic output or version reporting failed")
endif()
file(SHA256 "${source}" source_hash)
execute_process(COMMAND "${COMPILER}" -o "${source}" "${source}"
    RESULT_VARIABLE conflict_result ERROR_VARIABLE conflict_error)
file(SHA256 "${source}" protected_hash)
if(conflict_result EQUAL 0 OR NOT source_hash STREQUAL protected_hash)
    message(FATAL_ERROR "Compiler did not protect a source file from output overwrite")
endif()
