cmake_minimum_required(VERSION 3.21)
# A fresh installation must not retain source files removed by a migration.
string(TIMESTAMP installation_id "%Y%m%d%H%M%S" UTC)
set(work "${OUTPUT_DIR}/allocation faults/${installation_id}")
file(MAKE_DIRECTORY "${work}/bin" "${work}/case")
get_filename_component(compiler_name "${COMPILER}" NAME)
file(COPY_FILE "${COMPILER}" "${work}/bin/${compiler_name}")
file(COPY "${SOURCE_DIR}/stdlib" DESTINATION "${work}/share/dmm")
# Instrument ordinary allocator source only in this isolated installation.
set(allocator "${work}/share/dmm/stdlib/core/raw/memory.dmm")
file(READ "${allocator}" source)
set(allocation "return __dmm_intrinsic_alloc(bytes);")
string(FIND "${source}" "${allocation}" position)
if(position LESS 0)
    message(FATAL_ERROR "Allocator instrumentation anchor is missing")
endif()
string(REPLACE "${allocation}" "if(testAllocationFailure) { testAllocationFailure=false; return core_null(); }\n    var result:*u8=__dmm_intrinsic_alloc(bytes);\n    if(result!=core_null()) { testLiveAllocations+=1; }\n    return result;" source "${source}")
string(REPLACE "__dmm_intrinsic_release(data);" "if(data!=core_null()) { testLiveAllocations-=1; }\n    __dmm_intrinsic_release(data);" source "${source}")
file(WRITE "${allocator}" "${source}\nvar testAllocationFailure:bit=false;\nvar testLiveAllocations:usize=0;\npub func testFailNextAllocation()->void { testAllocationFailure=true; }\npub func testOutstandingAllocations()->usize { return testLiveAllocations; }\n")
if(NOT DEFINED FAULT_FIXTURES)
    set(FAULT_FIXTURES collection_allocation_faults)
endif()
foreach(fixture IN LISTS FAULT_FIXTURES)
file(COPY_FILE "${SOURCE_DIR}/tests/stdlib/${fixture}/dmm.manifest" "${work}/case/dmm.manifest")
file(COPY_FILE "${SOURCE_DIR}/tests/stdlib/${fixture}/${fixture}.dmm" "${work}/case/main.dmm")
foreach(level 0 1)
    set(program "${work}/case/program_${level}.exe")
    execute_process(COMMAND "${work}/bin/${compiler_name}" "-O${level}" --emit=exe
        "${work}/case/main.dmm" -o "${program}" RESULT_VARIABLE status ERROR_VARIABLE errors TIMEOUT 60)
    if(NOT status EQUAL 0)
        message(FATAL_ERROR "Collection allocation faults O${level}: ${errors}")
    endif()
    execute_process(COMMAND "${program}" RESULT_VARIABLE status TIMEOUT 15)
    if(NOT status EQUAL 0)
        message(FATAL_ERROR "Collection allocation faults O${level} destruction/content check: ${status}")
    endif()
endforeach()
endforeach()
