include("${CMAKE_CURRENT_LIST_DIR}/source_fixture.cmake")
cmake_minimum_required(VERSION 3.21)
get_filename_component(ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
include("${CMAKE_CURRENT_LIST_DIR}/standalone_link.cmake")
file(MAKE_DIRECTORY "${OUTPUT_DIR}")

# Exercise widths and unsigned conversion paths without relying on folding.
foreach(name byte_regions fixed_integers memory_foundations type_metadata io_streams slice_bounds slice_negative slice_null slice_overflow)
    set(trapping FALSE)
    set(source "${ROOT}/tests/execution/core/${name}/${name}.dmm")
    if(name MATCHES "^slice_")
        set(trapping TRUE)
        set(source "${OUTPUT_DIR}/${name}/input.dmm")
        if(name STREQUAL "slice_bounds")
            set(body "var backing:i32[2]; var values:i32[]=backing; var index:usize=values.length; return values[index].(int);")
        elseif(name STREQUAL "slice_negative")
            set(body "var backing:i32[2]; var count:int=-1; var values=slice(&backing[0],count); return values.length.(int);")
        elseif(name STREQUAL "slice_null")
            set(body "var values=slice(core.null<i32>(),1); return values.length.(int);")
        else()
            set(body "var backing:i64[1]; var count:usize=9223372036854775807; var values=slice(&backing[0],count); return values.length.(int);")
        endif()
        dmm_test_write("${source}" "import <stdlib/core>\nfunc main() -> int { ${body} }")
        set(expected "")
    else()
        file(READ "${ROOT}/tests/execution/core/${name}/${name}.expected" expected)
    endif()
    string(REPLACE "\r\n" "\n" expected "${expected}")
    foreach(level 0 1)
        foreach(mode native intel att)
            set(work "${OUTPUT_DIR}/${name}_${level}_${mode}")
            file(MAKE_DIRECTORY "${work}")
            set(program "${work}/program.exe")
            if(mode STREQUAL "native")
                set(options --emit=exe)
                set(artifact "${program}")
            else()
                set(options --emit=asm "--syntax=${mode}")
                set(artifact "${work}/program.s")
            endif()
            execute_process(COMMAND "${COMPILER}" "-O${level}" ${options}
                "${source}" -o "${artifact}"
                RESULT_VARIABLE result ERROR_VARIABLE errors TIMEOUT 30)
            if(NOT result STREQUAL "0")
                message(FATAL_ERROR "${name}/O${level}/${mode}: compilation failed ${errors}")
            endif()
            if(NOT mode STREQUAL "native")
                execute_process(COMMAND "${ASSEMBLER}" ${STANDALONE_FLAGS} "${artifact}"
                    ${SYSTEM_LIBRARIES} -o "${program}" RESULT_VARIABLE result ERROR_VARIABLE errors TIMEOUT 30)
                if(NOT result STREQUAL "0")
                    message(FATAL_ERROR "${name}/O${level}/${mode}: assembly failed ${errors}")
                endif()
            endif()
            execute_process(COMMAND "${program}" WORKING_DIRECTORY "${work}"
                RESULT_VARIABLE result OUTPUT_VARIABLE actual ERROR_VARIABLE errors TIMEOUT 10)
            string(REPLACE "\r\n" "\n" actual "${actual}")
            if(trapping)
                if(NOT result MATCHES "Illegal instruction|SIGILL|^-1073741795$|^3221225501$" OR NOT actual STREQUAL "")
                    message(FATAL_ERROR "${name}/O${level}/${mode}: expected immediate trap, got ${result} ${actual}")
                endif()
            elseif(NOT result STREQUAL "0" OR NOT actual STREQUAL expected OR NOT errors STREQUAL "")
                message(FATAL_ERROR "${name}/O${level}/${mode}: execution failed ${result}\n${actual}\n${errors}")
            endif()
        endforeach()
    endforeach()
endforeach()

foreach(level 0 1)
    set(source "${OUTPUT_DIR}/exit/exit.dmm")
    dmm_test_write( "${source}" "import <stdlib/core>\nfunc main() -> void { core_exit(7); core_trap(); }")
    set(program "${OUTPUT_DIR}/exit_${level}.exe")
    execute_process(COMMAND "${COMPILER}" "-O${level}" "${source}" -o "${program}"
        RESULT_VARIABLE result ERROR_VARIABLE errors TIMEOUT 30)
    if(NOT result STREQUAL "0")
        message(FATAL_ERROR "core_exit/O${level}: compilation failed ${errors}")
    endif()
    execute_process(COMMAND "${program}" RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE errors TIMEOUT 10)
    if(NOT result STREQUAL "7" OR NOT output STREQUAL "" OR NOT errors STREQUAL "")
        message(FATAL_ERROR "core_exit/O${level}: expected exit 7, got ${result} ${output}${errors}")
    endif()
endforeach()
