cmake_minimum_required(VERSION 3.21)
file(MAKE_DIRECTORY "${OUTPUT_DIR}")
file(GLOB_RECURSE fixtures "${SOURCE_DIR}/tests/rejection/*.dmm")
set(checked 0)
foreach(source IN LISTS fixtures)
    execute_process(COMMAND "${COMPILER}" --formatError -o "${OUTPUT_DIR}/reject.s" "${source}"
        RESULT_VARIABLE result ERROR_VARIABLE json ENCODING UTF-8 TIMEOUT 5)
    if(NOT result EQUAL 1)
        message(FATAL_ERROR "Rejection returned ${result}: ${source}\n${json}")
    endif()
    string(JSON count LENGTH "${json}" errors)
    string(JSON total GET "${json}" summary errorCount)
    string(JSON omitted GET "${json}" summary suppressedErrorCount)
    math(EXPR displayed "${total}-${omitted}")
    if(count LESS 1 OR NOT count EQUAL displayed)
        message(FATAL_ERROR "Inconsistent diagnostic summary: ${source}\n${json}")
    endif()
    execute_process(COMMAND "${COMPILER}" -o "${OUTPUT_DIR}/reject.s" "${source}"
        RESULT_VARIABLE human_result ERROR_VARIABLE human ENCODING UTF-8 TIMEOUT 5)
    math(EXPR last "${count}-1")
    foreach(i RANGE 0 ${last})
        string(JSON message GET "${json}" errors ${i} message)
        string(JSON code GET "${json}" errors ${i} errorCode)
        string(JSON line GET "${json}" errors ${i} line)
        string(JSON column GET "${json}" errors ${i} column)
        string(FIND "${human}" "${code}" code_position)
        string(FIND "${human}" "${message}" message_position)
        if(message STREQUAL "" OR code_position LESS 0 OR message_position LESS 0)
            message(FATAL_ERROR "Human/JSON mismatch: ${source}\n${json}\n${human}")
        endif()
        if(line GREATER 0)
            string(JSON filename GET "${json}" errors ${i} filename)
            string(JSON context GET "${json}" errors ${i} sourceLine)
            string(JSON end_line GET "${json}" errors ${i} endLine)
            string(JSON end_column GET "${json}" errors ${i} endColumn)
            file(READ "${filename}" remaining)
            string(REPLACE "\r" "" remaining "${remaining}")
            set(current 1)
            while(current LESS line)
                string(FIND "${remaining}" "\n" newline)
                if(newline LESS 0)
                    message(FATAL_ERROR "Diagnostic points outside source: ${json}")
                endif()
                math(EXPR start "${newline}+1")
                string(SUBSTRING "${remaining}" ${start} -1 remaining)
                math(EXPR current "${current}+1")
            endwhile()
            string(FIND "${remaining}" "\n" newline)
            if(newline GREATER_EQUAL 0)
                string(SUBSTRING "${remaining}" 0 ${newline} expected)
            else()
                set(expected "${remaining}")
            endif()
            string(FIND "${human}" "${filename}:${line}:${column}" location_position)
            if(NOT context STREQUAL expected OR column LESS 1 OR end_line LESS line OR
               (end_line EQUAL line AND end_column LESS column) OR location_position LESS 0)
                message(FATAL_ERROR "Incorrect source context/span: ${source}\n${json}\n${human}")
            endif()
        endif()
    endforeach()
    math(EXPR checked "${checked}+1")
endforeach()
message(STATUS "Audited human and JSON diagnostics for ${checked} rejection fixtures")
