cmake_minimum_required(VERSION 3.21)
file(MAKE_DIRECTORY "${OUTPUT_DIR}")
function(check_case name text expected_code expected_line expected_column expected_message)
    set(source "${OUTPUT_DIR}/${name}.dmm")
    file(WRITE "${source}" "${text}")
    execute_process(COMMAND "${COMPILER}" --emit=asm --formatError -o "${OUTPUT_DIR}/result.s" "${source}"
        RESULT_VARIABLE result ERROR_VARIABLE json ENCODING UTF-8 TIMEOUT 5)
    string(JSON code GET "${json}" errors 0 errorCode)
    string(JSON line GET "${json}" errors 0 line)
    string(JSON column GET "${json}" errors 0 column)
    string(JSON message GET "${json}" errors 0 message)
    string(FIND "${message}" "${expected_message}" found)
    if(NOT result EQUAL 1 OR NOT code STREQUAL expected_code OR NOT line EQUAL expected_line OR
       NOT column EQUAL expected_column OR found LESS 0)
        message(FATAL_ERROR "${name}: incorrect diagnostic: ${json}")
    endif()
    set(last_json "${json}" PARENT_SCOPE)
endfunction()
check_case(initializer "func main() -> int {\nvar value:int = \"bad\";\nreturn 0;\n}" T103 2 17 "got 'string', expected 'int'")
string(JSON end_column GET "${last_json}" errors 0 endColumn)
if(NOT end_column EQUAL 22)
    message(FATAL_ERROR "Initializer does not underline the actual expression: ${last_json}")
endif()
check_case(undefined "func main() -> int {\nreturn missing;\n}" S100 2 8 "Undefined variable 'missing'")
string(JSON count LENGTH "${last_json}" errors)
if(NOT count EQUAL 1)
    message(FATAL_ERROR "Unresolved value generated a conversion cascade: ${last_json}")
endif()
check_case(assignment "func main() -> void {\nvar value:int;\nvalue = \"bad\";\n}" T103 3 9 "got 'string', expected 'int'")
check_case(return_type "func main() -> int {\nreturn \"bad\";\n}" T103 2 8 "got 'string', expected 'int'")
check_case(builtin "func main() -> void {\nstrlen(1);\n}" T103 2 1 "expected (string)")
check_case(argument_count "func main() -> void {\nstrlen();\n}" S103 2 1 "expects 1 arguments but received 0")
check_case(expression "func main() -> int {\nvar value = ;\nreturn 0;\n}" P100 2 13 "Expected expression; found ';'")
check_case(char "func main() -> void {\nvar value = 'ab';\n}" L107 2 13 "exactly one byte")
check_case(decimal "func main() -> void {\nvar value = 1.2.3;\n}" L106 2 13 "multiple decimal points")
check_case(newline_string "func main() -> void {\nvar value = \"bad\n\";\n}" L100 2 13 "Unclosed string")
check_case(escape "func main() -> void {\nvar value = \"bad\\q\";\n}" L102 2 17 "Unknown escape sequence")
check_case(unicode "func main() -> void {\nα ?\n}" L103 2 1 "U+03B1")
string(JSON column GET "${last_json}" errors 1 column)
if(NOT column EQUAL 3)
    message(FATAL_ERROR "Unicode was counted as UTF-8 bytes: ${last_json}")
endif()
check_case(duplicate "func main() -> void {\nvar value = 1;\nvar value = 2;\n}" S112 3 5 "Duplicate variable 'value'")
string(JSON previous_line GET "${last_json}" errors 0 children 0 line)
if(NOT previous_line EQUAL 2)
    message(FATAL_ERROR "Duplicate definition lacks the correct original location: ${last_json}")
endif()
check_case(brace "func main() -> void {\n" P104 2 1 "reached end of file")
string(JSON opening_line GET "${last_json}" errors 0 children 0 line)
if(NOT opening_line EQUAL 1)
    message(FATAL_ERROR "Missing brace lacks its opening location: ${last_json}")
endif()
check_case(no_main "func helper() -> void {}" C100 0 0 "Program must define main")
check_case(import "import (\"absent.dmm\")\nfunc main() -> void {}" C104 1 9 "absent.dmm")
check_case(limit "func main() -> void {\n? ? ? ? ? ? ? ? ? ? ? ?\n}" L103 2 1 "Unknown character")
string(JSON displayed LENGTH "${last_json}" errors)
string(JSON count GET "${last_json}" summary errorCount)
string(JSON omitted GET "${last_json}" summary suppressedErrorCount)
if(NOT displayed EQUAL 12 OR NOT count EQUAL 12 OR NOT omitted EQUAL 0)
    message(FATAL_ERROR "Display limit/summary is incorrect: ${last_json}")
endif()
execute_process(COMMAND "${COMPILER}" --emit=asm -o "${OUTPUT_DIR}/result.s" "${OUTPUT_DIR}/limit.dmm"
    RESULT_VARIABLE result ERROR_VARIABLE human ENCODING UTF-8 TIMEOUT 5)
if(NOT human MATCHES "2 additional errors omitted.*display limit: 10")
    message(FATAL_ERROR "Human display limit is missing its omission notice: ${human}")
endif()
file(WRITE "${OUTPUT_DIR}/valid.dmm" "func main() -> void {}")
execute_process(COMMAND "${COMPILER}" --emit=asm --formatError -o "${OUTPUT_DIR}/absent/result.s" "${OUTPUT_DIR}/valid.dmm"
    RESULT_VARIABLE result ERROR_VARIABLE json ENCODING UTF-8 TIMEOUT 5)
string(JSON count LENGTH "${json}" errors)
string(JSON code GET "${json}" errors 0 errorCode)
string(JSON message GET "${json}" errors 0 message)
if(NOT result EQUAL 1 OR NOT count EQUAL 1 OR NOT code STREQUAL "G103" OR NOT message MATCHES "Could not open assembly output.*absent/result.s.*:")
    message(FATAL_ERROR "Output failure is missing path/reason or reported twice: ${json}")
endif()
execute_process(COMMAND "${COMPILER}" --emit=asm --formatError --dump-ast "${OUTPUT_DIR}/absent/result.ast" -o "${OUTPUT_DIR}/result.s" "${OUTPUT_DIR}/valid.dmm"
    RESULT_VARIABLE result ERROR_VARIABLE json ENCODING UTF-8 TIMEOUT 5)
string(JSON code GET "${json}" errors 0 errorCode)
string(JSON message GET "${json}" errors 0 message)
if(NOT result EQUAL 1 OR NOT code STREQUAL "C106" OR NOT message MATCHES "absent/result.ast")
    message(FATAL_ERROR "Dump failure is missing its output path: ${json}")
endif()
execute_process(COMMAND "${COMPILER}" --emit=asm --formatError --source-map "${OUTPUT_DIR}/absent/result.map" -o "${OUTPUT_DIR}/result.s" "${OUTPUT_DIR}/valid.dmm"
    RESULT_VARIABLE result ERROR_VARIABLE json ENCODING UTF-8 TIMEOUT 5)
string(JSON count LENGTH "${json}" errors)
string(JSON message GET "${json}" errors 0 message)
if(NOT result EQUAL 1 OR NOT count EQUAL 1 OR NOT message MATCHES "Could not open source-map output.*absent/result.map")
    message(FATAL_ERROR "Source-map failure has incorrect output path or duplicate reports: ${json}")
endif()
