cmake_minimum_required(VERSION 3.21)
if(NOT DEFINED COMPILER OR NOT DEFINED OUTPUT_DIR)
    message(FATAL_ERROR "COMPILER and OUTPUT_DIR are required")
endif()
file(MAKE_DIRECTORY "${OUTPUT_DIR}")
set(source "${OUTPUT_DIR}/invalid.dmm")
file(WRITE "${source}" "func main() -> void { @; }")
execute_process(COMMAND "${COMPILER}" "${source}" --formatError
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE diagnostics)
if(result EQUAL 0)
    message(FATAL_ERROR "Invalid source was accepted")
endif()
string(JSON error_count ERROR_VARIABLE json_error GET "${diagnostics}" summary errorCount)
if(json_error OR error_count LESS 1)
    message(FATAL_ERROR "Diagnostics are not valid JSON: ${diagnostics}")
endif()
file(WRITE "${source}" "func main() -> void {} $ $ $ $ $ $ $ $ $ $ $ $\n")
execute_process(COMMAND "${COMPILER}" --formatError "${source}"
    RESULT_VARIABLE result ERROR_VARIABLE diagnostics)
string(JSON error_count ERROR_VARIABLE json_error GET "${diagnostics}" summary errorCount)
if(result EQUAL 0 OR json_error OR error_count LESS 10)
    message(FATAL_ERROR "Multiple diagnostics were not emitted as one JSON document: ${diagnostics}")
endif()
