cmake_minimum_required(VERSION 3.21)
set(work "${OUTPUT_DIR}/consumer")
file(MAKE_DIRECTORY "${work}/vendor/examples/http_server")
file(COPY "${SOURCE_DIR}/tests/stdlib/http_library/http_library.dmm"
          "${SOURCE_DIR}/tests/stdlib/http_library/dmm.manifest" DESTINATION "${work}")
file(COPY "${SOURCE_DIR}/examples/http_server/http"
          "${SOURCE_DIR}/examples/http_server/dmm.manifest" DESTINATION "${work}/vendor/examples/http_server")
foreach(level 0 1)
    set(program "${OUTPUT_DIR}/http_library_${level}.exe")
    execute_process(COMMAND "${COMPILER}" "-O${level}" "${work}/http_library.dmm" -o "${program}"
        RESULT_VARIABLE status ERROR_VARIABLE errors TIMEOUT 90)
    if(NOT status STREQUAL "0")
        message(FATAL_ERROR "HTTP external consumer/O${level}: ${status}: ${errors}")
    endif()
    execute_process(COMMAND "${program}" RESULT_VARIABLE status TIMEOUT 20)
    if(NOT status STREQUAL "0")
        message(FATAL_ERROR "HTTP public API/O${level}: exit ${status}")
    endif()
    foreach(target elf coff)
        execute_process(COMMAND "${COMPILER}" "-O${level}" --emit=obj "--target=${target}" "${work}/http_library.dmm"
            -o "${OUTPUT_DIR}/http_library_${level}_${target}.o" RESULT_VARIABLE status ERROR_VARIABLE errors TIMEOUT 90)
        if(NOT status STREQUAL "0")
            message(FATAL_ERROR "HTTP external consumer/${target}/O${level}: ${status}: ${errors}")
        endif()
    endforeach()
endforeach()
# Borrowed request views must not escape the owning request, even across modules.
foreach(view path header)
    set(rejection "${OUTPUT_DIR}/rejections/${view}")
    file(MAKE_DIRECTORY "${rejection}/vendor/examples/http_server")
    file(COPY "${SOURCE_DIR}/examples/http_server/http"
              "${SOURCE_DIR}/examples/http_server/dmm.manifest" DESTINATION "${rejection}/vendor/examples/http_server")
    file(COPY "${SOURCE_DIR}/tests/stdlib/http_library/dmm.manifest" DESTINATION "${rejection}")
    set(prefix "package main; import (\"stdlib/core\" \"stdlib/text\" \"examples/http_server/http\");\n")
    set(setup "var input=text.bytes(\"GET / HTTP/1.1\\r\\nHost: localhost\\r\\n\\r\\n\");var owner=http.parseRequest(&input,http.config())?;")
    if(view STREQUAL "path")
        set(body "return core.Result<text.Text<'a>,http.Error>.Ok(owner.path());")
    else()
        set(body "match(owner.header(\"Host\")){Some(value)=>return core.Result<text.Text<'a>,http.Error>.Ok(value);None=>return core.Result<text.Text<'a>,http.Error>.Err(http.Error{kind:http.ErrorKind.InvalidRequest,message:\"missing\"});}")
    endif()
    file(WRITE "${rejection}/case.dmm" "${prefix}func bad<'a>()->core.Result<text.Text<'a>,http.Error>{${setup}${body}}func main()->int{return 0;}")
    execute_process(COMMAND "${COMPILER}" --emit=obj "${rejection}/case.dmm" -o "${rejection}/case.o"
        RESULT_VARIABLE status ERROR_VARIABLE errors TIMEOUT 90)
    if(status STREQUAL "0" OR NOT errors MATCHES "borrow|origin|lifetime")
        message(FATAL_ERROR "HTTP ${view} view escaped its owner: ${status}: ${errors}")
    endif()
endforeach()
# Reuse the application harness only for HTTP; other examples have their own gate.
set(EXAMPLES http_server)
set(OUTPUT_DIR "${OUTPUT_DIR}/server")
include("${SOURCE_DIR}/tests/application_examples_test.cmake")
