cmake_minimum_required(VERSION 3.21)
include("${CMAKE_CURRENT_LIST_DIR}/standalone_link.cmake")
set(work "${OUTPUT_DIR}/packages_v2")
file(MAKE_DIRECTORY "${work}")
function(source path text)
    get_filename_component(directory "${work}/${path}" DIRECTORY)
    file(MAKE_DIRECTORY "${directory}")
    file(WRITE "${work}/${path}" "${text}")
endfunction()
function(module name)
    source("${name}/dmm.manifest" "module example.com/${name}\ndmm 2026-09-22-dev\n")
endfunction()
function(build name package expected)
    foreach (level 0 1)
        foreach (mode exe intel att)
            set(program "${work}/${name}/${package}/test_${level}_${mode}.exe")
            if (mode STREQUAL "exe")
                set(options --emit=exe)
                set(artifact "${program}")
            else ()
                set(options --emit=asm "--syntax=${mode}")
                set(artifact "${program}.s")
            endif ()
            execute_process(COMMAND "${COMPILER}" "-O${level}" ${options} "${work}/${name}/${package}/main.dmm" -o "${artifact}"
                    RESULT_VARIABLE result ERROR_VARIABLE errors TIMEOUT 30)
            if (NOT result STREQUAL "0")
                message(FATAL_ERROR "${name}/${package}/${mode}/O${level}: ${errors}")
            endif ()
            if (NOT mode STREQUAL "exe")
                execute_process(COMMAND "${ASSEMBLER}" ${STANDALONE_FLAGS} "${artifact}" ${SYSTEM_LIBRARIES} -o "${program}"
                        RESULT_VARIABLE result ERROR_VARIABLE errors TIMEOUT 30)
                if (NOT result STREQUAL "0")
                    message(FATAL_ERROR "Package assembly failed: ${errors}")
                endif ()
            endif ()
            execute_process(COMMAND "${program}" RESULT_VARIABLE result TIMEOUT 10)
            if (NOT result STREQUAL "${expected}")
                message(FATAL_ERROR "${name}/${mode}/O${level}: exit ${result}, expected ${expected}")
            endif ()
        endforeach ()
    endforeach ()
endfunction()
function(reject name code)
    foreach (format human json)
        set(options)
        if (format STREQUAL "json")
            set(options --formatError)
        endif ()
        execute_process(COMMAND "${COMPILER}" ${options} "${work}/${name}/main.dmm" -o "${work}/${name}/bad.exe"
                RESULT_VARIABLE result ERROR_VARIABLE errors TIMEOUT 10)
        if (NOT result STREQUAL "1" OR NOT errors MATCHES "${code}")
            message(FATAL_ERROR "${name}/${format}: expected ${code}: ${errors}")
        endif ()
        if (format STREQUAL "json")
            string(JSON count LENGTH "${errors}" errors)
        endif ()
    endforeach ()
    set(last_errors "${errors}" PARENT_SCOPE)
endfunction()
module(discovery)
source("discovery/cmd/one/main.dmm" "package main; import lex \"example.com/discovery/lexer\"; func main() -> int { var t:lex.Token; t.kind=2; return lex.tokenize(t); }")
source("discovery/cmd/two/main.dmm" "package main; import \"example.com/discovery/lexer\"; func main() -> int { return lexer.answer; }")
source("discovery/lexer/a.dmm" "package lexer; pub struct Token { pub var kind:int; var hidden:int; pub func get() -> int { return kind; } } pub var answer:int=7; pub const Offset:int=5; pub func tokenize(t:Token) -> int { return scan(t)+Offset; }")
source("discovery/lexer/z.dmm" "package lexer; func scan(t:Token) -> int { return t.get(); }")
source("discovery/lexer/child/broken.dmm" "not a source in the parent package")
build(discovery cmd/one 7)
build(discovery cmd/two 7)
source("discovery/lexer/a.dmm" "package lexer; func scan(t:Token) -> int { return t.get(); }")
source("discovery/lexer/z.dmm" "package lexer; pub struct Token { pub var kind:int; var hidden:int; pub func get() -> int { return kind; } } pub var answer:int=7; pub const Offset=Later; const Later=5; pub func tokenize(t:Token) -> int { return scan(t)+Offset; }")
build(discovery cmd/one 7)
foreach (mode obj asm)
    execute_process(COMMAND "${COMPILER}" "--emit=${mode}" "${work}/discovery/lexer/a.dmm" -o "${work}/library.${mode}"
            RESULT_VARIABLE result ERROR_VARIABLE errors TIMEOUT 10)
    if (NOT result STREQUAL "0")
        message(FATAL_ERROR "Library package incorrectly needs main: ${errors}")
    endif ()
endforeach ()

module(initialization)
source("initialization/c/c.dmm" "package c; var calls:int; func initialize() -> int { calls+=1; return 1; } pub var value:int=initialize(); pub func initializationCount() -> int { return calls; }")
source("initialization/a/a.dmm" "package a; import \"example.com/initialization/c\"; pub var value:int=c.value*10+2;")
source("initialization/b/b.dmm" "package b; import \"example.com/initialization/c\"; pub var value:int=c.value*10+3;")
source("initialization/main.dmm" "package main; import \"example.com/initialization/b\"; import \"example.com/initialization/a\"; import \"example.com/initialization/c\"; var combined:int=a.value*100+b.value; func main() -> int { if (combined == 1213 && c.initializationCount() == 1) { return 0; } return 1; }")
build(initialization . 0)

module(initialization_cycle)
source("initialization_cycle/main.dmm" "package main; var first:int=second; var second:int=first; func main() -> int { return 0; }")
reject(initialization_cycle T102)
if (NOT last_errors MATCHES "Package variable initializer contains a dependency cycle")
    message(FATAL_ERROR "Package initializer cycle diagnostic is missing")
endif ()

module(generics)
source("generics/main.dmm" "package main; import a \"example.com/generics/a\"; import b \"example.com/generics/b\"; import \"stdlib\"; func main() -> int { var item:a.User; item.value=9; var r:stdlib.Result<a.User,int> = stdlib.Result<a.User,int>.Ok(item); var copied:a.User=a.identity(r.Ok()); var other:b.User; other.value=2; return copied.value-other.value; }")
source("generics/a/a.dmm" "package a; pub struct User { pub var value:int; } pub func identity<T>(value:T) -> T { return value; }")
source("generics/b/b.dmm" "package b; pub struct User { pub var value:int; }")
build(generics . 7)
source("generics/main.dmm" "package main; import a \"example.com/generics/a\"; import b \"example.com/generics/b\"; func main() -> int { var first:a.User; var second:b.User=first; return 0; }")
reject(generics T103)
module(vendored)
source("vendored/dmm.manifest" "module example.com/vendored\ndmm 2026-09-22-dev\nrequire (\n example.com/lib v1.2.0\n)\n")
source("vendored/vendor/example.com/lib/dmm.manifest" "module example.com/lib\ndmm 2026-09-22-dev\n")
source("vendored/vendor/example.com/lib/api/api.dmm" "package api; pub func answer() -> int { return 7; }")
source("vendored/main.dmm" "package main; import api \"example.com/lib/api\"; func main() -> int { return api.answer(); }")
build(vendored . 7)
source("vendored/vendor/example.com/lib/internal/secret/a.dmm" "package secret; pub func answer() -> int { return 7; }")
source("vendored/main.dmm" "package main; import \"example.com/lib/internal/secret\"; func main() -> int { return secret.answer(); }")
reject(vendored S126)
module(internal)
source("internal/area/internal/secret/a.dmm" "package secret; pub func answer() -> int { return 7; }")
source("internal/area/cmd/main.dmm" "package main; import \"example.com/internal/area/internal/secret\"; func main() -> int { return secret.answer(); }")
build(internal area/cmd 7)
source("internal/main.dmm" "package main; import \"example.com/internal/area/internal/secret\"; func main() -> int { return secret.answer(); }")
reject(internal S126)
module(cycle)
source("cycle/main.dmm" "package main; import \"example.com/cycle/a\"; func main() -> int { return 0; }")
source("cycle/a/a.dmm" "package a; import \"example.com/cycle/b\";")
source("cycle/b/b.dmm" "package b; import \"example.com/cycle/c\";")
source("cycle/c/c.dmm" "package c; import \"example.com/cycle/a\";")
reject(cycle S124)
if (NOT last_errors MATCHES "example.com/cycle/a -> example.com/cycle/b -> example.com/cycle/c -> example.com/cycle/a")
    message(FATAL_ERROR "Cycle diagnostic lacks the complete cycle")
endif ()
module(privacy)
source("privacy/api/api.dmm" "package api; pub struct Token { var hidden:int; pub var visible:int; func hiddenMethod() -> int { return 3; } } func hidden() -> int { return 7; }")
source("privacy/main.dmm" "package main; import \"example.com/privacy/api\"; func main() -> int { return api.hidden(); }")
reject(privacy S125)
source("privacy/main.dmm" "package main; import \"example.com/privacy/api\"; func main() -> int { var t:api.Token; return t.hidden; }")
reject(privacy S125)
source("privacy/main.dmm" "package main; import \"example.com/privacy/api\"; func main() -> int { var t:api.Token; return t.hiddenMethod(); }")
reject(privacy S125)
source("privacy/main.dmm" "package main; import \"example.com/privacy/api\"; func main() -> int { return hidden(); }")
reject(privacy S101)
foreach (name missing_package misplaced_package mismatched duplicate missing dependency alias invalid_module version no_main bad_main library_executable file_import)
    module(${name})
endforeach ()
source("missing_package/main.dmm" "func main() -> int { return 0; }")
reject(missing_package P120)
source("misplaced_package/main.dmm" "package main; func f() -> void {} package other; func main() -> int { return 0; }")
reject(misplaced_package P120)
source("mismatched/main.dmm" "package main; func main() -> int { return 0; }")
source("mismatched/other.dmm" "package other;")
reject(mismatched S121)
source("duplicate/main.dmm" "package main; const value:int=1; func main() -> int { return value; }")
source("duplicate/other.dmm" "package main; const value:int=2;")
reject(duplicate S112)
source("missing/main.dmm" "package main; import \"example.com/missing/absent\"; func main() -> int { return 0; }")
reject(missing S123)
source("dependency/dmm.manifest" "module example.com/dependency\ndmm 2026-09-22-dev\nrequire example.com/lib v1.0.0\n")
source("dependency/main.dmm" "package main; import \"example.com/lib\"; func main() -> int { return 0; }")
reject(dependency S129)
source("alias/main.dmm" "package main; import . \"stdlib\"; func main() -> int { return 0; }")
reject(alias P127)
source("alias/main.dmm" "package main; import _ \"stdlib\"; func main() -> int { return 0; }")
reject(alias S127)
module(duplicate_generic)
source("duplicate_generic/main.dmm" "package main; func identity<T>(x:T) -> T { return x; } func main() -> int { return 0; }")
source("duplicate_generic/other.dmm" "package main; func identity<U>(x:U) -> U { return x; }")
reject(duplicate_generic S112)
source("dependency/dmm.manifest" "module example.com/dependency\ndmm 2026-09-22-dev\nrequire example.com/lib v-1.0.0\n")
reject(dependency S122)
source("dependency/dmm.manifest" "module example.com/dependency\ndmm 2026-09-22-dev\nrequire example.com/lib v1.0.0 unexpected\n")
reject(dependency S122)
source("alias/main.dmm" "package main; import s \"stdlib\"; import s \"stdlib/core\"; func main() -> int { return 0; }")
reject(alias S127)
source("invalid_module/dmm.manifest" "module ../invalid\ndmm 2026-09-22-dev\n")
source("invalid_module/main.dmm" "package main; func main() -> int { return 0; }")
reject(invalid_module S122)
source("version/dmm.manifest" "module example.com/version\ndmm 9.0\n")
source("version/main.dmm" "package main; func main() -> int { return 0; }")
reject(version S128)
source("edition_date/dmm.manifest" "module example.com/edition_date\ndmm 2026-02-29-dev\n")
source("edition_date/main.dmm" "package main; func main() -> int { return 0; }")
reject(edition_date S128)
if (NOT last_errors MATCHES "invalid DMM edition")
    message(FATAL_ERROR "Invalid calendar date was not diagnosed precisely: ${last_errors}")
endif ()
source("unsupported_edition/dmm.manifest" "module example.com/unsupported_edition\ndmm 2026-09-22-releasecandidate\n")
source("unsupported_edition/main.dmm" "package main; func main() -> int { return 0; }")
reject(unsupported_edition S128)
if (NOT last_errors MATCHES "supports only DMM 2026-09-22-dev")
    message(FATAL_ERROR "Unsupported valid edition was not diagnosed precisely: ${last_errors}")
endif ()
source("legacy_edition/dmm.manifest" "module example.com/legacy_edition\ndmm 0.3\n")
source("legacy_edition/main.dmm" "package main; func main() -> int { return 0; }")
reject(legacy_edition S128)
source("empty_features/dmm.manifest" "module example.com/empty_features\ndmm 2026-09-22-dev\nfeatures = []\n")
source("empty_features/main.dmm" "package main; func main() -> int { return 0; }")
build(empty_features . 0)
source("unknown_feature/dmm.manifest" "module example.com/unknown_feature\ndmm 2026-09-22-dev\nfeatures = [\n    \"not_implemented\",\n]\n")
source("unknown_feature/main.dmm" "package main; func main() -> int { return 0; }")
reject(unknown_feature S130)
source("duplicate_feature/dmm.manifest" "module example.com/duplicate_feature\ndmm 2026-09-22-dev\nfeatures = [\n    \"duplicate\",\n    \"duplicate\",\n]\n")
source("duplicate_feature/main.dmm" "package main; func main() -> int { return 0; }")
reject(duplicate_feature S130)
source("no_main/main.dmm" "package main; func helper() -> int { return 0; }")
reject(no_main C100)
source("bad_main/main.dmm" "package main; func main(x:int) -> int { return x; }")
reject(bad_main T103)
source("library_executable/main.dmm" "package library; pub func answer() -> int { return 7; }")
reject(library_executable C100)
source("file_import/main.dmm" "package main; import \"helper.dmm\"; func main() -> int { return 0; }")
reject(file_import S123)
module(order)
source("order/main.dmm" "package main; const first=last+2; func main() -> int { return first; }")
source("order/z.dmm" "package main; const last=5;")
build(order . 7)
module(origins)
source("origins/api/box.dmm" "package api; pub struct Box<T> { pub var value:T; }")
source("origins/api/wrap.dmm" "package api; pub struct Wrap<T> { pub var value:T; }")
source("origins/main.dmm" "package main; import \"example.com/origins/api\"; func extract<T>(x:api.Box<T>) -> T { return x.value; } func main() -> int { var box:api.Box<int>; box.value=9; var wrap:api.Wrap<int>; wrap.value=2; return extract(box)-wrap.value; }")
build(origins . 7)
module(nested_types)
source("nested_types/api/api.dmm" "package api; pub func middle(values:int[2][3]) -> int[2] { return values[1]; } pub func sum(values:int[2][3]) -> int { return values[0][1]+values[2][0]; }")
source("nested_types/main.dmm" "package main; import \"example.com/nested_types/api\"; func main() -> int { var values:int[2][3]=[[1,2],[3,4],[5,6]]; var row:int[2]=api.middle(values); return api.sum(values)+row[1]-11; }")
build(nested_types . 0)
# Nested modules and executable packages cannot masquerade as libraries.
module(nested)
source("nested/child/dmm.manifest" "module example.com/other\ndmm 2026-09-22-dev\n")
source("nested/child/child.dmm" "package child;")
source("nested/main.dmm" "package main; import \"example.com/nested/child\"; func main() -> int { return 0; }")
reject(nested S105)
module(import_main)
source("import_main/cmd/main.dmm" "package main; func main() -> int { return 0; }")
source("import_main/main.dmm" "package main; import \"example.com/import_main/cmd\"; func main() -> int { return 0; }")
reject(import_main S121)
module(transitive)
source("transitive/dmm.manifest" "module example.com/transitive\ndmm 2026-09-22-dev\nrequire example.com/lib v1.0.0\n")
source("transitive/vendor/example.com/lib/dmm.manifest" "module example.com/lib\ndmm 2026-09-22-dev\nrequire example.com/utils v1.2.0\n")
source("transitive/vendor/example.com/lib/lib.dmm" "package lib; import \"example.com/utils\"; pub func answer() -> int { return utils.answer(); }")
source("transitive/vendor/example.com/utils/dmm.manifest" "module example.com/utils\ndmm 2026-09-22-dev\n")
source("transitive/vendor/example.com/utils/utils.dmm" "package utils; pub func answer() -> int { return 7; }")
source("transitive/main.dmm" "package main; import \"example.com/lib\"; var address:*void; func main() -> int { return lib.answer(); }")
build(transitive . 7)
module(private_interface)
source("private_interface/api/api.dmm" "package api; interface Hidden { func value() -> int; }")
source("private_interface/main.dmm" "package main; import \"example.com/private_interface/api\"; func read<T:api.Hidden>(x:T) -> int { return x.value(); } func main() -> int { return 0; }")
reject(private_interface S125)
module(private_variant)
source("private_variant/api/api.dmm" "package api; pub enum Value { Hidden(int), pub Visible(int) } pub func make() -> Value { return Value.Hidden(7); }")
source("private_variant/main.dmm" "package main; import \"example.com/private_variant/api\"; func main() -> int { var value=api.make(); match (value) { Hidden(x) => { return x; } Visible(x) => { return x; } } }")
reject(private_variant S125)
source("alias/main.dmm" "package main; import main \"stdlib\"; func main() -> int { return 0; }")
reject(alias S127)
