include("${CMAKE_CURRENT_LIST_DIR}/source_fixture.cmake")
cmake_minimum_required(VERSION 3.21)
get_filename_component(ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
file(GLOB_RECURSE sources "${ROOT}/tests/execution/*.dmm" "${ROOT}/tests/regression/*.dmm")
foreach (source IN LISTS sources)
    get_filename_component(name "${source}" NAME_WE)
    foreach (level 0 1)
        set(work "${OUTPUT_DIR}/${name}_O${level}")
        file(MAKE_DIRECTORY "${work}")
        execute_process(COMMAND "${COMPILER}" "-O${level}" "${source}" -o "${work}/program.exe"
                RESULT_VARIABLE result ERROR_VARIABLE errors TIMEOUT 30)
        if (NOT result EQUAL 0)
            message(FATAL_ERROR "O${level} compilation failed: ${source} ${errors}")
        endif ()
        execute_process(COMMAND "${work}/program.exe" WORKING_DIRECTORY "${work}"
                RESULT_VARIABLE result OUTPUT_VARIABLE actual ERROR_VARIABLE errors TIMEOUT 10)
        if (NOT result EQUAL 0 OR NOT errors STREQUAL "")
            message(FATAL_ERROR "O${level} execution failed: ${source} ${result} ${errors}")
        endif ()
        string(REPLACE "\r\n" "\n" actual "${actual}")
        if (level EQUAL 0)
            set(baseline "${actual}")
        elseif (NOT actual STREQUAL baseline)
            message(FATAL_ERROR "IR optimization changed output: ${source}\nO0: ${baseline}\nO1: ${actual}")
        endif ()
    endforeach ()
endforeach ()
foreach (failure division bounds)
    if (failure STREQUAL "division")
        set(source "func bad(x:int) -> int { var unused=1/x; return 0; } func main() -> int { return bad(0); }")
    else ()
        set(source "func bad(i:int) -> int { var a:int[4]; var unused=a[i]; return 0; } func main() -> int { return bad(5); }")
    endif ()
    set(input "${OUTPUT_DIR}/${failure}/${failure}.dmm")
    dmm_test_write("${input}" "${source}")
    foreach (level 0 1)
        set(program "${OUTPUT_DIR}/${failure}_O${level}.exe")
        execute_process(COMMAND "${COMPILER}" "-O${level}" "${input}" -o "${program}" RESULT_VARIABLE result ERROR_VARIABLE errors TIMEOUT 30)
        if (NOT result EQUAL 0)
            message(FATAL_ERROR "Trap fixture did not compile: ${errors}")
        endif ()
        execute_process(COMMAND "${program}" RESULT_VARIABLE result OUTPUT_VARIABLE actual ERROR_VARIABLE errors TIMEOUT 10)
        if (result STREQUAL "0" OR result MATCHES "timeout")
            message(FATAL_ERROR "IR optimization removed a runtime trap: ${failure}/O${level}")
        endif ()
    endforeach ()
endforeach ()
