cmake_minimum_required(VERSION 3.21)
file(MAKE_DIRECTORY "${OUTPUT_DIR}")
set(fixture "${SOURCE_DIR}/tests/language/iterators/iterators.dmm")
foreach(level 0 1)
    set(program "${OUTPUT_DIR}/iterators_${level}.exe")
    execute_process(COMMAND "${COMPILER}" "-O${level}" --emit=exe "${fixture}" -o "${program}"
        RESULT_VARIABLE status ERROR_VARIABLE errors TIMEOUT 60)
    if(NOT status EQUAL 0)
        message(FATAL_ERROR "Iterators O${level}: ${errors}")
    endif()
    execute_process(COMMAND "${program}" RESULT_VARIABLE status TIMEOUT 15)
    if(NOT status EQUAL 0)
        message(FATAL_ERROR "Iterators O${level} execution: ${status}")
    endif()
    foreach(target elf coff)
        foreach(mode obj intel att)
            set(options --emit=obj)
            if(NOT mode STREQUAL obj)
                set(options --emit=asm "--syntax=${mode}")
            endif()
            execute_process(COMMAND "${COMPILER}" "-O${level}" "--target=${target}" ${options}
                "${fixture}" -o "${OUTPUT_DIR}/${target}_${level}_${mode}.out"
                RESULT_VARIABLE status ERROR_VARIABLE errors TIMEOUT 30)
            if(NOT status EQUAL 0)
                message(FATAL_ERROR "Iterators ${target}/O${level}/${mode}: ${errors}")
            endif()
        endforeach()
    endforeach()
endforeach()

file(READ "${fixture}" prefix)
string(REGEX MATCH "func[ \t\r\n]+main[ \t\r\n]*\\([ \t\r\n]*\\)[ \t\r\n]*->[ \t\r\n]*int[ \t\r\n]*\\{" main_signature "${prefix}")
if(main_signature STREQUAL "")
    message(FATAL_ERROR "Could not find the iterator fixture's main function: ${fixture}")
endif()
string(FIND "${prefix}" "${main_signature}" main_position)
string(SUBSTRING "${prefix}" 0 ${main_position} prefix)
set(editor "${OUTPUT_DIR}/editor")
file(MAKE_DIRECTORY "${editor}")
file(WRITE "${editor}/dmm.manifest" "module tests/iterators/editor\ndmm 2026-10-04-dev\nfeatures = [\"async\"]\n")
file(WRITE "${editor}/main.dmm" "${prefix}\nfunc main()->void { var list=sample(); for(var x=list) {} for(var &x=list) {} for(var &mut x=list) {} }\n")
execute_process(COMMAND "${COMPILER}" --ide --dump-ast "${editor}/main.ast" "${editor}/main.dmm"
    RESULT_VARIABLE status ERROR_VARIABLE errors TIMEOUT 30)
if(NOT status EQUAL 0)
    message(FATAL_ERROR "Iterator editor AST validation/serialization: ${errors}")
endif()
function(reject name body expected)
    set(work "${OUTPUT_DIR}/${name}")
    file(MAKE_DIRECTORY "${work}")
    file(WRITE "${work}/dmm.manifest" "module tests/iterators/${name}\ndmm 2026-10-04-dev\nfeatures = [\"async\"]\n")
    file(WRITE "${work}/main.dmm" "${prefix}\n${body}\n")
    execute_process(COMMAND "${COMPILER}" --emit=obj "${work}/main.dmm" -o "${work}/main.o"
        RESULT_VARIABLE status ERROR_VARIABLE errors TIMEOUT 30)
    if(status EQUAL 0 OR NOT errors MATCHES "${expected}")
        message(FATAL_ERROR "Expected rejection ${name} (${expected}): ${status}: ${errors}")
    endif()
endfunction()
reject(missing_value "struct NoIterator { var value:i32; } func main()->void { var source=NoIterator{value:1}; for(var x=source) {} }" "iter|member")
reject(missing_mutable "func main()->void { var source=Counter{limit:3}; for(var &mut x=source) {} }" "iterMut|member")
reject(shared_mutation "func main()->void { var list=sample(); for(var &x=list) { *x=4; } }" "shared checked reference")
reject(shared_source "func main()->void { var list=sample(); var source=&list; for(var &mut x=source) { *x=4; } }" "shared checked reference")
reject(live_source_write "func main()->void { var list=sample(); for(var &mut x=list) { list.values[0]=4; *x+=1; } }" "borrow")
reject(live_source_move "func main()->void { var list=TestList<Owner>{values:[Owner{value:1},Owner{value:2},Owner{value:3}],count:3}; for(var &x=list) { var moved=list; var value=x.value; } }" "borrow")
reject(mutable_outer "func main()->void { var list=sample(); var outside:i32=0; var escaped=&mut outside; for(var &mut x=list) { escaped=x; } var value=*escaped; }" "cannot escape its iteration")
reject(mutable_return "func bad<'a>(list:&'a mut TestList<i32>)->&'a mut i32 { for(var &mut x=list) { return x; } return &mut list.values[0]; } func main()->void { var list=sample(); var value=bad(&mut list); }" "cannot escape its iteration")
reject(mutable_aggregate "func main()->void { var list=sample(); var escaped:stdlib.Option<&mut i32>=stdlib.Option<&mut i32>.None; for(var &mut x=list) { escaped=stdlib.Option<&mut i32>.Some(x); } }" "cannot escape its iteration")
reject(mutable_forward "func identity<'a>(value:&'a mut i32)->&'a mut i32 { return value; } func main()->void { var list=sample(); var outside:i32=0; var escaped=&mut outside; for(var &mut x=list) { escaped=identity(x); } }" "cannot escape its iteration")
reject(mutable_indirect_store "func stash<'a>(dst:&mut stdlib.Option<&'a mut i32>, item:&'a mut i32)->void { *dst=stdlib.Option<&'a mut i32>.Some(item); } func main()->void { var list=sample(); var escaped:stdlib.Option<&mut i32>=stdlib.Option<&mut i32>.None; for(var &mut x=list) { stash(&mut escaped,x); } }" "cannot escape its iteration")
reject(mutable_alias "func main()->void { var list=sample(); for(var &mut x=list) { var a=&mut *x; var b=&mut *x; *a=1; *b=2; } }" "borrow")
reject(mutable_future "async func bad<'a>(list:&'a mut TestList<i32>)->Future<i32> { for(var &mut x=list) { return readAsync(x); } return readAsync(&mut list.values[0]); } func main()->void { var list=sample(); var future=bad(&mut list); var inner=block_on(future); block_on(inner); }" "cannot escape its iteration")
reject(mutable_closure "interface Reader { func __invoke()->i32; } func bad<'a>(list:&'a mut TestList<i32>)->Reader { for(var &mut x=list) { return func [move x]()->i32 { return *x; }; } return func []()->i32 { return 0; }; } func main()->void { var list=sample(); var reader=bad(&mut list); }" "cannot escape its iteration")
reject(self_alias "struct Invalid { var value:i32; func wrong()->void { var whole=&mut self; var part=&mut value; whole.value=1; *part=2; } } func main()->void { var source=Invalid{value:0}; source.wrong(); }" "borrow")
reject(shared_factory_mutation "struct Invalid { var value:i32; func iter()->CounterIterator { var borrow=&mut self; return CounterIterator{index:0,limit:borrow.value}; } } func main()->void { var source=Invalid{value:0}; for(var x=source) {} }" "shared checked reference")
reject(factory_scalar "struct Invalid { func iter()->i32 { return 0; } } func main()->void { var source=Invalid{}; for(var x=source) {} }" "concrete iterator struct")
reject(factory_static "struct Invalid { static func iter()->CounterIterator { return CounterIterator{index:0,limit:0}; } } func main()->void { var source=Invalid{}; for(var x=source) {} }" "instance method")
reject(factory_arguments "struct Invalid { func iter(value:i32)->CounterIterator { return CounterIterator{index:0,limit:value}; } } func main()->void { var source=Invalid{}; for(var x=source) {} }" "parameterless|overload|argument")
reject(next_scalar "struct Invalid { func iter()->Invalid { return Invalid{}; } func next()->i32 { return 0; } } func main()->void { var source=Invalid{}; for(var x=source) {} }" "next.*core.Option")
reject(next_fake_option "enum FakeOption<T> { None, Some(T) } struct Invalid { func iter()->Invalid { return Invalid{}; } func next()->FakeOption<i32> { return FakeOption<i32>.None; } } func main()->void { var source=Invalid{}; for(var x=source) {} }" "next.*core.Option")
reject(next_wrong_shared "struct Invalid { func iterRef()->CounterIterator { return CounterIterator{index:0,limit:0}; } } func main()->void { var source=Invalid{}; for(var &x=source) {} }" "requested shared/mutable binding")
reject(next_wrong_mutable "struct Invalid { func iterMut()->CounterIterator { return CounterIterator{index:0,limit:0}; } } func main()->void { var source=Invalid{}; for(var &mut x=source) {} }" "requested shared/mutable binding")
reject(typed_header "func main()->void { var list=sample(); for(var x:i32=list) {} }" "Iterator for requires")
reject(const_header "func main()->void { var list=sample(); for(const x=list) {} }" "Iterator for requires")
reject(self_free "func main()->void { var value=&self; }" "Unknown|unknown|Undefined")
reject(self_static "struct Invalid { static func wrong()->void { var value=&self; } } func main()->void {}" "Unknown|unknown|Undefined")
reject(self_shadow "struct Invalid { func wrong()->void { var self:i32=0; } } func main()->void {}" "Reserved name")
reject(self_replace "struct Invalid { var value:i32; func wrong()->void { *self=Invalid{value:1}; } } func main()->void {}" "Cannot replace the entire self")
reject(self_move "struct Invalid { func wrong()->void { var moved=self; } } func main()->void {}" "explicit checked borrow")
reject(self_pattern "struct Invalid { func wrong()->void { match(stdlib.Option<i32>.Some(1)) { Some(self)=>{} None=>{} } } } func main()->void {}" "Reserved name")
reject(self_loop "struct Invalid { func wrong()->void { var source=Counter{limit:3}; for(var self=source) {} } } func main()->void {}" "Reserved name")
reject(raw_source "func main()->void { var list=sample(); var raw=(&list).(*TestList<i32>); for(var x=raw) {} }" "Raw pointer member/method access requires explicit dereference")
reject(shared_local_escape "func bad()->&i32 { var list=sample(); for(var &x=list) { return x; } return &list.values[0]; } func main()->void {}" "local|outlive|escape")
reject(factory_local_escape "func bad<'a>()->RefIterator<'a,i32> { var list=sample(); return list.iterRef(); } func main()->void {}" "local|outlive|borrow")
reject(default_mutable_escape "var globalItem:i32=0; struct GlobalSource { func iter()->GlobalIterator { return GlobalIterator{}; } } struct GlobalIterator { func next()->stdlib.Option<&mut i32> { return stdlib.Option<&mut i32>.Some(&mut globalItem); } } func main()->void { var source=GlobalSource{}; var outside:i32=0; var escaped=&mut outside; for(var x=source) { escaped=x; break; } }" "cannot escape its iteration")
