cmake_minimum_required(VERSION 3.21)
set(work "${OUTPUT_DIR}/manifest_commands")
file(MAKE_DIRECTORY "${work}")
function(source path text)
    get_filename_component(parent "${work}/${path}" DIRECTORY)
    file(MAKE_DIRECTORY "${parent}")
    file(WRITE "${work}/${path}" "${text}")
endfunction()
function(command action)
    execute_process(COMMAND "${COMPILER}" manifest "${action}" ${ARGN}
        WORKING_DIRECTORY "${work}/cmd/compiler"
        RESULT_VARIABLE result ERROR_VARIABLE errors OUTPUT_VARIABLE output TIMEOUT 20)
    if(NOT result STREQUAL "0")
        message(FATAL_ERROR "manifest ${action}: ${errors}")
    endif()
endfunction()
function(expect text)
    file(READ "${work}/dmm.manifest" actual)
    if(NOT actual STREQUAL text)
        message(FATAL_ERROR "Unexpected manifest:\n${actual}\nExpected:\n${text}")
    endif()
endfunction()
function(reject code)
    file(SHA256 "${work}/dmm.manifest" before)
    execute_process(COMMAND "${COMPILER}" --formatError manifest sync "${work}" ${ARGN}
        RESULT_VARIABLE result ERROR_VARIABLE errors TIMEOUT 20)
    file(SHA256 "${work}/dmm.manifest" after)
    if(NOT result STREQUAL "1" OR NOT before STREQUAL after)
        message(FATAL_ERROR "Failed update changed manifest or returned ${result}: ${errors}")
    endif()
    string(JSON count LENGTH "${errors}" errors)
    if(NOT errors MATCHES "${code}")
        message(FATAL_ERROR "Expected ${code}: ${errors}")
    endif()
endfunction()
source("dmm.manifest" "module example.com/project\ndmm 0.3\nrequire (\nexample.com/a v1.0.0\nexample.com/b v2.0.0\nexample.com/d v4.0.0 // indirect\nexample.com/stale v1.0.0 // indirect\nexample.com/unused v9.0.0\n)\n")
source("cmd/compiler/main.dmm" "package main; import \"example.com/a\"; func main() -> int { return a.answer(); }")
source("cmd/formatter/main.dmm" "package main; import \"example.com/d\"; func main() -> int { return d.answer(); }")
source("library/lib.dmm" "package library; pub func answer() -> int { return 7; }")
source("nested/dmm.manifest" "module invalid\ndmm 9.0\n")
source("nested/broken.dmm" "this nested module must not be scanned")
source("vendor/example.com/a/dmm.manifest" "module example.com/a\ndmm 0.3\nrequire example.com/b v2.0.0\n")
source("vendor/example.com/a/a.dmm" "package a; import \"example.com/b\"; pub func answer() -> int { return b.answer(); }")
source("vendor/example.com/b/dmm.manifest" "module example.com/b\ndmm 0.3\nrequire example.com/c v3.0.0\n")
source("vendor/example.com/b/b.dmm" "package b; import \"example.com/c\"; pub func answer() -> int { return c.answer(); }")
source("vendor/example.com/c/dmm.manifest" "module example.com/c\ndmm 0.3\n")
source("vendor/example.com/c/c.dmm" "package c; pub func answer() -> int { return 7; }")
source("vendor/example.com/d/dmm.manifest" "module example.com/d\ndmm 0.3\n")
source("vendor/example.com/d/d.dmm" "package d; pub func answer() -> int { return 7; }")
source("vendor/unrelated/broken.dmm" "unimported vendor sources must not be scanned")
command(sync)
set(updated "module example.com/project\n\ndmm 0.3\n\nrequire (\n    example.com/a v1.0.0\n    example.com/b v2.0.0 // indirect\n    example.com/c v3.0.0 // indirect\n    example.com/d v4.0.0\n)\n")
expect("${updated}")
command(sync "${work}")
expect("${updated}")
command(sync)
set(cleaned "module example.com/project\n\ndmm 0.3\n\nrequire (\n    example.com/a v1.0.0\n    example.com/b v2.0.0 // indirect\n    example.com/c v3.0.0 // indirect\n    example.com/d v4.0.0\n)\n")
expect("${cleaned}")
execute_process(COMMAND "${COMPILER}" -c "${work}/cmd/compiler" -o "${work}/program.obj"
    RESULT_VARIABLE result ERROR_VARIABLE errors TIMEOUT 20)
if(NOT result STREQUAL "0")
    message(FATAL_ERROR "Updated manifest cannot build: ${errors}")
endif()
# A directly imported module must have an explicit version, not an invented one.
source("cmd/formatter/main.dmm" "package main; import \"example.com/missing\"; func main() -> int { return 0; }")
reject(S129)
source("cmd/formatter/main.dmm" "package main; import \"example.com/d\"; func main() -> int { return d.answer(); }")
# An existing exact requirement and a conflicting transitive version cannot resolve silently.
source("vendor/example.com/a/dmm.manifest" "module example.com/a\ndmm 0.3\nrequire example.com/b v8.0.0\n")
reject(S129)
source("vendor/example.com/a/dmm.manifest" "module example.com/a\ndmm 0.3\nrequire example.com/b v2.0.0\n")
source("dmm.manifest.tmp" "user content")
reject(S122)
file(READ "${work}/dmm.manifest.tmp" preserved)
if(NOT preserved STREQUAL "user content")
    message(FATAL_ERROR "Manifest command overwrote an existing temporary file")
endif()
file(REMOVE "${work}/dmm.manifest.tmp")
reject(C102 unexpected)
# With no remaining external imports, clean removes the require block entirely.
source("cmd/compiler/main.dmm" "package main; func main() -> int { return 0; }")
source("cmd/formatter/main.dmm" "package main; func main() -> int { return 0; }")
command(sync)
expect("module example.com/project\n\ndmm 0.3\n")
