cmake_minimum_required(VERSION 3.21)
file(MAKE_DIRECTORY "${OUTPUT_DIR}")
set(source "${OUTPUT_DIR}/root.dmm")
set(library "${OUTPUT_DIR}/library.dmm")
file(WRITE "${library}" "func answer() -> int { return 7; }")
file(WRITE "${source}" "import \"library.dmm\"\nfunc main() -> int { return answer(); }")
foreach(mode obj exe)
    foreach(target elf coff)
        foreach(protected "${source}" "${library}")
            file(SHA256 "${protected}" before)
            execute_process(COMMAND "${COMPILER}" "--emit=${mode}" "--target=${target}" "${source}" -o "${protected}"
                RESULT_VARIABLE result ERROR_VARIABLE errors)
            file(SHA256 "${protected}" after)
            if(result STREQUAL "0" OR NOT before STREQUAL after)
                message(FATAL_ERROR "Native output overwrote loaded source ${protected}")
            endif()
        endforeach()
        file(CREATE_LINK "${library}" "${OUTPUT_DIR}/alias_${mode}_${target}" RESULT link_result)
        if(link_result STREQUAL "0")
            file(SHA256 "${library}" before)
            execute_process(COMMAND "${COMPILER}" "--emit=${mode}" "--target=${target}" "${source}"
                -o "${OUTPUT_DIR}/alias_${mode}_${target}" RESULT_VARIABLE result ERROR_VARIABLE errors)
            file(SHA256 "${library}" after)
            if(result STREQUAL "0" OR NOT before STREQUAL after)
                message(FATAL_ERROR "Native output overwrote hard-linked source")
            endif()
        endif()
        set(artifact "${OUTPUT_DIR}/${mode}_${target}")
        set(map "${artifact}.map")
        execute_process(COMMAND "${COMPILER}" "--emit=${mode}" "--target=${target}" --source-map "${map}"
            --dump-ir "${artifact}.ir" --dump-ast "${artifact}.ast" "${source}" -o "${artifact}"
            RESULT_VARIABLE result ERROR_VARIABLE errors)
        if(NOT result STREQUAL "0")
            message(FATAL_ERROR "Native CLI compilation failed: ${errors}")
        endif()
        file(READ "${map}" contents)
        if(NOT contents MATCHES "^dmm-native-map-v1" OR NOT contents MATCHES "text-offset [0-9]+ instruction [0-9]+ function=\"main\".*span=2:")
            message(FATAL_ERROR "Native map lacks offsets and source spans")
        endif()
        file(SHA256 "${artifact}" before)
        execute_process(COMMAND "${COMPILER}" "--emit=${mode}" "--target=${target}" --source-map "${artifact}"
            "${source}" -o "${artifact}" RESULT_VARIABLE result ERROR_VARIABLE errors)
        file(SHA256 "${artifact}" after)
        if(result STREQUAL "0" OR NOT before STREQUAL after)
            message(FATAL_ERROR "Native artifact alias was not rejected")
        endif()
        execute_process(COMMAND "${COMPILER}" "--emit=${mode}" "--target=${target}" "${source}"
            RESULT_VARIABLE result ERROR_VARIABLE errors)
        if(mode STREQUAL "obj")
            if(target STREQUAL "elf")
                set(suffix .o)
            else()
                set(suffix .obj)
            endif()
        else()
            if(target STREQUAL "elf")
                set(suffix .out)
            else()
                set(suffix .exe)
            endif()
        endif()
        if(NOT result STREQUAL "0" OR NOT EXISTS "${source}${suffix}")
            message(FATAL_ERROR "Native default suffix failed: ${mode}/${target}")
        endif()
    endforeach()
endforeach()
# A default artifact suffix may itself be a loaded source unit.
foreach(suffix .o .obj .out .exe)
    set(imported "${OUTPUT_DIR}/suffix_root.dmm${suffix}")
    file(WRITE "${imported}" "func answer() -> int { return 7; }")
    file(WRITE "${OUTPUT_DIR}/suffix_root.dmm" "import \"suffix_root.dmm${suffix}\"\nfunc main() -> int { return answer(); }")
    if(suffix STREQUAL ".o" OR suffix STREQUAL ".out")
        set(target elf)
    else()
        set(target coff)
    endif()
    if(suffix STREQUAL ".o" OR suffix STREQUAL ".obj")
        set(mode obj)
    else()
        set(mode exe)
    endif()
    file(SHA256 "${imported}" before)
    execute_process(COMMAND "${COMPILER}" "--emit=${mode}" "--target=${target}" "${OUTPUT_DIR}/suffix_root.dmm"
        RESULT_VARIABLE result ERROR_VARIABLE errors)
    file(SHA256 "${imported}" after)
    if(result STREQUAL "0" OR NOT before STREQUAL after)
        message(FATAL_ERROR "Native default cleanup damaged an imported artifact-suffix source")
    endif()
endforeach()
if(WIN32)
    set(program "${source}.exe")
else()
    set(program "${source}.out")
endif()
execute_process(COMMAND "${program}" RESULT_VARIABLE result ERROR_VARIABLE errors)
if(NOT result STREQUAL "7")
    message(FATAL_ERROR "Native startup did not propagate main return: ${result} ${errors}")
endif()
execute_process(COMMAND "${COMPILER}" --emit=invalid "${source}" RESULT_VARIABLE result ERROR_VARIABLE errors)
if(result STREQUAL "0" OR NOT errors MATCHES "Invalid emission mode")
    message(FATAL_ERROR "Invalid --emit was accepted")
endif()
