include("${CMAKE_CURRENT_LIST_DIR}/source_fixture.cmake")
cmake_minimum_required(VERSION 3.21)
include("${CMAKE_CURRENT_LIST_DIR}/standalone_link.cmake")
get_filename_component(ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
file(MAKE_DIRECTORY "${OUTPUT_DIR}")
if (WIN32)
    set(host coff)
else ()
    set(host elf)
endif ()
file(GLOB_RECURSE sources "${ROOT}/tests/execution/*.dmm" "${ROOT}/tests/regression/*.dmm")
foreach (source IN LISTS sources)
        file(READ "${source}" package_source)
        if(NOT package_source MATCHES "^[ \t\r\n]*package[ \t]+main[ \t]*;" OR
           NOT package_source MATCHES "func[ \t]+main[ \t]*[(]")
            continue()
        endif()
    get_filename_component(name "${source}" NAME_WE)
    get_filename_component(directory "${source}" DIRECTORY)
    set(expected_file "${directory}/${name}.expected")
    if (NOT EXISTS "${expected_file}")
        set(expected_file "${ROOT}/tests/expected/${name}.expected")
    endif ()
    file(READ "${expected_file}" expected)
    string(REPLACE "\r\n" "\n" expected "${expected}")
    string(REGEX REPLACE "\n+$" "" expected "${expected}")
    foreach (mode exe obj)
        set(work "${OUTPUT_DIR}/${name}_${mode}")
        file(MAKE_DIRECTORY "${work}")
        foreach (syntax intel att)
            set(artifact "${work}/${syntax}.native")
            execute_process(COMMAND "${COMPILER}" "--emit=${mode}" --dump-native-link "${work}/native.link" "--syntax=${syntax}" --deterministic
                    "${source}" -o "${artifact}" RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE errors TIMEOUT 30)
            if (NOT result STREQUAL "0")
                message(FATAL_ERROR "${name}/${mode}/${syntax}: ${output}${errors}")
            endif ()
        endforeach ()
        file(SHA256 "${work}/intel.native" intel)
        file(SHA256 "${work}/att.native" att)
        if (NOT intel STREQUAL att)
            message(FATAL_ERROR "Native output depends on assembly syntax: ${name}/${mode}")
        endif ()
        set(program "${work}/program.exe")
        if (mode STREQUAL "obj")
            # The compiler emits this object directly; external linking tests interoperability.
            dmm_test_link_profile("${work}/native.link")
            execute_process(COMMAND "${ASSEMBLER}" ${CASE_LINK_FLAGS} "${work}/intel.native"
                    ${CASE_SYSTEM_LIBRARIES} -o "${program}" RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE errors TIMEOUT 30)
            if (NOT result STREQUAL "0")
                message(FATAL_ERROR "Object link failed ${name}: ${output}${errors}")
            endif ()
        else ()
            file(COPY_FILE "${work}/intel.native" "${program}")
            if (NOT WIN32)
                file(CHMOD "${program}" PERMISSIONS OWNER_READ OWNER_WRITE OWNER_EXECUTE GROUP_READ GROUP_EXECUTE WORLD_READ WORLD_EXECUTE)
            endif ()
        endif ()
        if (name STREQUAL "hello" AND CASE_STANDALONE)
            check_standalone_dependencies("${program}")
        endif ()
        execute_process(COMMAND "${program}" WORKING_DIRECTORY "${work}" RESULT_VARIABLE result
                OUTPUT_VARIABLE actual ERROR_VARIABLE errors TIMEOUT 10)
        dmm_test_write("${work}/actual.out" "${actual}")
        string(REPLACE "\r\n" "\n" actual "${actual}")
        string(REGEX REPLACE "\n+$" "" actual "${actual}")
        if (NOT result STREQUAL "0" OR NOT actual STREQUAL expected OR NOT errors STREQUAL "")
            message(FATAL_ERROR "${name}/${mode}: execution failed ${result}, see ${work}/actual.out\n${errors}")
        endif ()
        message(STATUS "PASS ${name}/${mode}")
    endforeach ()
    foreach (target elf coff)
        foreach (mode obj asm)
            execute_process(COMMAND "${COMPILER}" "--emit=${mode}" "--target=${target}" "${source}"
                    -o "${OUTPUT_DIR}/cross_${name}_${target}_${mode}" RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE errors TIMEOUT 30)
            if (NOT result STREQUAL "0")
                message(FATAL_ERROR "Cross emission ${name}/${target}/${mode}: ${output}${errors}")
            endif ()
        endforeach ()
    endforeach ()
endforeach ()

# Unbounded decimal input consumes every digit and saturates on overflow.
dmm_test_write("${OUTPUT_DIR}/integers/integers.dmm" "import <stdlib>\nfunc main() -> void {
    println(scanfInt()); println(scanfInt()); println(scanfInt()); println(scanfChar());
}")
string(REPEAT "0" 100 zeros)
dmm_test_write("${OUTPUT_DIR}/integers.txt" "${zeros}42 922337203685477580800 -922337203685477580900Z")
execute_process(COMMAND "${COMPILER}" --emit=exe "${OUTPUT_DIR}/integers/integers.dmm" -o "${OUTPUT_DIR}/integers.exe"
        RESULT_VARIABLE result ERROR_VARIABLE errors)
if (NOT result STREQUAL "0")
    message(FATAL_ERROR "Integer input compilation failed: ${errors}")
endif ()
execute_process(COMMAND "${OUTPUT_DIR}/integers.exe" INPUT_FILE "${OUTPUT_DIR}/integers.txt"
        RESULT_VARIABLE result OUTPUT_VARIABLE actual ERROR_VARIABLE errors TIMEOUT 10)
string(REPLACE "\r\n" "\n" actual "${actual}")
# The runtime's saturated int64 result is narrowed to the language's int32.
if (NOT result STREQUAL "0" OR NOT actual STREQUAL "42\n-1\n0\nZ\n")
    message(FATAL_ERROR "Standalone integer input failed: ${actual} ${errors}")
endif ()

# Independent C callers validate native object ABI boundaries.
file(READ "${ROOT}/tests/abi/systemv/core_abi/core_abi.dmm" abi_source)
dmm_test_write("${OUTPUT_DIR}/abi/abi.dmm" "${abi_source}")
execute_process(COMMAND "${COMPILER}" --emit=obj "${OUTPUT_DIR}/abi/abi.dmm" -o "${OUTPUT_DIR}/abi.obj"
        RESULT_VARIABLE result ERROR_VARIABLE errors)
if (NOT result STREQUAL "0")
    message(FATAL_ERROR "Native ABI compilation failed: ${errors}")
endif ()
get_filename_component(tool_directory "${ASSEMBLER}" DIRECTORY)
find_program(OBJCOPY NAMES objcopy HINTS "${tool_directory}" REQUIRED)
execute_process(COMMAND "${OBJCOPY}" --redefine-sym main=dmm_test_entry "${OUTPUT_DIR}/abi.obj"
        RESULT_VARIABLE result ERROR_VARIABLE errors)
if (NOT result STREQUAL "0")
    message(FATAL_ERROR "Native ABI symbol rename failed: ${errors}")
endif ()
dmm_test_abi_definitions("${OUTPUT_DIR}/abi.obj" abi_definitions)
execute_process(COMMAND "${ASSEMBLER}" ${SANITIZER_FLAGS} ${abi_definitions} -no-pie "${OUTPUT_DIR}/abi.obj"
        "${ROOT}/tests/abi/c_interop/abi_driver.c" ${SYSTEM_LIBRARIES} -o "${OUTPUT_DIR}/abi.exe"
        RESULT_VARIABLE result ERROR_VARIABLE errors)
if (NOT result STREQUAL "0")
    message(FATAL_ERROR "Native ABI link failed: ${errors}")
endif ()
execute_process(COMMAND "${OUTPUT_DIR}/abi.exe" RESULT_VARIABLE result ERROR_VARIABLE errors)
if (NOT result STREQUAL "0")
    message(FATAL_ERROR "Native ABI execution failed: ${result} ${errors}")
endif ()

# Scalar input, EOF defaults and bounded integer formatting in the embedded runtime.
dmm_test_write("${OUTPUT_DIR}/runtime/runtime.dmm" "import <stdlib>\nfunc main() -> void {
    println(scanfInt()); println(scanfChar()); println(scanfString());
    var buffer:char[3]; println(io_int_to_str(1234, buffer, 3));
    println(buffer[0]); println(buffer[1]); println(buffer[2] == 0);
    println(io_str_to_int(\"-42\")); println(sys_close(-1) < 0);
    println(sys_open(\"missing_directory/file\", 0, 0) < 0);
}")
dmm_test_write("${OUTPUT_DIR}/stdin.txt" "42Zhello")
dmm_test_write("${OUTPUT_DIR}/empty.txt" "")
execute_process(COMMAND "${COMPILER}" --emit=exe "${OUTPUT_DIR}/runtime/runtime.dmm" -o "${OUTPUT_DIR}/runtime.exe"
        RESULT_VARIABLE result ERROR_VARIABLE errors)
if (NOT result STREQUAL "0")
    message(FATAL_ERROR "Native runtime compilation failed: ${errors}")
endif ()
foreach (input stdin empty)
    execute_process(COMMAND "${OUTPUT_DIR}/runtime.exe" WORKING_DIRECTORY "${OUTPUT_DIR}"
            INPUT_FILE "${OUTPUT_DIR}/${input}.txt" RESULT_VARIABLE result OUTPUT_VARIABLE actual ERROR_VARIABLE errors)
    string(REPLACE "\r\n" "\n" actual "${actual}")
    if (input STREQUAL "stdin")
        set(expected "42\nZ\nhello\n2\n1\n2\n1\n-42\n1\n1\n")
    else ()
        set(expected "0\n\n\n2\n1\n2\n1\n-42\n1\n1\n")
        # scanfChar at EOF yields a NUL, which CMake omits in captured text.
    endif ()
    if (NOT result STREQUAL "0" OR NOT actual STREQUAL expected)
        message(FATAL_ERROR "Embedded runtime/${input}: ${result}\nExpected: ${expected}\nActual: ${actual}\n${errors}")
    endif ()
endforeach ()
