cmake_minimum_required(VERSION 3.21)
get_filename_component(ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
file(MAKE_DIRECTORY "${OUTPUT_DIR}")
set(source "${OUTPUT_DIR}/root.dmm")
set(library "${OUTPUT_DIR}/library.dmm")
file(WRITE "${library}" "func answer() -> int { return 7; }")
file(WRITE "${source}" "import \"library.dmm\"\nfunc main() -> int { return answer(); }")

# Omitting --emit selects an executable, independent of target or -o suffix.
file(WRITE "${source}.s" "preserve-unselected-assembly")
foreach(target elf coff)
    if(target STREQUAL "elf")
        set(suffix ".out")
        set(magic "7f454c46")
    else()
        set(suffix ".exe")
        set(magic "4d5a")
    endif()
    execute_process(COMMAND "${COMPILER}" "--target=${target}" "${source}"
        RESULT_VARIABLE result ERROR_VARIABLE errors)
    if(NOT result EQUAL 0 OR NOT EXISTS "${source}${suffix}")
        message(FATAL_ERROR "Default executable output failed: ${target} ${errors}")
    endif()
    file(READ "${source}${suffix}" header LIMIT 4 HEX)
    if(NOT header MATCHES "^${magic}")
        message(FATAL_ERROR "Default output is not an executable: ${target}")
    endif()
    set(named "${OUTPUT_DIR}/default_${target}.bin")
    execute_process(COMMAND "${COMPILER}" "--target=${target}" "${source}" -o "${named}"
        RESULT_VARIABLE result ERROR_VARIABLE errors)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "Default -o failed: ${errors}")
    endif()
    file(SHA256 "${source}${suffix}" implicit)
    file(SHA256 "${named}" explicit)
    if(NOT implicit STREQUAL explicit)
        message(FATAL_ERROR "-o changed the default emission mode")
    endif()
    foreach(flag -c -S)
        if(flag STREQUAL "-c")
            set(mode obj)
        else()
            set(mode asm)
        endif()
        execute_process(COMMAND "${COMPILER}" "${flag}" "--target=${target}" --deterministic
            "${source}" -o "${OUTPUT_DIR}/short_${target}_${mode}"
            RESULT_VARIABLE short_result ERROR_VARIABLE errors)
        execute_process(COMMAND "${COMPILER}" "--emit=${mode}" "--target=${target}" --deterministic
            "${source}" -o "${OUTPUT_DIR}/long_${target}_${mode}"
            RESULT_VARIABLE long_result ERROR_VARIABLE errors)
        if(NOT short_result EQUAL 0 OR NOT long_result EQUAL 0)
            message(FATAL_ERROR "Emission alias failed: ${flag} ${errors}")
        endif()
        file(SHA256 "${OUTPUT_DIR}/short_${target}_${mode}" short_hash)
        file(SHA256 "${OUTPUT_DIR}/long_${target}_${mode}" long_hash)
        if(NOT short_hash STREQUAL long_hash)
            message(FATAL_ERROR "Emission alias differs from --emit: ${flag}")
        endif()
    endforeach()
endforeach()
file(READ "${source}.s" preserved)
if(NOT preserved STREQUAL "preserve-unselected-assembly")
    message(FATAL_ERROR "Native default touched unselected assembly output")
endif()
execute_process(COMMAND "${COMPILER}" --help OUTPUT_VARIABLE help RESULT_VARIABLE result)
if(NOT result EQUAL 0 OR NOT help MATCHES "exe [(]default[)]" OR NOT help MATCHES "-c" OR NOT help MATCHES "-S")
    message(FATAL_ERROR "Help does not describe the native default and emission aliases")
endif()
foreach(mode obj exe)
    foreach(target elf coff)
        foreach(protected "${source}" "${library}")
            file(SHA256 "${protected}" before)
            execute_process(COMMAND "${COMPILER}" "--emit=${mode}" "--target=${target}" "${source}" -o "${protected}"
                RESULT_VARIABLE result ERROR_VARIABLE errors)
            file(SHA256 "${protected}" after)
            if(result STREQUAL "0" OR NOT before STREQUAL after)
                message(FATAL_ERROR "Native output overwrote loaded source ${protected}")
            endif()
        endforeach()
        file(CREATE_LINK "${library}" "${OUTPUT_DIR}/alias_${mode}_${target}" RESULT link_result)
        if(link_result STREQUAL "0")
            file(SHA256 "${library}" before)
            execute_process(COMMAND "${COMPILER}" "--emit=${mode}" "--target=${target}" "${source}"
                -o "${OUTPUT_DIR}/alias_${mode}_${target}" RESULT_VARIABLE result ERROR_VARIABLE errors)
            file(SHA256 "${library}" after)
            if(result STREQUAL "0" OR NOT before STREQUAL after)
                message(FATAL_ERROR "Native output overwrote hard-linked source")
            endif()
        endif()
        set(artifact "${OUTPUT_DIR}/${mode}_${target}")
        set(map "${artifact}.map")
        execute_process(COMMAND "${COMPILER}" "--emit=${mode}" "--target=${target}" --source-map "${map}"
            --dump-ir "${artifact}.ir" --dump-ast "${artifact}.ast" "${source}" -o "${artifact}"
            RESULT_VARIABLE result ERROR_VARIABLE errors)
        if(NOT result STREQUAL "0")
            message(FATAL_ERROR "Native CLI compilation failed: ${errors}")
        endif()
        file(READ "${map}" contents)
        if(NOT contents MATCHES "^dmm-native-map-v1" OR NOT contents MATCHES "text-offset [0-9]+ instruction [0-9]+ function=\"main\".*span=2:")
            message(FATAL_ERROR "Native map lacks offsets and source spans")
        endif()
        file(SHA256 "${artifact}" before)
        execute_process(COMMAND "${COMPILER}" "--emit=${mode}" "--target=${target}" --source-map "${artifact}"
            "${source}" -o "${artifact}" RESULT_VARIABLE result ERROR_VARIABLE errors)
        file(SHA256 "${artifact}" after)
        if(result STREQUAL "0" OR NOT before STREQUAL after)
            message(FATAL_ERROR "Native artifact alias was not rejected")
        endif()
        execute_process(COMMAND "${COMPILER}" "--emit=${mode}" "--target=${target}" "${source}"
            RESULT_VARIABLE result ERROR_VARIABLE errors)
        if(mode STREQUAL "obj")
            if(target STREQUAL "elf")
                set(suffix .o)
            else()
                set(suffix .obj)
            endif()
        else()
            if(target STREQUAL "elf")
                set(suffix .out)
            else()
                set(suffix .exe)
            endif()
        endif()
        if(NOT result STREQUAL "0" OR NOT EXISTS "${source}${suffix}")
            message(FATAL_ERROR "Native default suffix failed: ${mode}/${target}")
        endif()
    endforeach()
endforeach()
# A default artifact suffix may itself be a loaded source unit.
foreach(suffix .o .obj .out .exe)
    set(imported "${OUTPUT_DIR}/suffix_root.dmm${suffix}")
    file(WRITE "${imported}" "func answer() -> int { return 7; }")
    file(WRITE "${OUTPUT_DIR}/suffix_root.dmm" "import \"suffix_root.dmm${suffix}\"\nfunc main() -> int { return answer(); }")
    if(suffix STREQUAL ".o" OR suffix STREQUAL ".out")
        set(target elf)
    else()
        set(target coff)
    endif()
    if(suffix STREQUAL ".o" OR suffix STREQUAL ".obj")
        set(mode obj)
    else()
        set(mode exe)
    endif()
    file(SHA256 "${imported}" before)
    execute_process(COMMAND "${COMPILER}" "--emit=${mode}" "--target=${target}" "${OUTPUT_DIR}/suffix_root.dmm"
        RESULT_VARIABLE result ERROR_VARIABLE errors)
    file(SHA256 "${imported}" after)
    if(result STREQUAL "0" OR NOT before STREQUAL after)
        message(FATAL_ERROR "Native default cleanup damaged an imported artifact-suffix source")
    endif()
endforeach()
if(WIN32)
    set(program "${source}.exe")
else()
    set(program "${source}.out")
endif()
execute_process(COMMAND "${program}" RESULT_VARIABLE result ERROR_VARIABLE errors)
if(NOT result STREQUAL "7")
    message(FATAL_ERROR "Native startup did not propagate main return: ${result} ${errors}")
endif()
execute_process(COMMAND "${COMPILER}" --emit=invalid "${source}" RESULT_VARIABLE result ERROR_VARIABLE errors)
if(result STREQUAL "0" OR NOT errors MATCHES "Invalid emission mode")
    message(FATAL_ERROR "Invalid --emit was accepted")
endif()

# Check Linux collision protection even when this suite runs on Windows.
foreach(target elf coff)
    set(assembly "${OUTPUT_DIR}/collision_${target}.s")
    execute_process(COMMAND "${COMPILER}" --emit=asm "--target=${target}"
        "${ROOT}/tests/execution/functions/runtime_name_collision.dmm" -o "${assembly}"
        RESULT_VARIABLE result ERROR_VARIABLE errors)
    if(NOT result STREQUAL "0")
        message(FATAL_ERROR "Collision cross-emission failed: ${errors}")
    endif()
    file(READ "${assembly}" contents)
    foreach(name write open close exit __errno_location)
        string(LENGTH "${name}" length)
        string(FIND "${contents}" ".globl ${name}\n" unsafe)
        string(FIND "${contents}" ".globl __dmm_f${length}_${name}__" mangled)
        if(NOT unsafe EQUAL -1 OR mangled EQUAL -1)
            message(FATAL_ERROR "${target}: source symbol ${name} can intercept runtime calls")
        endif()
    endforeach()
endforeach()
