cmake_minimum_required(VERSION 3.21)
file(MAKE_DIRECTORY "${OUTPUT_DIR}/libraries with spaces")
foreach(case platform used bad unused address)
    file(MAKE_DIRECTORY "${OUTPUT_DIR}/${case}")
endforeach()
file(WRITE "${OUTPUT_DIR}/dmm.manifest" "module ffi.test/link\ndmm 2026-09-22-dev\n")
if(WIN32)
    set(host coff)
    set(platform_library kernel32)
    set(platform_declaration "func nativePid() -> u32 = \"GetCurrentProcessId\";")
else()
    set(host elf)
    set(platform_library c)
    set(platform_declaration "func nativePid() -> i32 = \"getpid\";")
endif()
file(WRITE "${OUTPUT_DIR}/platform/main.dmm"
    "package main; extern \"system\" from \"${platform_library}\" { ${platform_declaration} }\nfunc main() -> int { if (nativePid() > 0) { return 0; } return 1; }")
execute_process(COMMAND "${COMPILER}" --linker-driver "${C_DRIVER}" "${OUTPUT_DIR}/platform/main.dmm"
    -o "${OUTPUT_DIR}/platform.exe" RESULT_VARIABLE result ERROR_VARIABLE diagnostics TIMEOUT 30)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "Real platform function linking failed: ${diagnostics}")
endif()
execute_process(COMMAND "${OUTPUT_DIR}/platform.exe" RESULT_VARIABLE result TIMEOUT 10)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "Real platform function call failed: ${result}")
endif()
file(WRITE "${OUTPUT_DIR}/ref.c" "int ffi_link_value(void) { return 42; }\n")
execute_process(COMMAND "${C_DRIVER}" -c "${OUTPUT_DIR}/ref.c" -o "${OUTPUT_DIR}/ref.o"
    RESULT_VARIABLE result ERROR_VARIABLE diagnostics TIMEOUT 30)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "Link reference compilation failed: ${diagnostics}")
endif()
get_filename_component(driver_dir "${C_DRIVER}" DIRECTORY)
find_program(AR_DRIVER NAMES ar llvm-ar HINTS "${driver_dir}" REQUIRED)
execute_process(COMMAND "${AR_DRIVER}" rcs "${OUTPUT_DIR}/libraries with spaces/libffi_link.a" "${OUTPUT_DIR}/ref.o"
    RESULT_VARIABLE result ERROR_VARIABLE diagnostics TIMEOUT 30)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "Link reference archive failed: ${diagnostics}")
endif()
file(WRITE "${OUTPUT_DIR}/used/main.dmm" "package main; extern \"system\" from \"ffi_link\" { func value() -> i32 = \"ffi_link_value\"; }\nfunc main() -> int { return (value()-42).(int); }")
execute_process(COMMAND "${COMPILER}" --native-library-dir "${OUTPUT_DIR}/libraries with spaces"
    --native-library-dir "${OUTPUT_DIR}" --linker-driver "${C_DRIVER}"
    "${OUTPUT_DIR}/used/main.dmm" -o "${OUTPUT_DIR}/used.exe"
    RESULT_VARIABLE result ERROR_VARIABLE diagnostics TIMEOUT 30)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "Logical library search failed: ${diagnostics}")
endif()
execute_process(COMMAND "${OUTPUT_DIR}/used.exe" RESULT_VARIABLE result TIMEOUT 10)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "Archive call failed: ${result}")
endif()
file(WRITE "${OUTPUT_DIR}/address/main.dmm" "package main; extern \"system\" from \"ffi_link\" { func value() -> i32 = \"ffi_link_value\"; } var address:extern \"system\" func() -> i32=value; func main() -> int { return (address()-42).(int); }")
execute_process(COMMAND "${COMPILER}" --native-library-dir "${OUTPUT_DIR}/libraries with spaces"
    --linker-driver "${C_DRIVER}" --dump-native-link "${OUTPUT_DIR}/address.link"
    "${OUTPUT_DIR}/address/main.dmm" -o "${OUTPUT_DIR}/address.exe"
    RESULT_VARIABLE result ERROR_VARIABLE diagnostics TIMEOUT 30)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "Native global function-address linking failed: ${diagnostics}")
endif()
execute_process(COMMAND "${OUTPUT_DIR}/address.exe" RESULT_VARIABLE result TIMEOUT 10)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "Native global function-address call failed: ${result}")
endif()
file(SHA256 "${OUTPUT_DIR}/used.exe" original)
foreach(mode missing_library missing_override missing_symbol internal)
    set(options --linker-driver "${C_DRIVER}")
    set(source "${OUTPUT_DIR}/used/main.dmm")
    if(mode STREQUAL missing_override)
        list(APPEND options --native-library "ffi_link=${OUTPUT_DIR}/nonexistent.a")
    elseif(mode STREQUAL missing_symbol)
        file(WRITE "${OUTPUT_DIR}/bad/main.dmm" "package main; extern \"system\" from \"ffi_link\" { func bad() -> i32 = \"ffi_missing_symbol\"; } func main() -> int { return bad().(int); }")
        set(source "${OUTPUT_DIR}/bad/main.dmm")
        list(APPEND options --native-library-dir "${OUTPUT_DIR}/libraries with spaces")
    elseif(mode STREQUAL internal)
        set(options --link=internal)
    endif()
    execute_process(COMMAND "${COMPILER}" ${options} "${source}" -o "${OUTPUT_DIR}/used.exe"
        RESULT_VARIABLE result ERROR_VARIABLE diagnostics TIMEOUT 30)
    if(result EQUAL 0 OR NOT diagnostics MATCHES "native imports|Native library|External linker")
        message(FATAL_ERROR "Expected concrete native link failure (${mode}): ${diagnostics}")
    endif()
    file(SHA256 "${OUTPUT_DIR}/used.exe" current)
    if(NOT current STREQUAL original)
        message(FATAL_ERROR "Native link failure replaced/deleted the existing output (${mode})")
    endif()
endforeach()
foreach(target elf coff)
    foreach(emission obj asm)
        execute_process(COMMAND "${COMPILER}" "--target=${target}" "--emit=${emission}"
            --dump-native-link "${OUTPUT_DIR}/${target}_${emission}.link"
            "${OUTPUT_DIR}/used/main.dmm" -o "${OUTPUT_DIR}/${target}.${emission}"
            RESULT_VARIABLE result ERROR_VARIABLE diagnostics TIMEOUT 30)
        if(NOT result EQUAL 0)
            message(FATAL_ERROR "Cross-target emission must not start linking (${target}/${emission}): ${diagnostics}")
        endif()
    endforeach()
endforeach()
file(WRITE "${OUTPUT_DIR}/unused/main.dmm" "package main; extern \"system\" from \"never_link_this\" { func unused() -> i32; } func main() -> int { return 0; }")
execute_process(COMMAND "${COMPILER}" --link=internal --dump-native-link "${OUTPUT_DIR}/unused.link"
    "${OUTPUT_DIR}/unused/main.dmm" -o "${OUTPUT_DIR}/unused.exe" RESULT_VARIABLE result ERROR_VARIABLE diagnostics TIMEOUT 30)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "Unused native imports must not force external linking: ${diagnostics}")
endif()
file(READ "${OUTPUT_DIR}/unused.link" link)
if(link MATCHES "never_link_this" OR NOT link MATCHES "runtime-profile=standalone")
    message(FATAL_ERROR "Unused imports changed native requirements: ${link}")
endif()
