cmake_minimum_required(VERSION 3.21)
if(WIN32)
    set(host coff)
    set(system_library -lws2_32)
    set(link_flag -Wl,--subsystem,console)
else()
    set(host elf)
    set(system_library -pthread)
    set(link_flag -no-pie)
endif()
set(work "${OUTPUT_DIR}/network")
file(MAKE_DIRECTORY "${work}")
foreach(case loopback lifecycle borrow_close borrow_buffer borrow_spawn)
    file(MAKE_DIRECTORY "${work}/${case}")
    file(WRITE "${work}/${case}/dmm.manifest" "module network.test/${case}\ndmm 2026-09-22-dev\nfeatures = [\"async\"]\n")
    configure_file("${CMAKE_CURRENT_LIST_DIR}/network/${case}.dmm" "${work}/${case}/main.dmm" COPYONLY)
endforeach()
foreach(level 0 1)
    execute_process(COMMAND "${COMPILER}" "${work}/lifecycle/main.dmm" "-O${level}" "--target=${host}" --linker-driver "${ASSEMBLER}" -o "${work}/lifecycle.exe" RESULT_VARIABLE status ERROR_VARIABLE errors)
    if(NOT status EQUAL 0)
        message(FATAL_ERROR "Network lifecycle compile: ${errors}")
    endif()
    execute_process(COMMAND "${work}/lifecycle.exe" RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE errors TIMEOUT 20)
    string(REPLACE "\r\n" "\n" output "${output}")
    if(NOT status EQUAL 17 OR NOT output STREQUAL "init\nmain\ntask\npackage\nclosed\n")
        message(FATAL_ERROR "Network lifecycle: ${status} ${output} ${errors}")
    endif()
endforeach()
foreach(case borrow_close borrow_buffer borrow_spawn)
    execute_process(COMMAND "${COMPILER}" "${work}/${case}/main.dmm" --emit=obj -o "${work}/${case}/rejected.o" RESULT_VARIABLE status ERROR_VARIABLE errors)
    if(status EQUAL 0 OR EXISTS "${work}/${case}/rejected.o")
        message(FATAL_ERROR "Unsafe ${case} was accepted: ${errors}")
    endif()
    if(NOT errors MATCHES "[Bb]orrow|Send Future")
        message(FATAL_ERROR "Unexpected ${case} rejection: ${errors}")
    endif()
endforeach()
foreach(level 0 1)
    foreach(emit obj asm)
        foreach(syntax intel att)
            set(artifact "${work}/loopback_${level}_${emit}_${syntax}")
            execute_process(COMMAND "${COMPILER}" "${work}/loopback/main.dmm" "-O${level}" "--target=${host}" "--emit=${emit}" "--syntax=${syntax}" -o "${artifact}.${emit}"
                RESULT_VARIABLE status ERROR_VARIABLE errors TIMEOUT 30)
            if(NOT status EQUAL 0)
                message(FATAL_ERROR "Network ${level}/${emit}/${syntax}: ${errors}")
            endif()
            if(emit STREQUAL asm)
                set(language -x assembler)
            else()
                set(language -x none)
            endif()
            execute_process(COMMAND "${ASSEMBLER}" ${language} "${artifact}.${emit}" -x none "${SHIM}" ${link_flag} ${system_library} -o "${artifact}.exe"
                RESULT_VARIABLE status ERROR_VARIABLE errors TIMEOUT 30)
            if(NOT status EQUAL 0)
                message(FATAL_ERROR "Network manual link: ${errors}")
            endif()
            execute_process(COMMAND "${artifact}.exe" RESULT_VARIABLE status ERROR_VARIABLE errors TIMEOUT 20)
            if(NOT status EQUAL 0)
                message(FATAL_ERROR "Network execution ${level}/${emit}/${syntax}: ${status} ${errors}")
            endif()
        endforeach()
    endforeach()
endforeach()
execute_process(COMMAND "${COMPILER}" "${work}/loopback/main.dmm" "--target=${host}" --link=internal -o "${work}/rejected.exe" RESULT_VARIABLE status ERROR_VARIABLE errors)
if(status EQUAL 0 OR EXISTS "${work}/rejected.exe")
    message(FATAL_ERROR "Internal network executable accepted: ${errors}")
endif()
execute_process(COMMAND "${COMPILER}" "${work}/loopback/main.dmm" "--target=${host}" --link=auto --linker-driver "${ASSEMBLER}" -o "${work}/automatic.exe" RESULT_VARIABLE status ERROR_VARIABLE errors TIMEOUT 30)
if(NOT status EQUAL 0)
    message(FATAL_ERROR "Automatic network profile failed: ${errors}")
endif()
execute_process(COMMAND "${work}/automatic.exe" RESULT_VARIABLE status TIMEOUT 20)
if(NOT status EQUAL 0)
    message(FATAL_ERROR "Automatic network execution failed: ${status}")
endif()
get_filename_component(shim_directory "${SHIM}" DIRECTORY)
file(COPY_FILE "${SHIM}" "${work}/network shim copy.o")
execute_process(COMMAND "${COMPILER}" "${work}/loopback/main.dmm" --linker-driver "${ASSEMBLER}"
    --runtime-shim "${work}/network shim copy.o" -o "${work}/network space.exe" RESULT_VARIABLE status ERROR_VARIABLE errors)
if(NOT status EQUAL 0)
    message(FATAL_ERROR "Network shim path with spaces: ${errors}")
endif()
execute_process(COMMAND "${work}/network space.exe" RESULT_VARIABLE status TIMEOUT 20)
if(NOT status EQUAL 0)
    message(FATAL_ERROR "Network override execution: ${status}")
endif()
foreach(bad_shim "${work}/missing.o" "${shim_directory}/platform-shim.o")
    file(WRITE "${work}/preserved.exe" "existing output")
    execute_process(COMMAND "${COMPILER}" "${work}/loopback/main.dmm" --linker-driver "${ASSEMBLER}"
        --runtime-shim "${bad_shim}" -o "${work}/preserved.exe" RESULT_VARIABLE status ERROR_VARIABLE errors)
    file(READ "${work}/preserved.exe" preserved)
    if(status EQUAL 0 OR NOT preserved STREQUAL "existing output")
        message(FATAL_ERROR "Failed network link replaced output: ${errors}")
    endif()
endforeach()
file(SHA256 "${SHIM}" shim_before)
execute_process(COMMAND "${COMPILER}" "${work}/loopback/main.dmm" --dump-ast "${SHIM}"
    --linker-driver "${ASSEMBLER}" -o "${work}/collision.exe" RESULT_VARIABLE status ERROR_VARIABLE errors)
file(SHA256 "${SHIM}" shim_after)
if(status EQUAL 0 OR NOT shim_before STREQUAL shim_after)
    message(FATAL_ERROR "Network shim collision was not protected: ${errors}")
endif()
file(MAKE_DIRECTORY "${work}/unused")
file(WRITE "${work}/unused/dmm.manifest" "module network.test/unused\ndmm 2026-09-22-dev\nfeatures = [\"async\"]\n")
file(WRITE "${work}/unused/main.dmm" "package main; import \"stdlib/core/net\"; func main()->int { return 0; }\n")
execute_process(COMMAND "${COMPILER}" "${work}/unused/main.dmm" --link=internal "--target=${host}" -o "${work}/unused.exe" RESULT_VARIABLE status ERROR_VARIABLE errors)
if(NOT status EQUAL 0)
    message(FATAL_ERROR "Unused network import changes standalone profile: ${errors}")
endif()
