cmake_minimum_required(VERSION 3.21)
set(work "${OUTPUT_DIR}/platform space")
file(MAKE_DIRECTORY "${work}")
file(REMOVE "${work}/lifecycle.dmm" "${work}/executor.dmm" "${work}/void.dmm" "${work}/exit.dmm")
foreach(fixture lifecycle executor void exit)
    file(MAKE_DIRECTORY "${work}/${fixture}")
    file(WRITE "${work}/${fixture}/dmm.manifest" "module platform.test/${fixture}\ndmm 2026-09-22-dev\nfeatures = [\"async\"]\n")
endforeach()
configure_file("${CMAKE_CURRENT_LIST_DIR}/platform/lifecycle.dmm" "${work}/lifecycle/main.dmm" COPYONLY)
configure_file("${CMAKE_CURRENT_LIST_DIR}/async/executor.dmm" "${work}/executor/main.dmm" COPYONLY)
file(WRITE "${work}/void/main.dmm" "package main; func main() -> void { return; }\n")
file(WRITE "${work}/exit/main.dmm" "package main; import \"stdlib/core\"; async func worker() -> int { core.core_exit(23); } async func join(handle:JoinHandle<int>) -> void { var result=handle.await(); match(result) { Ok(value) => return; Err(error) => return; } } func main() -> int { block_on(join(spawn(worker()))); return 1; }\n")
if(WIN32)
    set(host coff)
    set(other elf)
else()
    set(host elf)
    set(other coff)
endif()
function(compile_ok)
    execute_process(COMMAND "${COMPILER}" ${ARGV} RESULT_VARIABLE result ERROR_VARIABLE errors TIMEOUT 30)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "Platform compilation failed: ${ARGV}: ${result} ${errors}")
    endif()
endfunction()
function(run_ok image status expected)
    execute_process(COMMAND "${image}" RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE errors TIMEOUT 20)
    string(REPLACE "\r\n" "\n" output "${output}")
    if(NOT result STREQUAL "${status}" OR NOT output STREQUAL "${expected}")
        message(FATAL_ERROR "Platform execution failed: ${image}: ${result} [${output}] ${errors}")
    endif()
endfunction()
function(fail_match pattern)
    execute_process(COMMAND "${COMPILER}" ${ARGN} RESULT_VARIABLE result ERROR_VARIABLE errors OUTPUT_VARIABLE output TIMEOUT 30)
    if(result EQUAL 0 OR NOT "${errors}${output}" MATCHES "${pattern}")
        message(FATAL_ERROR "Expected ${pattern}: ${ARGN}: ${result} ${errors} ${output}")
    endif()
endfunction()
foreach(level 0 1)
    foreach(fixture lifecycle executor void exit)
        compile_ok(--link=external "-O${level}" "${work}/${fixture}/main.dmm" -o "${work}/${fixture}.exe")
        if(fixture STREQUAL lifecycle)
            run_ok("${work}/${fixture}.exe" 37 "init\nmain\nworker\nlocal\npackage\n")
        elseif(fixture STREQUAL exit)
            run_ok("${work}/${fixture}.exe" 23 "")
        else()
            run_ok("${work}/${fixture}.exe" 0 "")
        endif()
    endforeach()
    foreach(target elf coff)
        compile_ok(--link=external --emit=obj "--target=${target}" "-O${level}"
            --linker-driver "${work}/not-needed" --runtime-shim "${work}/not-needed-shim"
            "${work}/lifecycle/main.dmm" -o "${work}/program_${target}.o")
        foreach(syntax intel att)
            compile_ok(--link=external --emit=asm "--target=${target}" "--syntax=${syntax}" "-O${level}"
                "${work}/lifecycle/main.dmm" -o "${work}/program_${target}_${syntax}.s")
            file(READ "${work}/program_${target}_${syntax}.s" assembly)
            if(NOT assembly MATCHES "__dmm_runtime_main" OR assembly MATCHES "[.]globl __dmm_entry")
                message(FATAL_ERROR "Wrong platform assembly profile")
            endif()
            if(target STREQUAL host)
                execute_process(COMMAND "${ASSEMBLER}" "${work}/program_${target}_${syntax}.s"
                    -no-pie -pthread -o "${work}/manual.exe" RESULT_VARIABLE result ERROR_VARIABLE errors TIMEOUT 30)
                if(NOT result EQUAL 0)
                    message(FATAL_ERROR "Manual assembly handoff failed: ${result} ${errors}")
                endif()
                run_ok("${work}/manual.exe" 37 "init\nmain\nworker\nlocal\npackage\n")
            endif()
        endforeach()
    endforeach()
    execute_process(COMMAND "${ASSEMBLER}" "${work}/program_${host}.o" "${SHIM}"
        -no-pie -pthread -o "${work}/manual-object.exe" RESULT_VARIABLE result ERROR_VARIABLE errors TIMEOUT 30)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "Manual object handoff failed: ${result} ${errors}")
    endif()
    run_ok("${work}/manual-object.exe" 37 "init\nmain\nworker\nlocal\npackage\n")
endforeach()
# Explicit overrides, including whitespace in the shim and driver paths.
file(COPY_FILE "${SHIM}" "${work}/shim copy.o")
compile_ok(--link=external --linker-driver "${ASSEMBLER}" --runtime-shim "${work}/shim copy.o"
    "${work}/void/main.dmm" -o "${work}/override.exe")
run_ok("${work}/override.exe" 0 "")
file(WRITE "${work}/bad-shim.o" "not a native object")
fail_match("Invalid link mode" --link=bad "${work}/void/main.dmm")
fail_match("Missing value" --runtime-shim)
fail_match("Incompatible additional runtime object" --link=external --runtime-shim "${work}/bad-shim.o" "${work}/void/main.dmm" -o "${work}/failed.exe")
fail_match("Incompatible additional runtime object" --link=external --runtime-shim "${work}/missing.o" "${work}/void/main.dmm" -o "${work}/failed.exe")
fail_match("External linker" --link=external --linker-driver "${work}/missing-driver" "${work}/void/main.dmm" -o "${work}/failed.exe")
file(COPY_FILE "${FAIL_DRIVER}" "${work}/failure driver.exe")
fail_match("status 42.*private linker (stdout|stderr).*private linker (stdout|stderr)" --link=external
    --linker-driver "${work}/failure driver.exe" "${work}/void/main.dmm" -o "${work}/failed.exe")
execute_process(COMMAND "${COMPILER}" --formatError --link=external --linker-driver "${work}/failure driver.exe"
    "${work}/void/main.dmm" -o "${work}/failed.exe" RESULT_VARIABLE result OUTPUT_VARIABLE json ERROR_VARIABLE errors)
if(result EQUAL 0 OR NOT "${json}${errors}" MATCHES "private linker stderr")
    message(FATAL_ERROR "Linker diagnostics lost in JSON mode")
endif()
file(WRITE "${work}/existing.exe" "preserve existing artifact")
fail_match("External linker" --link=external --linker-driver "${work}/failure driver.exe"
    "${work}/void/main.dmm" -o "${work}/existing.exe")
file(READ "${work}/existing.exe" existing)
if(NOT existing STREQUAL "preserve existing artifact")
    message(FATAL_ERROR "Failed link replaced existing output")
endif()
if(EXISTS "${work}/failed.exe")
    message(FATAL_ERROR "Failed link published an executable")
endif()
fail_match("Cross-linking requires" --link=external "--target=${other}" "${work}/void/main.dmm" -o "${work}/cross.exe")
fail_match("conflicts with linker input" --link=external --runtime-shim "${work}/shim copy.o" "${work}/void/main.dmm" -o "${work}/shim copy.o")
file(SHA256 "${work}/shim copy.o" shim_before)
fail_match("conflicts with linker input" --link=external --runtime-shim "${work}/shim copy.o"
    --dump-ast "${work}/shim copy.o" "${work}/void/main.dmm" -o "${work}/unused.exe")
file(SHA256 "${work}/shim copy.o" shim_after)
if(NOT shim_before STREQUAL shim_after)
    message(FATAL_ERROR "Dump overwrote linker input")
endif()
file(SHA256 "${SHIM}" default_before)
fail_match("conflicts with linker input" --link=external --runtime-shim "${SHIM}" --dump-tokens "${SHIM}"
    "${work}/void/main.dmm" -o "${work}/unused.exe")
file(SHA256 "${SHIM}" default_after)
if(NOT default_before STREQUAL default_after)
    message(FATAL_ERROR "Dump overwrote default runtime shim")
endif()
file(READ "${work}/void/main.dmm" original)
fail_match("differ from" --link=external "${work}/void/main.dmm" -o "${work}/void/main.dmm")
file(READ "${work}/void/main.dmm" preserved)
if(NOT preserved STREQUAL original)
    message(FATAL_ERROR "Source overwritten")
endif()
compile_ok(--link=internal "${work}/void/main.dmm" -o "${work}/standalone.exe")
run_ok("${work}/standalone.exe" 0 "")
file(GLOB leftovers "${work}/*.dmm-link-*")
if(leftovers)
    message(FATAL_ERROR "Leaked link directories: ${leftovers}")
endif()
