cmake_minimum_required(VERSION 3.21)
file(MAKE_DIRECTORY "${OUTPUT_DIR}")
if(WIN32)
    set(host coff)
else()
    set(host elf)
endif()
function(compile_ok)
    execute_process(COMMAND "${COMPILER}" ${ARGV} RESULT_VARIABLE result ERROR_VARIABLE errors TIMEOUT 45)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "Runtime component compilation failed: ${ARGV}: ${errors}")
    endif()
endfunction()
foreach(target elf coff)
    foreach(level 0 1)
        set(object "${OUTPUT_DIR}/platform_${target}_${level}.o")
        compile_ok(--runtime-component "--target=${target}" "-O${level}"
            --dump-native-link "${object}.link" -o "${object}"
            "${SOURCE_DIR}/stdlib/native/threading/threading.dmm")
        file(READ "${object}.link" inventory)
        if(NOT inventory MATCHES "dmm-native-link-v2" OR NOT inventory MATCHES "runtime-profile=component")
            message(FATAL_ERROR "Wrong bootstrap dependency inventory: ${inventory}")
        endif()
        execute_process(COMMAND "${NM}" -u "${object}" RESULT_VARIABLE result OUTPUT_VARIABLE undefined ERROR_VARIABLE errors)
        if(NOT result EQUAL 0 OR undefined MATCHES "__dmm_")
            message(FATAL_ERROR "Recursive runtime dependency: ${undefined} ${errors}")
        endif()
        execute_process(COMMAND "${NM}" -g --defined-only "${object}" RESULT_VARIABLE result OUTPUT_VARIABLE exported)
        if(NOT result EQUAL 0 OR exported MATCHES "__dmm_p[0-9a-f]|__dmm_export_body|[ ]main[\r\n]" OR
           NOT exported MATCHES "__dmm_async_thread_create" OR NOT exported MATCHES "__dmm_platform_exit")
            message(FATAL_ERROR "Wrong component exports: ${exported}")
        endif()
        if(target STREQUAL host)
            execute_process(COMMAND "${C_DRIVER}" -std=c11 -pthread
                "-I${SOURCE_DIR}/src/runtime" "-I${SOURCE_DIR}/src/common" "-I${SOURCE_DIR}/src/ir"
                "-I${SOURCE_DIR}/src/ast" "-I${SOURCE_DIR}/src/sema"
                "${SOURCE_DIR}/tests/unit/platform_shim_test.c" "${object}" -o "${object}.exe"
                RESULT_VARIABLE result ERROR_VARIABLE errors TIMEOUT 30)
            if(NOT result EQUAL 0)
                message(FATAL_ERROR "Runtime component C contract link failed: ${errors}")
            endif()
            execute_process(COMMAND "${object}.exe" RESULT_VARIABLE result TIMEOUT 20)
            if(NOT result EQUAL 0)
                message(FATAL_ERROR "Runtime component thread/event/TLS contract failed: ${result}")
            endif()
        endif()
        foreach(syntax intel att)
            set(assembly "${OUTPUT_DIR}/platform_${target}_${level}_${syntax}.s")
            compile_ok(--runtime-component -S "--target=${target}" "--syntax=${syntax}" "-O${level}"
                -o "${assembly}" "${SOURCE_DIR}/stdlib/native/threading/threading.dmm")
            file(READ "${assembly}" text)
            if(text MATCHES "__dmm_runtime_main|__dmm_package_init|__dmm_async_default_drain|[.]globl main")
                message(FATAL_ERROR "Runtime component acquired application startup/runtime")
            endif()
        endforeach()
    endforeach()
endforeach()
function(reject name source pattern)
    file(MAKE_DIRECTORY "${OUTPUT_DIR}/${name}")
    file(WRITE "${OUTPUT_DIR}/${name}/dmm.manifest" "module component.test/${name}\ndmm 2026-09-22-dev\n")
    file(WRITE "${OUTPUT_DIR}/${name}/library.dmm" "${source}")
    execute_process(COMMAND "${COMPILER}" ${ARGN} -o "${OUTPUT_DIR}/${name}/out.o"
        "${OUTPUT_DIR}/${name}/library.dmm" RESULT_VARIABLE result ERROR_VARIABLE errors OUTPUT_VARIABLE output TIMEOUT 45)
    if(result EQUAL 0 OR NOT "${errors}${output}" MATCHES "${pattern}")
        message(FATAL_ERROR "Expected component rejection ${name}/${pattern}: ${errors}${output}")
    endif()
endfunction()
reject(reserved "package component; export \"system\" func __dmm_platform_exit(code:i32) -> void {}"
    "reserved by the runtime" -c)
reject(foreign "package component; export \"system\" func applicationHook() -> void {}"
    "outside the private runtime ABI" --runtime-component)
reject(executable "package component;" "require object/assembly" --runtime-component --emit=exe)
reject(linker "package component;" "without linker or runtime overrides" --runtime-component --link=external)
reject(startup "package main; func main() -> int { return 0; }" "requires a library package" --runtime-component)
reject(initializer "package component; func initialize() -> i32 { return 1; } var value:i32=initialize();"
    "global initialization or cleanup" --runtime-component)
reject(implicit "package component; import \"stdlib/core\"; export \"system\" func __dmm_async_wait_create() -> *void { return core.core_alloc(8).(*void); }"
    "explicit native declaration" --runtime-component)
reject(masked "package component; import \"stdlib/core\"; extern \"system\" from \"dmm_basis\" { func basisNull() -> *void = \"__dmm_core_null\"; } export \"system\" func __dmm_async_wait_create() -> *void { return core.core_alloc(8).(*void); }"
    "explicit native declaration" --runtime-component)
file(MAKE_DIRECTORY "${OUTPUT_DIR}/explicit")
file(WRITE "${OUTPUT_DIR}/explicit/dmm.manifest" "module component.test/explicit\ndmm 2026-09-22-dev\n")
file(WRITE "${OUTPUT_DIR}/explicit/library.dmm" "package component; extern \"system\" from \"dmm_basis\" { func basisNull() -> *void = \"__dmm_core_null\"; } export \"system\" func __dmm_async_wait_create() -> *void { return basisNull(); }\n")
compile_ok(--runtime-component --dump-native-link "${OUTPUT_DIR}/explicit/native.link"
    -o "${OUTPUT_DIR}/explicit/library.o" "${OUTPUT_DIR}/explicit/library.dmm")
file(READ "${OUTPUT_DIR}/explicit/native.link" explicit)
if(NOT explicit MATCHES "dmm_basis" OR NOT explicit MATCHES "__dmm_core_null")
    message(FATAL_ERROR "Explicit compiler base dependency missing from inventory: ${explicit}")
endif()
if(AR)
    execute_process(COMMAND "${AR}" rcs "${OUTPUT_DIR}/mixed.a"
        "${OUTPUT_DIR}/platform_elf_0.o" "${OUTPUT_DIR}/platform_coff_0.o"
        RESULT_VARIABLE result ERROR_VARIABLE errors)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "Mixed archive fixture failed: ${errors}")
    endif()
    file(READ "${OUTPUT_DIR}/mixed.a" prefix LIMIT 90)
    file(WRITE "${OUTPUT_DIR}/truncated.a" "${prefix}")
    file(WRITE "${OUTPUT_DIR}/empty.a" "!<arch>\n")
    file(MAKE_DIRECTORY "${OUTPUT_DIR}/override")
    file(WRITE "${OUTPUT_DIR}/override/dmm.manifest" "module component.test/override\ndmm 2026-09-22-dev\n")
    file(WRITE "${OUTPUT_DIR}/override/main.dmm" "package main; func main() -> int { return 0; }\n")
    foreach(archive mixed truncated empty)
        file(WRITE "${OUTPUT_DIR}/override/preserved.exe" "preserved")
        execute_process(COMMAND "${COMPILER}" --link=external --runtime-shim "${OUTPUT_DIR}/${archive}.a"
            -o "${OUTPUT_DIR}/override/preserved.exe" "${OUTPUT_DIR}/override/main.dmm"
            RESULT_VARIABLE result ERROR_VARIABLE errors TIMEOUT 30)
        file(READ "${OUTPUT_DIR}/override/preserved.exe" preserved)
        if(result EQUAL 0 OR NOT errors MATCHES "Incompatible additional runtime object" OR NOT preserved STREQUAL "preserved")
            message(FATAL_ERROR "Archive target validation/preservation failed for ${archive}: ${errors}")
        endif()
    endforeach()
endif()
