# Generated test programs are explicit packages in an isolated test module.
function(dmm_test_write path)
    set(text "${ARGV1}")
    if (ARGC GREATER 2)
        math(EXPR last "${ARGC}-1")
        foreach (index RANGE 2 ${last})
            string(APPEND text "${ARGV${index}}")
        endforeach ()
    endif ()
    get_filename_component(directory "${path}" DIRECTORY)
    file(MAKE_DIRECTORY "${directory}")
    if (path MATCHES "\\.dmm$")
        if (NOT text MATCHES "^package ")
            set(text "package main;\n${text}")
        endif ()
        string(REPLACE "import <stdlib>" "import \"stdlib/core\"; import \"stdlib/io\";" text "${text}")
        string(REPLACE "import <stdlib/core>" "import \"stdlib/core\";" text "${text}")
        if (text MATCHES "import \"stdlib/io\";")
            foreach (name print println)
                string(REGEX REPLACE "(^|[^A-Za-z0-9_.])${name}([(<.])" "\\1io.${name}\\2" text "${text}")
            endforeach ()
        endif ()
        if (text MATCHES "import \"stdlib/core\";")
            foreach (name unwrapOr Option Result)
                string(REGEX REPLACE "(^|[^A-Za-z0-9_.])${name}([(<.])" "\\1core.${name}\\2" text "${text}")
            endforeach ()
            string(REGEX REPLACE "(^|[^A-Za-z0-9_.])(core_[A-Za-z0-9_]+)" "\\1memraw.\\2" text "${text}")
            string(REGEX REPLACE "(^|[^A-Za-z0-9_.])(CORE_[A-Z0-9_]+)" "\\1ioraw.\\2" text "${text}")
        endif ()
        if(text MATCHES "memraw[.]" AND NOT text MATCHES "import memraw \"stdlib/memory/raw\"")
            string(REGEX REPLACE "^(package [^;]+;)" "\\1\nimport memraw \"stdlib/memory/raw\";" text "${text}")
        endif()
        if(text MATCHES "ioraw[.]" AND NOT text MATCHES "import ioraw \"stdlib/io/raw\"")
            string(REGEX REPLACE "^(package [^;]+;)" "\\1\nimport ioraw \"stdlib/io/raw\";" text "${text}")
        endif()
        # Always refresh the generated module edition so an existing test directory
        # cannot retain a manifest from an older compiler edition.
        file(WRITE "${OUTPUT_DIR}/dmm.manifest" "module dmm.test/generated\ndmm 2026-10-04-dev\n")
    endif ()
    file(WRITE "${path}" "${text}")
endfunction()

function(dmm_test_abi_definitions artifact output)
    if (artifact MATCHES "\\.s$")
        file(READ "${artifact}" symbols)
    else ()
        get_filename_component(tool_directory "${ASSEMBLER}" DIRECTORY)
        find_program(DMM_ABI_OBJDUMP NAMES objdump HINTS "${tool_directory}" REQUIRED)
        execute_process(COMMAND "${DMM_ABI_OBJDUMP}" -t "${artifact}" OUTPUT_VARIABLE symbols RESULT_VARIABLE result)
        if (NOT result STREQUAL "0")
            message(FATAL_ERROR "Cannot inspect ABI symbols")
        endif ()
    endif ()
    string(REGEX MATCHALL "__dmm_p[0-9a-f]+___dmm_f[0-9]+_[A-Za-z0-9_]+__[0-9]+[_A-Za-z0-9]*" names "${symbols}")
    set(definitions)
    foreach (name IN LISTS names)
        string(REGEX REPLACE "^__dmm_p[0-9a-f]+___dmm_f[0-9]+_(.*)__[0-9]+.*$" "\\1" original "${name}")
        list(APPEND definitions "-D${original}=${name}")
    endforeach ()
    list(REMOVE_DUPLICATES definitions)
    set(${output} "${definitions}" PARENT_SCOPE)
endfunction()
