# Generated programs provide their entry point and runtime; only OS APIs remain.
set(STANDALONE_FLAGS -nostdlib -no-pie -Wl,-e,__dmm_entry)
set(SYSTEM_LIBRARIES "")
if(WIN32)
    list(APPEND STANDALONE_FLAGS -Wl,--subsystem,console)
    set(SYSTEM_LIBRARIES -lkernel32)
endif()

function(check_standalone_dependencies program)
    get_filename_component(tool_directory "${ASSEMBLER}" DIRECTORY)
    find_program(OBJDUMP NAMES objdump HINTS "${tool_directory}" REQUIRED)
    execute_process(COMMAND "${OBJDUMP}" -p "${program}"
        RESULT_VARIABLE result OUTPUT_VARIABLE headers ERROR_VARIABLE errors TIMEOUT 10)
    if(NOT result STREQUAL "0")
        message(FATAL_ERROR "Cannot inspect standalone image: ${errors}")
    endif()
    if(WIN32)
        string(REGEX MATCHALL "DLL Name: [^\r\n]+" libraries "${headers}")
        foreach(library IN LISTS libraries)
            string(TOLOWER "${library}" library)
            if(NOT library STREQUAL "dll name: kernel32.dll")
                message(FATAL_ERROR "Foreign runtime dependency: ${library}")
            endif()
        endforeach()
    elseif(headers MATCHES "INTERP|DYNAMIC|NEEDED")
        message(FATAL_ERROR "Standalone ELF has a loader or dynamic dependency")
    endif()
endfunction()
