cmake_minimum_required(VERSION 3.21)
file(MAKE_DIRECTORY "${OUTPUT_DIR}")
if(WIN32)
    set(host coff)
    set(libraries -lws2_32)
else()
    set(host elf)
    set(libraries -pthread -no-pie)
endif()
function(compile_ok)
    execute_process(COMMAND "${COMPILER}" --runtime-component ${ARGV}
        RESULT_VARIABLE status ERROR_VARIABLE errors TIMEOUT 45)
    if(NOT status EQUAL 0)
        message(FATAL_ERROR "Stdlib component failed: ${ARGV}: ${errors}")
    endif()
endfunction()
foreach(target elf coff)
    foreach(level 0 1)
        foreach(component network executor)
            if(component STREQUAL network)
                set(source "${SOURCE_DIR}/stdlib/core/net/internal/network.dmm")
            else()
                set(source "${SOURCE_DIR}/stdlib/core/executor/executor.dmm")
            endif()
            set(object "${OUTPUT_DIR}/${component}_${target}_${level}.o")
            compile_ok("--target=${target}" "-O${level}" --dump-native-link "${object}.link" -o "${object}" "${source}")
            execute_process(COMMAND "${NM}" -g --defined-only "${object}" RESULT_VARIABLE status OUTPUT_VARIABLE exports)
            if(NOT status EQUAL 0 OR exports MATCHES "__dmm_p[0-9a-f]|__dmm_export_body|[ ]main[\r\n]")
                message(FATAL_ERROR "Component leaked implementation/startup symbols: ${exports}")
            endif()
            execute_process(COMMAND "${NM}" -u "${object}" RESULT_VARIABLE status OUTPUT_VARIABLE imports)
            if(NOT status EQUAL 0 OR imports MATCHES "__dmm_intrinsic|__dmm_rt_malloc|__dmm_runtime_main")
                message(FATAL_ERROR "Component acquired implicit application runtime: ${imports}")
            endif()
            foreach(syntax intel att)
                set(assembly "${OUTPUT_DIR}/${component}_${target}_${level}_${syntax}.s")
                compile_ok("--target=${target}" "-O${level}" -S "--syntax=${syntax}" -o "${assembly}" "${source}")
            endforeach()
        endforeach()
        if(target STREQUAL host)
            # Reuse the complete independent C ownership/race harness with DMM
            # implementation and test-only injected gates at both optimization levels.
            foreach(syntax obj intel att)
                set(artifact "${OUTPUT_DIR}/network_test_${level}_${syntax}")
                set(emission -c)
                set(language -x none)
                if(NOT syntax STREQUAL obj)
                    set(emission -S "--syntax=${syntax}")
                    set(language -x assembler)
                endif()
                compile_ok("--target=${target}" "-O${level}" ${emission} -o "${artifact}.o" "${TEST_PACKAGE}/network.dmm")
                execute_process(COMMAND "${C_DRIVER}" -std=c11 "-I${SOURCE_DIR}/src/runtime"
                    "${SOURCE_DIR}/tests/unit/network_shim_test.c" ${language} "${artifact}.o" -x none
                    "${PLATFORM_COMPONENT}" ${libraries} -o "${artifact}.exe"
                    RESULT_VARIABLE status ERROR_VARIABLE errors TIMEOUT 30)
                if(NOT status EQUAL 0)
                    message(FATAL_ERROR "DMM parity harness link failed: ${errors}")
                endif()
                execute_process(COMMAND "${artifact}.exe" RESULT_VARIABLE status TIMEOUT 30)
                if(NOT status EQUAL 0)
                    message(FATAL_ERROR "DMM parity harness failed: ${level}/${syntax}: ${status}")
                endif()
            endforeach()
        endif()
    endforeach()
endforeach()
foreach(case scalar typed_pointer feature)
    file(MAKE_DIRECTORY "${OUTPUT_DIR}/${case}")
    set(features "features = [\"async\"]\n")
    set(argument "0")
    set(parameter "")
    if(case STREQUAL typed_pointer)
        set(parameter "p:*u8")
        set(argument p)
    elseif(case STREQUAL feature)
        set(features "")
        set(parameter "p:*void")
        set(argument p)
    endif()
    file(WRITE "${OUTPUT_DIR}/${case}/dmm.manifest" "module native.future/${case}\ndmm 2026-09-22-dev\n${features}")
    file(WRITE "${OUTPUT_DIR}/${case}/library.dmm" "package fixture; func invalid(${parameter})->Future<void> { return nativeFuture(${argument}); }\n")
    execute_process(COMMAND "${COMPILER}" -c -o "${OUTPUT_DIR}/${case}/out.o" "${OUTPUT_DIR}/${case}/library.dmm"
        RESULT_VARIABLE status ERROR_VARIABLE errors TIMEOUT 20)
    if(status EQUAL 0 OR NOT errors MATCHES "nativeFuture requires|async manifest feature")
        message(FATAL_ERROR "Native Future bridge accepted invalid ${case}: ${errors}")
    endif()
endforeach()
