cmake_minimum_required(VERSION 3.21)
include("${SOURCE_DIR}/tests/collection_allocation_faults_test.cmake")
file(MAKE_DIRECTORY "${OUTPUT_DIR}")
foreach(level 0 1)
    set(closure_program "${OUTPUT_DIR}/language_closures_${level}.exe")
    execute_process(COMMAND "${COMPILER}" "-O${level}" --emit=exe
        "${SOURCE_DIR}/tests/stdlib/language_closures/language_closures.dmm" -o "${closure_program}"
        RESULT_VARIABLE status ERROR_VARIABLE errors TIMEOUT 60)
    if(NOT status EQUAL 0)
        message(FATAL_ERROR "Capturing closures O${level}: ${errors}")
    endif()
    execute_process(COMMAND "${closure_program}" RESULT_VARIABLE status TIMEOUT 15)
    if(NOT status EQUAL 0)
        message(FATAL_ERROR "Capturing closures O${level}: ${status}")
    endif()
    set(collection_program "${OUTPUT_DIR}/language_collections_${level}.exe")
    execute_process(COMMAND "${COMPILER}" "-O${level}" --emit=exe
        "${SOURCE_DIR}/tests/stdlib/language_collections/language_collections.dmm" -o "${collection_program}"
        RESULT_VARIABLE status ERROR_VARIABLE errors TIMEOUT 60)
    if(NOT status EQUAL 0)
        message(FATAL_ERROR "Owner collections O${level}: ${errors}")
    endif()
    execute_process(COMMAND "${collection_program}" RESULT_VARIABLE status TIMEOUT 15)
    if(NOT status EQUAL 0)
        message(FATAL_ERROR "Owner collections O${level}: ${status}")
    endif()
    set(file_program "${OUTPUT_DIR}/language_files_${level}.exe")
    execute_process(COMMAND "${COMPILER}" "-O${level}" --emit=exe
        "${SOURCE_DIR}/tests/stdlib/language_files/language_files.dmm" -o "${file_program}"
        RESULT_VARIABLE status ERROR_VARIABLE errors TIMEOUT 60)
    if(NOT status EQUAL 0)
        message(FATAL_ERROR "File ownership O${level}: ${errors}")
    endif()
    execute_process(COMMAND "${file_program}" WORKING_DIRECTORY "${OUTPUT_DIR}" RESULT_VARIABLE status TIMEOUT 15)
    if(NOT status EQUAL 0)
        message(FATAL_ERROR "File ownership O${level}: ${status}")
    endif()
    set(lifetime_program "${OUTPUT_DIR}/language_lifetimes_${level}.exe")
    execute_process(COMMAND "${COMPILER}" "-O${level}" --emit=exe
        "${SOURCE_DIR}/tests/stdlib/language_lifetimes/language_lifetimes.dmm" -o "${lifetime_program}"
        RESULT_VARIABLE status ERROR_VARIABLE errors TIMEOUT 60)
    if(NOT status EQUAL 0)
        message(FATAL_ERROR "Stored lifetimes O${level}: ${errors}")
    endif()
    execute_process(COMMAND "${lifetime_program}" RESULT_VARIABLE status TIMEOUT 15)
    if(NOT status EQUAL 0)
        message(FATAL_ERROR "Stored lifetimes O${level}: ${status}")
    endif()
    set(async_program "${OUTPUT_DIR}/language_gaps_async_${level}.exe")
    execute_process(COMMAND "${COMPILER}" "-O${level}" --emit=exe
        "${SOURCE_DIR}/tests/stdlib/language_gaps_async/language_gaps_async.dmm" -o "${async_program}"
        RESULT_VARIABLE status ERROR_VARIABLE errors TIMEOUT 60)
    if(NOT status EQUAL 0)
        message(FATAL_ERROR "Language gaps async O${level}: ${errors}")
    endif()
    execute_process(COMMAND "${async_program}" RESULT_VARIABLE status TIMEOUT 15)
    if(NOT status EQUAL 0)
        message(FATAL_ERROR "Language gaps async O${level}: ${status}")
    endif()
    set(program "${OUTPUT_DIR}/language_gaps_${level}.exe")
    execute_process(COMMAND "${COMPILER}" "-O${level}" --emit=exe
        "${SOURCE_DIR}/tests/stdlib/language_gaps/language_gaps.dmm" -o "${program}"
        RESULT_VARIABLE status ERROR_VARIABLE errors TIMEOUT 60)
    if(NOT status EQUAL 0)
        message(FATAL_ERROR "Language gaps O${level}: ${errors}")
    endif()
    execute_process(COMMAND "${program}" RESULT_VARIABLE status TIMEOUT 15)
    if(NOT status EQUAL 0)
        message(FATAL_ERROR "Language gaps O${level} destruction/ownership execution: ${status}")
    endif()
    foreach(target elf coff)
        foreach(mode obj intel att)
            set(options --emit=obj)
            if(NOT mode STREQUAL obj)
                set(options --emit=asm "--syntax=${mode}")
            endif()
            execute_process(COMMAND "${COMPILER}" "-O${level}" "--target=${target}" ${options}
                "${SOURCE_DIR}/tests/stdlib/language_gaps/language_gaps.dmm"
                -o "${OUTPUT_DIR}/language_gaps_${target}_${level}_${mode}.out"
                RESULT_VARIABLE status ERROR_VARIABLE errors TIMEOUT 30)
            if(NOT status EQUAL 0)
                message(FATAL_ERROR "Language gaps ${target}/O${level}/${mode}: ${errors}")
            endif()
            foreach(fixture language_lifetimes language_collections language_files language_closures language_gaps_async)
                execute_process(COMMAND "${COMPILER}" "-O${level}" "--target=${target}" ${options}
                    "${SOURCE_DIR}/tests/stdlib/${fixture}/${fixture}.dmm"
                    -o "${OUTPUT_DIR}/${fixture}_${target}_${level}_${mode}.out"
                    RESULT_VARIABLE status ERROR_VARIABLE errors TIMEOUT 30)
                if(NOT status EQUAL 0)
                    message(FATAL_ERROR "${fixture} ${target}/O${level}/${mode}: ${errors}")
                endif()
            endforeach()
        endforeach()
    endforeach()
endforeach()

function(reject name body expected)
    set(work "${OUTPUT_DIR}/${name}")
    file(MAKE_DIRECTORY "${work}")
    file(WRITE "${work}/dmm.manifest" "module gaps/${name}\ndmm 2026-10-04-dev\nfeatures = [\"async\"]\n")
    file(WRITE "${work}/case.dmm" "package main;\nimport (\"stdlib/core\" \"stdlib\" \"stdlib/binary\" \"stdlib/sync\" \"stdlib/collections\");\nstruct Resource { var value:i32; destructor {} }\nenum Owner { Item(Resource), Empty }\n${body}\n")
    execute_process(COMMAND "${COMPILER}" --emit=obj "${work}/case.dmm" -o "${work}/case.o"
        RESULT_VARIABLE status ERROR_VARIABLE errors TIMEOUT 15)
    if(status EQUAL 0 OR NOT errors MATCHES "${expected}")
        message(FATAL_ERROR "Expected rejection ${name} (${expected}): ${status}: ${errors}")
    endif()
endfunction()
reject(return_owned_parameter_storage "func wrong(value:i32)->&i32 { return &value; } func main()->void {}" "Returned borrow may outlive its owner")
# Known conservative restriction, not an accepted borrowed-payload propagation API.
reject(return_option_borrow_via_propagation "func forward(value:stdlib.Option<&i32>)->stdlib.Option<&i32> { var reference=value?; return stdlib.Option<&i32>.Some(reference); } func main()->void {}" "cannot capture a borrow of a local value")
reject(copy_owner "func copy<T:core.Copy>(x:T)->T { return x; } func main()->void { var r:Resource; var x=copy(r); }" "core.Copy requires")
reject(copy_override "@[core.Copy] struct Claimed { var r:Resource; } func main()->void {}" "cannot be overridden")
reject(foreign_copy "auto interface Copy {} func copy<T:Copy>(x:T)->T { return x; } func main()->void { var x=copy(42); }" "No generic function")
reject(method_copy "struct Conditional<T> { var value:T; func get()->T where T:core.Copy { return value; } } func main()->void { var x:Conditional<Resource>; var y=x.get(); }" "No method overload")
reject(match_moved "func main()->void { var o=Owner.Item(Resource{value:1}); match(o) { Item(r)=>{} Empty=>{} } match(o) { Item(r)=>{} Empty=>{} } }" "after ownership was moved")
reject(match_wildcard "func main()->void { var o=Owner.Item(Resource{value:1}); match(o) { _=>{} } }" "must bind every variant payload")
reject(pattern_move "func main()->void { var o=Owner.Item(Resource{value:1}); match(&o) { Item(r)=>{ var other=take(o); var v=(*r).value; } Empty=>{} } }" "borrow")
reject(pattern_escape "func escape()->&Resource { var o=Owner.Item(Resource{value:1}); match(&o) { Item(r)=>return r; Empty=>core.core_trap(); } } func main()->void {}" "borrow|reference")
reject(take_dead "func main()->void { var r:Resource; var x=take(r); var y=take(r); }" "destroyed|uninitialized")
reject(take_borrowed "func main()->void { var r:Resource; var loan=&r; var x=take(r); var y=(*loan).value; }" "borrow")
reject(take_partial "struct Pair { var a:Resource; var b:Resource; } func main()->void { var p:Pair; var x=take(p.a); }" "partial lifetimes")
reject(take_reference_value "func main()->void { var x:i32=1; var reference=&x; var moved=take(reference); }" "nested reference support")
reject(replace_reference_value "func main()->void { var x:i32=1; var y:i32=2; var reference=&x; var old=replace(reference,&y); }" "nested reference support")
reject(replace_dead "func main()->void { var r:Resource; var x=take(r); var y=replace(r,Resource{value:2}); }" "destroyed|uninitialized")
reject(callback_conflict "func map<T,U>(x:T,f:func(T)->U)->U { return f(x); } func mapper(x:i64)->i32 { return 1; } func main()->void { var x:i32=1; var y=map(x,mapper); }" "Callback signature conflicts")
reject(callback_ambiguous "func invoke<T,U>(f:func(T)->U)->void {} func mapper(x:i64)->i32 { return 1; } func mapper(x:i32)->i32 { return 1; } func main()->void { invoke(mapper); }" "Ambiguous callback inference")
reject(take_future_discard "async func work()->i32 { return 1; } func main()->void { var f=work(); take(f); }" "implicit drop is forbidden")
reject(take_future_escape "async func work(x:&i32)->i32 { return *x; } func escape()->Future<i32> { var x:i32=1; var f=work(&x); return take(f); } func main()->void {}" "cannot capture a borrow of a local")
reject(replace_future_borrow "async func work(x:&i32)->i32 { return *x; } func main()->void { var x:i32=1; var y:i32=2; var f=work(&x); block_on(replace(f,work(&y))); y=3; block_on(f); }" "borrow")
reject(match_future_drop "enum Tasks { Task(Future<i32>), Empty } async func work()->i32 { return 1; } func main()->void { var tasks=Tasks.Task(work()); match(tasks) { Task(f)=>{} Empty=>{} } }" "implicit drop is forbidden")
reject(stored_borrow_escape "struct Reader<'a> { var source:&'a i32; } func escape<'a>()->Reader<'a> { var source:i32=1; return Reader<'a>{source:&source}; } func main()->void {}" "cannot capture a borrow of a local")
reject(stored_borrow_scope "struct Reader<'a> { var source:&'a i32; } func main()->void { var r:Reader; { var source:i32=1; r=Reader{source:&source}; } var x=*r.source; }" "cannot outlive its source")
reject(stored_borrow_copy "struct Reader<'a> { var source:&'a i32; } func make<'a>(source:&'a i32)->Reader<'a> { return Reader<'a>{source:source}; } func main()->void { var source:i32=1; var r=make(&source); var copy=r; source=2; var x=*copy.source; }" "borrow")
reject(stored_mutable_move "struct Writer<'a> { var source:&'a mut i32; } func main()->void { var source:i32=1; var w=Writer{source:&mut source}; var moved=w; var x=*w.source; }" "after ownership was moved")
reject(stored_mutable_reborrow "struct Writer<'a> { var source:&'a mut i32; } func main()->void { var source:i32=1; var w=Writer{source:&mut source}; var alias=w.source; *w.source=2; var x=*alias; }" "reborrow|borrow")
reject(stored_borrow_unknown "struct Reader<'a> { var source:&'b i32; } func main()->void {}" "Unknown lifetime|Unknown field type")
reject(stored_borrow_duplicate "struct Reader<'a,'a> { var source:&'a i32; } func main()->void {}" "Duplicate lifetime")
reject(stored_borrow_default "struct Reader<'a> { var source:&'a i32; } func main()->void { var r:Reader; var x=*r.source; }" "uninitialized")
reject(result_lifetime_mismatch "func wrong<'a,'b>(left:&'a i32,right:&'b i32)->&'a i32 { return right; } func main()->void {}" "declared result lifetime")
reject(result_aggregate_lifetime_mismatch "struct Reader<'a> { var source:&'a i32; } func wrong<'a,'b>(source:&'b i32)->Reader<'a> { return Reader<'a>{source:source}; } func main()->void {}" "declared lifetimes")
reject(static_borrow_call "func read(source:&'static i32)->i32 { return *source; } func main()->void { var source:i32=1; var x=read(&source); }" "permanently live storage")
reject(static_borrow_field "struct Reader { var source:&'static i32; } func main()->void { var source:i32=1; var r=Reader{source:&source}; }" "permanently live storage")
reject(package_borrow_source_write "var source:i32=1; var saved:&'static i32=&source; func modify()->void { source=2; } func main()->void { modify(); }" "borrow")
reject(package_borrow_source_mutable "var source:i32=1; var saved:&'static i32=&source; func main()->void { var loan=&mut source; *loan=2; }" "Conflicting checked borrows")
reject(package_borrow_rebind "var source:i32=1; var other:i32=2; var saved:&'static i32=&source; func main()->void { saved=&other; }" "cannot be rebound")
reject(package_empty_borrow_rebind "var source:i32=1; var saved:stdlib.Option<&'static i32>=stdlib.Option<&'static i32>.None; func main()->void { saved=stdlib.Option<&'static i32>.Some(&source); }" "cannot be rebound")
reject(package_aggregate_borrow_source_write "struct Reader<'a> { var source:&'a i32; } var source:i32=1; var saved:Reader<'static>=Reader<'static>{source:&source}; func modify()->void { source=2; } func main()->void {}" "borrow")
reject(package_aggregate_borrow_rebind "struct Reader<'a> { var source:&'a i32; } var source:i32=1; var saved:Reader<'static>=Reader<'static>{source:&source}; func main()->void { saved=Reader<'static>{source:&source}; }" "cannot be rebound")
reject(package_borrow_no_origin "var saved:&'static i32; func main()->void {}" "provably permanent origin")
reject(package_borrow_local_origin "func escape()->&i32 { var local:i32=1; return &local; } var saved:&i32=escape(); func main()->void {}" "borrow|provably permanent origin")
reject(package_mutable_borrow "var source:i32=1; var saved:&'static mut i32=&mut source; func main()->void {}" "interprocedural exclusive-access proof")
reject(package_borrow_uninitialized_source "@[no_default] struct Source { var value:i32; } var source:Source; var saved:&'static Source=&source; func main()->void {}" "initialized permanent storage")
reject(package_borrow_raw_referent "var source:*i32; var saved:&'static i32=&*source; func main()->void {}" "permanently live referent")
reject(stored_constructor_exclusive_alias "struct Pair<'a> { var left:&'a mut i32; var right:&'a mut i32; } func main()->void { var value:i32=1; var pair=Pair{left:&mut value,right:&mut value}; }" "Conflicting checked borrows")
reject(stored_constructor_shared_alias "struct Pair<'a> { var left:&'a mut i32; var right:&'a i32; } func main()->void { var value:i32=1; var pair=Pair{left:&mut value,right:&value}; }" "Conflicting checked borrows")
reject(stored_enum_exclusive_alias "enum Pair<'a> { Values(&'a mut i32,&'a mut i32) } func main()->void { var value:i32=1; var pair=Pair.Values(&mut value,&mut value); }" "Conflicting checked borrows")
reject(stored_constructor_returned_alias "struct Pair<'a> { var left:&'a mut i32; var right:&'a mut i32; } func borrow<'a>(value:&'a mut i32)->&'a mut i32 { return value; } func main()->void { var value:i32=1; var pair=Pair{left:borrow(&mut value),right:borrow(&mut value)}; }" "Conflicting checked borrows")
reject(stored_nested_constructor_alias "struct Writer<'a> { var source:&'a mut i32; } struct Pair<'a> { var left:Writer<'a>; var right:Writer<'a>; } func writer<'a>(source:&'a mut i32)->Writer<'a> { return Writer<'a>{source:source}; } func main()->void { var source:i32=1; var pair=Pair{left:writer(&mut source),right:writer(&mut source)}; }" "borrow")
reject(stored_constructor_later_mutation "struct Reader<'a> { var source:&'a i32; var value:i32; } func modify(source:&mut i32)->i32 { *source=2; return 2; } func main()->void { var source:i32=1; var value=Reader{source:&source,value:modify(&mut source)}; }" "borrow")
reject(stored_return_field_lifetime "struct Pair<'a,'b> { var left:&'a i32; var right:&'b i32; } func swapped<'a,'b>(left:&'a i32,right:&'b i32)->Pair<'a,'b> { return Pair<'a,'b>{left:right,right:left}; } func main()->void {}" "declared result lifetime")
reject(stored_return_field_reborrow "struct Pair<'a,'b> { var left:&'a mut i32; var right:&'b mut i32; } func pair<'a,'b>(left:&'a mut i32,right:&'b mut i32)->Pair<'a,'b> { return Pair<'a,'b>{left:left,right:right}; } func main()->void { var left:i32=1; var right:i32=2; var value=pair(&mut left,&mut right); var reference=&*value.left; *value.left=3; var read=*reference; }" "reborrow|borrow")
reject(stored_return_field_source_write "struct Pair<'a,'b> { var left:&'a i32; var right:&'b i32; } func pair<'a,'b>(left:&'a i32,right:&'b i32)->Pair<'a,'b> { return Pair<'a,'b>{left:left,right:right}; } func main()->void { var left:i32=1; var right:i32=2; var value=pair(&left,&right); right=3; var read=*value.right; }" "borrow")
reject(stored_return_parameter_field_lifetime "struct Pair<'a,'b> { var left:&'a i32; var right:&'b i32; } func wrong<'a,'b>(value:&Pair<'a,'b>)->&'a i32 { return value.right; } func main()->void {}" "declared result lifetime")
reject(stored_return_parameter_field_origin "struct Pair<'a,'b> { var left:&'a i32; var right:&'b i32; } func leftRef<'a,'b>(value:&Pair<'a,'b>)->&'a i32 { return value.left; } func main()->void { var left:i32=1; var right:i32=2; var pair=Pair{left:&left,right:&right}; var reference=leftRef(&pair); left=3; var read=*reference; }" "while it is borrowed")
reject(stored_return_projected_field_origin "struct Pair<'a,'b> { var left:&'a i32; var right:&'b i32; } struct Reader<'a> { var source:&'a i32; } func project<'a,'b>(value:Pair<'a,'b>)->Reader<'a> { return Reader<'a>{source:value.left}; } func main()->void { var left:i32=1; var right:i32=2; var pair=Pair{left:&left,right:&right}; var reference=project(pair); left=3; var read=*reference.source; }" "while it is borrowed")
reject(stored_return_nested_field_union "struct Reader<'a> { var source:&'a i32; } struct Nested<'a> { var direct:&'a i32; var nested:Reader<'a>; } func readNested<'a>(value:&Nested<'a>)->&'a i32 { return value.nested.source; } func main()->void { var left:i32=1; var right:i32=2; var nested=Nested{direct:&left,nested:Reader{source:&right}}; var reference=readNested(&nested); right=3; var read=*reference; }" "while it is borrowed")
reject(stored_return_nested_field_lifetime "struct Reader<'a> { var source:&'a i32; } struct Nested<'a,'b> { var left:Reader<'a>; var right:Reader<'b>; } func wrong<'a,'b>(value:&Nested<'a,'b>)->&'a i32 { return value.right.source; } func main()->void {}" "declared result lifetime")
reject(stored_return_nested_projected_lifetime "struct Reader<'a> { var source:&'a i32; } struct Nested<'a,'b> { var left:Reader<'a>; var right:Reader<'b>; } func wrong<'a,'b>(value:&Nested<'a,'b>)->Reader<'a> { return Reader<'a>{source:value.right.source}; } func main()->void {}" "declared result lifetime")
reject(stored_return_enum_payload_lifetime "enum Pair<'a,'b> { Both(&'a i32,&'b i32), Empty } func wrong<'a,'b>(left:&'a i32,right:&'b i32)->Pair<'a,'b> { return Pair<'a,'b>.Both(right,left); } func main()->void {}" "declared result lifetime")
reject(stored_return_enum_pattern_lifetime "enum Pair<'a,'b> { Both(&'a i32,&'b i32), Empty } func wrong<'a,'b>(value:Pair<'a,'b>,fallback:&'a i32)->&'a i32 { match(value) { Both(left,right)=>return right; Empty=>return fallback; } } func main()->void {}" "declared result lifetime")
reject(stored_return_enum_reconstructed_lifetime "enum Pair<'a,'b> { Both(&'a i32,&'b i32), Empty } func wrong<'a,'b>(value:Pair<'a,'b>)->Pair<'a,'b> { match(value) { Both(left,right)=>return Pair<'a,'b>.Both(right,left); Empty=>return Pair<'a,'b>.Empty; } } func main()->void {}" "declared result lifetime")
reject(stored_enum_static_payload "enum Ref<'a> { Value(&'a i32), Empty } func main()->void { var source:i32=1; var value=Ref<'static>.Value(&source); }" "permanently live storage")
reject(stored_reborrow_union_left "func choose<'a>(left:&'a i32,right:&'a i32,first:bit)->&'a i32 { if(first) { return left; } return right; } func main()->void { var left:i32=1; var right:i32=2; var selected=choose(&left,&right,false); var child=&*selected; left=3; var read=*child; }" "while it is borrowed")
reject(stored_reborrow_union_right "func choose<'a>(left:&'a i32,right:&'a i32,first:bit)->&'a i32 { if(first) { return left; } return right; } func main()->void { var left:i32=1; var right:i32=2; var selected=choose(&left,&right,false); var child=&*selected; right=3; var read=*child; }" "while it is borrowed")
reject(stored_copy_reference_union "func choose<'a>(left:&'a i32,right:&'a i32,first:bit)->&'a i32 { if(first) { return left; } return right; } func main()->void { var left:i32=1; var right:i32=2; var selected=choose(&left,&right,false); var child=selected; right=3; var read=*child; }" "while it is borrowed")
reject(stored_nested_direct_reborrow "struct Reader<'a> { var source:&'a i32; } struct Nested<'a> { var reader:Reader<'a>; } func main()->void { var source:i32=1; var nested=Nested{reader:Reader{source:&source}}; var child=&*nested.reader.source; source=2; var read=*child; }" "while it is borrowed")
reject(stored_nested_copy_origin "struct Reader<'a> { var source:&'a i32; } struct Nested<'a> { var reader:Reader<'a>; } func main()->void { var source:i32=1; var nested=Nested{reader:Reader{source:&source}}; var copy=nested.reader; source=2; var read=*copy.source; }" "while it is borrowed")
reject(shared_reference_write "func change(value:&i32)->void { *value=2; } func main()->void {}" "mutable access through a shared checked reference")
reject(shared_reference_mutable_reborrow "func change(value:&i32)->void { var writable=&mut *value; *writable=2; } func main()->void {}" "mutable access through a shared checked reference")
reject(shared_reference_mutable_field "struct Writer<'a> { var source:&'a mut i32; } func change(value:&Writer)->void { var writable=value.source; *writable=2; } func main()->void {}" "mutable access through a shared checked reference")
reject(shared_reference_mutating_method "struct Value { var data:i32; func change()->void { data=2; } } func change(value:&Value)->void { value.change(); } func main()->void {}" "mutable access through a shared checked reference")
reject(shared_reference_mutable_getter "struct Value { var data:i32; func getMut()->&mut i32 { return &mut data; } } func change(value:&Value)->void { var writable=value.getMut(); *writable=2; } func main()->void {}" "mutable access through a shared checked reference")
reject(temporary_receiver_hidden_reborrow "struct Value { var data:i32; destructor {} func getRef()->&i32 { return &data; } } func main()->void { var reference=&*Value{data:1}.getRef(); var read=*reference; }" "named receiver")
reject(stored_return_parameter_field_conflict "struct Pair<'a,'b> { var left:&'a mut i32; var right:&'b mut i32; } func leftRef<'a,'b>(value:&Pair<'a,'b>)->&'a mut i32 { return value.left; } func main()->void { var left:i32=1; var right:i32=2; var pair=Pair{left:&mut left,right:&mut right}; var first=&*pair.left; var second=leftRef(&pair); var read=*first+*second; }" "Conflicting checked borrows")
reject(stored_return_outer_field_origin "struct Pair<'a> { var source:&'a i32; } func read<'a>(value:&'a Pair<'a>)->&'a i32 { return value.source; } func main()->void { var source:i32=1; var pair=Pair{source:&source}; var reference=read(&pair); source=2; var value=*reference; }" "while it is borrowed")
reject(call_borrow_later_mutation "func modify(value:&mut i32)->i32 { *value=2; return *value; } func use(value:&i32,other:i32)->i32 { return *value+other; } func main()->void { var source:i32=1; var result=use(&source,modify(&mut source)); }" "Conflicting checked borrows")
reject(call_borrow_multiple_origins "func choose<'a>(left:&'a mut i32,right:&'a mut i32,first:bit)->&'a mut i32 { if(first) { return left; } return right; } func use(left:&mut i32,right:&mut i32)->void { *left=1; *right=2; } func main()->void { var left:i32=1; var right:i32=2; use(choose(&mut left,&mut right,true),&mut left); }" "Conflicting checked borrows")
reject(call_borrow_nested_aggregate "struct Writer<'a> { var source:&'a mut i32; } func writer<'a>(source:&'a mut i32)->Writer<'a> { return Writer<'a>{source:source}; } func use(left:Writer,right:Writer)->void { *left.source=1; *right.source=2; } func main()->void { var source:i32=1; use(writer(&mut source),writer(&mut source)); }" "Conflicting checked borrows")
reject(enum_multiple_future_loans "enum Pair { Both(Future<i32>,Future<i32>), Empty } async func work(value:&i32)->i32 { return *value; } func main()->void { var left:i32=1; var right:i32=2; var first=work(&left); var second=work(&right); var pair=Pair.Both(first,second); left=3; match(pair) { Both(first,second)=>{ block_on(cancel(first)); block_on(cancel(second)); } Empty=>{} } }" "while it is borrowed")
reject(enum_remaining_future_loan "enum Pair { Both(Future<i32>,Future<i32>), Empty } async func work(value:&i32)->i32 { return *value; } func main()->void { var left:i32=1; var right:i32=2; var pair=Pair.Both(work(&left),work(&right)); match(pair) { Both(first,second)=>{ block_on(cancel(first)); right=3; block_on(cancel(second)); } Empty=>{} } }" "while it is borrowed")
reject(enum_shared_future_loan "enum Pair { Both(Future<i32>,Future<i32>), Empty } async func work(value:&i32)->i32 { return *value; } func main()->void { var source:i32=1; var pair=Pair.Both(work(&source),work(&source)); match(pair) { Both(first,second)=>{ block_on(cancel(first)); source=3; block_on(cancel(second)); } Empty=>{} } }" "while it is borrowed")
reject(enum_return_reordered_loans "enum Pair { Both(Future<i32>,Future<i32>), Empty } async func work(value:&i32)->i32 { return *value; } func swap(value:Pair)->Pair { match(value) { Both(first,second)=>return Pair.Both(second,first); Empty=>return Pair.Empty; } } func main()->void { var left:i32=1; var right:i32=2; var pair=swap(Pair.Both(work(&left),work(&right))); match(pair) { Both(first,second)=>{ block_on(cancel(first)); left=3; block_on(cancel(second)); } Empty=>{} } }" "while it is borrowed")
reject(stored_return_generic_field_lifetime "struct Pair<'a,'b,T> { var left:&'a T; var right:&'b T; } func wrong<'a,'b,T>(left:&'a T,right:&'b T)->Pair<'a,'b,T> { return Pair<'a,'b,T>{left:right,right:left}; } func main()->void { var left:i32=1; var right:i32=2; var value=wrong<i32>(&left,&right); }" "declared result lifetime")
reject(stored_borrow_branch "struct Reader<'a> { var source:&'a i32; } func choose()->bit { return true; } func main()->void { var x:i32=1; var y:i32=2; var r:Reader; if(choose()) { r=Reader{source:&x}; } else { r=Reader{source:&y}; } x=3; var z=*r.source; }" "borrow")
reject(stored_borrow_loop "struct Reader<'a> { var source:&'a i32; } func main()->void { var x:i32=1; var y:i32=2; var r=Reader{source:&x}; while(false) { r=Reader{source:&y}; } x=3; var z=*r.source; }" "borrow")
reject(stored_borrow_destructor "struct Guard<'a> { var source:&'a mut i32; destructor { *source=2; } } func main()->void { var x:i32=1; var guard=Guard{source:&mut x}; x=3; }" "borrow")
reject(stored_reborrow_delegation "struct Writer<'a> { pub var source:&'a mut i32; func write()->void { change(source); } } func change(value:&mut i32)->void { *value=2; } func main()->void { var x:i32=1; var w=Writer{source:&mut x}; var alias=&*w.source; w.write(); var z=*alias; }" "reborrow|borrow")
reject(stored_call_reborrow "struct Writer<'a> { pub var source:&'a mut i32; func write()->void { *source=2; } } func writer<'a>(value:&'a mut i32)->Writer<'a> { return Writer<'a>{source:value}; } func main()->void { var x:i32=1; var w=writer(&mut x); var alias=&*w.source; w.write(); var z=*alias; }" "reborrow|borrow")
reject(stored_reader_call_borrow "func main()->void { var storage:u8[4]; var bytes:u8[]=storage; var r=binary.borrowedReader(&bytes); bytes=slice(storage.data,0); var n=r.remaining(); }" "borrow")
reject(stored_writer_backing_borrow "func main()->void { var storage:u8[4]; var bytes:u8[]=storage; var w=binary.borrowedWriter(&mut bytes); storage[0]=1; var n=w.remaining(); }" "borrow")
reject(stored_borrow_self_reference "struct SelfRef<'a> { pub var value:i32; pub var source:&'a i32; } func main()->void { var x:i32=1; var r=SelfRef{value:2,source:&x}; r.source=&r.value; }" "Self-referential")
reject(mutex_guard_holds_owner "func main()->void { var result=sync.mutex(1); match(result) { Ok(mutex)=>{ var guard=sync.lock(&mutex); var moved=take(mutex); } Err(error)=>{} } }" "borrow")
reject(mutex_guard_not_send "func needsSend<T:core.Send>(value:T)->void {} func main()->void { var result=sync.mutex(1); match(result) { Ok(mutex)=>{ var guard=sync.lock(&mutex); needsSend(guard); } Err(error)=>{} } }" "No generic function")
reject(mutex_guard_borrow_conflict "func main()->void { var result=sync.mutex(1); match(result) { Ok(mutex)=>{ var guard=sync.lock(&mutex); var first=guard.getMut(); var second=guard.getMut(); var value=*first; } Err(error)=>{} } }" "borrow")
reject(mutex_guard_borrow_escape "func escape()->&i32 { var result=sync.mutex(1); match(result) { Ok(mutex)=>{ var guard=sync.lock(&mutex); return guard.getRef(); } Err(error)=>core.core_trap(); } } func main()->void {}" "borrow")

file(MAKE_DIRECTORY "${OUTPUT_DIR}/legacy")
file(WRITE "${OUTPUT_DIR}/legacy/dmm.manifest" "module gaps/legacy\ndmm 2026-09-22-dev\n")
file(WRITE "${OUTPUT_DIR}/legacy/case.dmm" "package main; func main()->void { var x=1; var y=take(x); }")
execute_process(COMMAND "${COMPILER}" -c "${OUTPUT_DIR}/legacy/case.dmm" -o "${OUTPUT_DIR}/legacy/case.o"
    RESULT_VARIABLE status ERROR_VARIABLE errors TIMEOUT 15)
if(status EQUAL 0 OR NOT errors MATCHES "require DMM 2026-10-04-dev")
    message(FATAL_ERROR "Lifetime syntax edition gate: ${status}: ${errors}")
endif()

reject(list_copy_owner "func main()->void { var values=stdlib.list<Resource>(0); values.push(Resource{value:1}); var copy=values.get(0); }" "No method overload")
reject(buffer_owner "func main()->void { var values=stdlib.buffer<Resource>(1); }" "core.Copy|interface bounds")
reject(list_move_argument "func main()->void { var values=stdlib.list<Resource>(0); var r:Resource; values.push(r); var value=r.value; }" "after ownership was moved")
reject(list_relocation_borrow "func main()->void { var values=stdlib.list<Resource>(0); values.push(Resource{value:1}); var reference=values.getRef(0); values.push(Resource{value:2}); var value=(*reference).value; }" "borrow")
reject(list_mutable_conflict "func main()->void { var values=stdlib.list<Resource>(0); values.push(Resource{value:1}); var reference=values.getMut(0); var second=values.getRef(0); (*reference).value=2; var value=(*second).value; }" "borrow")
reject(list_borrow_escape "func escape()->&Resource { var values=stdlib.list<Resource>(0); values.push(Resource{value:1}); return values.getRef(0); } func main()->void {}" "borrow|reference")
reject(list_stored_borrow "struct Reader<'a> { var source:&'a i32; } func main()->void { var source:i32=1; var values=stdlib.list<Reader>(0); values.push(Reader{source:&source}); source=2; var r=values.getRef(0); var v=*(*r).source; }" "borrow")
reject(map_relocation_borrow "func hash(key:i32)->u64 { return key.(u64); } func same(a:i32,b:i32)->bit { return a==b; } func main()->void { var values=collections.hashMap<i32,Resource>(hash,same); values.insert(1,Resource{value:1}); var key:i32=1; var reference=values.getRef(&key); values.insert(2,Resource{value:2}); match(reference) { Some(r)=>{ var v=(*r).value; } None=>{} } }" "borrow")
reject(map_mutable_conflict "func hash(key:i32)->u64 { return key.(u64); } func same(a:i32,b:i32)->bit { return a==b; } func main()->void { var values=collections.hashMap<i32,Resource>(hash,same); values.insert(1,Resource{value:1}); var key:i32=1; var reference=values.getMut(&key); var second=values.getRef(&key); match(reference) { Some(r)=>{ (*r).value=2; } None=>{} } match(second) { Some(r)=>{} None=>{} } }" "borrow")
reject(destroy_future "async func work()->i32 { return 1; } func main()->void { var f=work(); core.destroy<Future<i32>>(&f); }" "complete or cancel")
reject(closure_implicit_capture "func main()->void { var source:i32=1; var f=func [](x:i32)->i32 { return x+source; }; }" "Undefined variable 'source'")
reject(closure_move_capture "func main()->void { var source=Resource{value:1}; var f=func [move source](x:i32)->i32 { return x+source.value; }; var old=source.value; }" "after ownership was moved")
reject(closure_owner_double_call "func main()->void { var source=Resource{value:1}; var f=func [move source]()->Resource { return source; }; var first=f(); var second=f(); }" "after ownership was moved")
reject(closure_owner_double_capture_move "func main()->void { var source=Resource{value:1}; var f=func [move source]()->Resource { var first=source; return source; }; var item=f(); }" "after ownership was moved")
reject(closure_owner_shared_bound "func run(f:func()->Resource)->Resource { return f(); } func main()->void { var source=Resource{value:1}; var f=func [move source]()->Resource { return source; }; var item=run(f); }" "No overload")
reject(closure_owner_borrow_move "func main()->void { var source=Resource{value:1}; var f=func [move source]()->Resource { var loan=&source; var moved=source; var old=(*loan).value; return moved; }; var item=f(); }" "borrow")
reject(closure_future_obligation "async func work()->i32 { return 1; } func main()->void { var child=work(); var resume=func [move child]()->Future<i32> { return child; }; }" "live Future|consumption")
reject(closure_temporary_future_obligation "async func work()->i32 { return 1; } func main()->void { var child=work(); (func [move child]()->void {})(); }" "live Future")
reject(closure_deferred_future_loan "async func work(value:&i32)->i32 { return *value; } func main()->void { var source:i32=1; var child=work(&source); var finish=func [move child]()->void { block_on(cancel(child)); }; defer finish(); source=2; }" "borrow")
reject(temporary_receiver_borrow "struct OwnerValue { var value:i32; func getRef()->&i32 { return &value; } destructor {} } func main()->void { var reference=OwnerValue{value:1}.getRef(); var value=*reference; }" "named receiver")
reject(temporary_copy_receiver_borrow "struct Reader<'a> { var source:&'a i32; func getRef()->&'a i32 { return source; } } func main()->void { var source:i32=1; var reference=Reader{source:&source}.getRef(); source=2; var value=*reference; }" "named receiver")
reject(closure_future_live_loan "async func work(source:&i32)->i32 { return *source; } func main()->void { var source:i32=1; var child=work(&source); var resume=func [move child]()->Future<i32> { return child; }; var transferred=resume(); source=2; var value=block_on(transferred); }" "borrow")
reject(closure_implicit_field_take "struct OwnerField { var resource:Resource; func steal()->Resource { return take(resource); } } func main()->void {}" "partial lifetimes")
reject(closure_borrow_escape "func escape()->func(i32)->i32 { var source:i32=1; return func [&source](x:i32)->i32 { return x+source; }; } func main()->void {}" "cannot capture a borrow of a local")
reject(closure_mutable_mode "func apply(f:func(i32)->i32,x:i32)->i32 { return f(x); } func main()->void { var source:i32=1; var f=func [&mut source](x:i32)->i32 { source+=x; return source; }; var value=apply(f,2); }" "No overload")
reject(closure_duplicate_capture "func main()->void { var source:i32=1; var f=func [move source,move source](x:i32)->i32 { return x+source; }; }" "already defined|Duplicate field")
reject(closure_mutable_borrow_conflict "func main()->void { var source:i32=1; var f=func [&mut source](x:i32)->i32 { source+=x; return source; }; source=2; var value=f(3); }" "while it is borrowed")
reject(closure_mutable_alias "func main()->void { var source:i32=1; var f=func [&mut source](x:i32)->i32 { source+=x; return source; }; var alias=&mut source; var value=f(3)+*alias; }" "Conflicting checked borrows")
reject(closure_mutable_move "func main()->void { var source:i32=1; var f=func [&mut source](x:i32)->i32 { source+=x; return source; }; var moved=f; var value=f(2); }" "after ownership was moved")
reject(once_double_call "func consume(f:once func()->i32)->i32 { var first=f(); return first+f(); } func main()->void {}" "after ownership was moved")
reject(once_alias "func consume(f:once func()->i32)->i32 { var alias=f; return alias()+f(); } func main()->void {}" "after ownership was moved")
reject(once_branch_call "func consume(f:once func()->i32,condition:bit)->i32 { if(condition) { var first=f(); } return f(); } func main()->void {}" "after ownership was moved")
reject(once_loop_call "func consume(f:once func()->i32)->void { while(true) { var value=f(); } } func main()->void {}" "more than once")
reject(once_inferred_loop_call "func consume(f:once func()->i32)->void { var moved=f; while(true) { var value=moved(); } } func main()->void {}" "more than once")
reject(once_inferred_self_assignment "func consume(f:once func()->i32)->void { var moved=f; moved=moved; } func main()->void {}" "into itself")
reject(once_annotated_closure "func main()->void { var source:i32=1; var f:once func()->i32=func [move source]()->i32 { return source; }; var first=f(); var second=f(); }" "after ownership was moved")
reject(once_annotated_closure_loop "func main()->void { var source:i32=1; var f:once func()->i32=func [move source]()->i32 { return source; }; var moved=f; while(true) { var value=moved(); } }" "more than once")
reject(once_weaken "func twice(f:func()->i32)->i32 { return f()+f(); } func consume(f:once func()->i32)->i32 { return twice(f); } func main()->void {}" "No overload")
reject(once_copy_bound "func need<T:core.Copy>(value:T)->void {} func consume(f:once func()->i32)->void { need(f); } func main()->void {}" "No generic function|Function 'need' not found")
reject(once_borrowed_call "func consume(f:once func()->i32)->i32 { var loan=&f; var value=f(); var old=*loan; return value; } func main()->void {}" "borrow")
reject(once_reference_call "func consume(f:&once func()->i32)->i32 { return f()+f(); } func main()->void {}" "owned value")
reject(once_dereference_call "func consume(f:&once func()->i32)->i32 { return (*f)()+(*f)(); } func main()->void {}" "checked reference")
reject(once_reference_copy "func consume(f:&once func()->i32)->i32 { var copy=*f; return copy(); } func main()->void {}" "checked reference")
reject(once_closure_double_call "func twice(f:once func()->i32)->i32 { var first=f(); return first+f(); } func main()->void { var source:i32=1; var f=func [move source]()->i32 { return source; }; var value=twice(f); }" "after ownership was moved")
reject(once_closure_weaken "func twice(f:func()->i32)->i32 { return f()+f(); } func consume(f:once func()->i32)->i32 { return twice(f); } func main()->void { var source:i32=1; var f=func [move source]()->i32 { return source; }; var value=consume(f); }" "No overload")
reject(closure_native_callback "func accept(f:extern \"system\" func(i32)->i32)->void {} func main()->void { var value:i32=1; var f=func [move value](x:i32)->i32 { return x+value; }; accept(f); }" "No overload")
reject(interface_borrow_mode "interface Mutate { func update(value:&mut i32)->void; } struct Bad { func update(value:&i32)->void {} } func need<T:Mutate>(value:T)->void {} func main()->void { var bad:Bad; need(bad); }" "Function 'need' not found")
reject(interface_callable_mode "interface Repeat { func run(callback:func()->i32)->i32; } struct Bad { func run(callback:once func()->i32)->i32 { return callback(); } } func need<T:Repeat>(value:T)->void {} func main()->void { var bad:Bad; need(bad); }" "Function 'need' not found")
reject(interface_callable_argument "interface Invoke { func run(callback:once func(i32)->i32)->i32; } struct Bad { func run(callback:once func(i64)->i32)->i32 { return callback(1); } } func need<T:Invoke>(value:T)->void {} func main()->void { var bad:Bad; need(bad); }" "Function 'need' not found")
reject(interface_callable_result "interface Invoke { func run(callback:once func()->i32)->i32; } struct Bad { func run(callback:once func()->i64)->i32 { return callback().(i32); } } func need<T:Invoke>(value:T)->void {} func main()->void { var bad:Bad; need(bad); }" "Function 'need' not found")

file(MAKE_DIRECTORY "${OUTPUT_DIR}/waker_forge")
file(WRITE "${OUTPUT_DIR}/waker_forge/dmm.manifest" "module gaps/waker_forge\ndmm 2026-10-04-dev\nfeatures = [\"async\"]\n")
file(WRITE "${OUTPUT_DIR}/waker_forge/case.dmm" "package main; import (\"stdlib/async\" \"stdlib/core\"); func main()->void { var forged=asynchronous.Waker{raw:core.core_null().(*void)}; forged.wake(); }")
execute_process(COMMAND "${COMPILER}" -c "${OUTPUT_DIR}/waker_forge/case.dmm" -o "${OUTPUT_DIR}/waker_forge/case.o"
    RESULT_VARIABLE status ERROR_VARIABLE errors TIMEOUT 15)
if(status EQUAL 0 OR NOT errors MATCHES "Member is private to its defining package")
    message(FATAL_ERROR "Waker constructor privacy: ${status}: ${errors}")
endif()

function(reexport_reject name facade body expected edition)
    set(work "${OUTPUT_DIR}/${name}")
    file(MAKE_DIRECTORY "${work}/leaf" "${work}/other" "${work}/facade")
    file(WRITE "${work}/dmm.manifest" "module gaps/${name}\ndmm ${edition}\n")
    file(WRITE "${work}/leaf/leaf.dmm" "package leaf; pub func answer()->i32 { return 1; } func hidden()->i32 { return 2; }\n")
    file(WRITE "${work}/other/other.dmm" "package other; pub func answer()->i32 { return 3; }\n")
    file(WRITE "${work}/facade/facade.dmm" "package facade; ${facade}\n")
    file(WRITE "${work}/case.dmm" "package main; import (\"gaps/${name}/facade\"); ${body}\n")
    execute_process(COMMAND "${COMPILER}" --emit=obj "${work}/case.dmm" -o "${work}/case.o"
        RESULT_VARIABLE status ERROR_VARIABLE errors TIMEOUT 15)
    if(status EQUAL 0 OR NOT errors MATCHES "${expected}")
        message(FATAL_ERROR "Expected rejection ${name} (${expected}): ${status}: ${errors}")
    endif()
endfunction()
reexport_reject(reexport_collision "pub import (\"gaps/reexport_collision/leaf\" \"gaps/reexport_collision/other\");" "func main()->void {}" "Public reexport name" "2026-10-04-dev")
reexport_reject(reexport_private "pub import (\"gaps/reexport_private/leaf\");" "func main()->i32 { return facade.hidden(); }" "private|not found|No overload" "2026-10-04-dev")
reexport_reject(reexport_legacy "pub import (\"gaps/reexport_legacy/leaf\");" "func main()->void {}" "2026-10-04-dev" "2026-09-22-dev")

reexport_reject(lifetime_legacy "pub struct Reader<'a> { var source:&'a i32; }" "func main()->void {}" "2026-10-04-dev" "2026-09-22-dev")
reexport_reject(where_legacy "pub struct Cell<T> { var value:T; func get()->T where T:Copy { return value; } } auto interface Copy {}" "func main()->void {}" "2026-10-04-dev" "2026-09-22-dev")
file(MAKE_DIRECTORY "${OUTPUT_DIR}/closure_legacy")
file(WRITE "${OUTPUT_DIR}/closure_legacy/dmm.manifest" "module gaps/closure_legacy\ndmm 2026-09-22-dev\n")
file(WRITE "${OUTPUT_DIR}/closure_legacy/case.dmm" "package main; func main()->int { var source:i32=1; var f=func [move source](x:i32)->i32 { return x+source; }; return f(2); }")
execute_process(COMMAND "${COMPILER}" -c "${OUTPUT_DIR}/closure_legacy/case.dmm" -o "${OUTPUT_DIR}/closure_legacy/case.o"
    RESULT_VARIABLE status ERROR_VARIABLE errors TIMEOUT 15)
if(status EQUAL 0 OR NOT errors MATCHES "Capturing closures and callable modes require DMM 2026-10-04-dev")
    message(FATAL_ERROR "Closure edition gate: ${status}: ${errors}")
endif()
