cmake_minimum_required(VERSION 3.21)
# Removed stdlib source files must not survive from an older test installation.
string(TIMESTAMP installation_id "%Y%m%d%H%M%S" UTC)
set(work "${OUTPUT_DIR}/stdlib packages/${installation_id}")
file(MAKE_DIRECTORY "${work}/bin")
get_filename_component(compiler_name "${COMPILER}" NAME)
file(COPY_FILE "${COMPILER}" "${work}/bin/${compiler_name}")
file(COPY "${SOURCE_DIR}/stdlib" DESTINATION "${work}/share/dmm")
set(compiler "${work}/bin/${compiler_name}")
if(EXISTS "${work}/bin/dmm-runtime")
    message(FATAL_ERROR "The isolated stdlib-package installation must contain no bundle")
endif()
if(WIN32)
    set(host coff)
    set(libraries -lws2_32 -lucrt -lbcrypt)
    set(link_flags -Wl,--subsystem,console)
else()
    set(host elf)
    set(libraries -pthread -lm)
    set(link_flags -no-pie)
endif()
foreach(case executor loopback lifecycle system)
    set(directory "${work}/${case}")
    file(MAKE_DIRECTORY "${directory}")
    file(WRITE "${directory}/dmm.manifest" "module runtime.source/${case}\ndmm 2026-09-22-dev\nfeatures = [\"async\"]\n")
    if(case STREQUAL executor)
        set(source "${SOURCE_DIR}/tests/async/executor.dmm")
    elseif(case STREQUAL system)
        set(source "${SOURCE_DIR}/tests/stdlib/system/stdlib_system.dmm")
    else()
        set(source "${SOURCE_DIR}/tests/network/${case}.dmm")
    endif()
    file(COPY_FILE "${source}" "${directory}/main.dmm")
    foreach(level 0 1)
        foreach(emit exe obj asm)
            set(artifact "${directory}/program_${level}_${emit}")
            execute_process(COMMAND "${compiler}" "-O${level}" "--emit=${emit}"
                --linker-driver "${ASSEMBLER}" --dump-tokens "${artifact}.tokens"
                --dump-native-link "${artifact}.link" "${directory}/main.dmm" -o "${artifact}"
                RESULT_VARIABLE status ERROR_VARIABLE errors TIMEOUT 45)
            if(NOT status EQUAL 0)
                message(FATAL_ERROR "Stdlib packages ${case}/${level}/${emit}: ${errors}")
            endif()
            file(READ "${artifact}.tokens" tokens)
            if(case STREQUAL system)
                set(installed_source "share/dmm/stdlib/fs/fs.dmm")
            else()
                set(installed_source "share/dmm/stdlib/internal/executor/executor.dmm")
            endif()
            if(NOT tokens MATCHES "${installed_source}")
                message(FATAL_ERROR "Installed compiler did not load installed stdlib source")
            endif()
            file(READ "${artifact}.link" inventory)
            if(inventory MATCHES "library=\"dmm_network\"|symbol=\"__dmm_(async|net)_")
                message(FATAL_ERROR "DMM package call became a foreign stdlib dependency: ${inventory}")
            endif()
            set(program "${artifact}")
            if(NOT emit STREQUAL exe)
                if(emit STREQUAL asm)
                    set(language -x assembler)
                else()
                    set(language -x none)
                endif()
                set(program "${artifact}.exe")
                execute_process(COMMAND "${ASSEMBLER}" ${language} "${artifact}" -x none ${link_flags} ${libraries} -o "${program}"
                    RESULT_VARIABLE status ERROR_VARIABLE errors TIMEOUT 30)
                if(NOT status EQUAL 0)
                    message(FATAL_ERROR "Manual source-only runtime link: ${errors}")
                endif()
            endif()
            execute_process(COMMAND "${program}" WORKING_DIRECTORY "${directory}" RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE errors TIMEOUT 20)
            if(case STREQUAL lifecycle)
                set(expected 17)
            else()
                set(expected 0)
            endif()
            if(NOT status EQUAL expected)
                message(FATAL_ERROR "Stdlib packages execution ${case}/${level}/${emit}: ${status} ${output} ${errors}")
            endif()
        endforeach()
    endforeach()
endforeach()
# Merely loading the provider or a network import must not require a platform linker.
file(MAKE_DIRECTORY "${work}/unused")
file(WRITE "${work}/unused/dmm.manifest" "module runtime.source/unused\ndmm 2026-09-22-dev\nfeatures = [\"async\"]\n")
file(WRITE "${work}/unused/main.dmm" "package main; import \"stdlib/net/raw\"; func main()->int { return 0; }\n")
execute_process(COMMAND "${compiler}" --link=internal "${work}/unused/main.dmm" -o "${work}/unused.exe"
    RESULT_VARIABLE status ERROR_VARIABLE errors TIMEOUT 30)
if(NOT status EQUAL 0)
    message(FATAL_ERROR "Unused source provider changes standalone linking: ${errors}")
endif()
