cmake_minimum_required(VERSION 3.21)
file(MAKE_DIRECTORY "${OUTPUT_DIR}")
set(fixture "${SOURCE_DIR}/tests/stdlib/language_algorithms_borrowed/language_algorithms_borrowed.dmm")
foreach(level 0 1)
    set(program "${OUTPUT_DIR}/borrowed_${level}.exe")
    execute_process(COMMAND "${COMPILER}" "-O${level}" --emit=exe "${fixture}" -o "${program}"
        RESULT_VARIABLE status ERROR_VARIABLE errors TIMEOUT 60)
    if(NOT status EQUAL 0)
        message(FATAL_ERROR "Borrowed algorithms O${level}: ${errors}")
    endif()
    execute_process(COMMAND "${program}" RESULT_VARIABLE status TIMEOUT 15)
    if(NOT status EQUAL 0)
        message(FATAL_ERROR "Borrowed algorithms O${level} execution: ${status}")
    endif()
    foreach(target elf coff)
        foreach(mode obj intel att)
            set(options --emit=obj)
            if(NOT mode STREQUAL obj)
                set(options --emit=asm "--syntax=${mode}")
            endif()
            execute_process(COMMAND "${COMPILER}" "-O${level}" "--target=${target}" ${options}
                "${fixture}" -o "${OUTPUT_DIR}/${target}_${level}_${mode}.out"
                RESULT_VARIABLE status ERROR_VARIABLE errors TIMEOUT 30)
            if(NOT status EQUAL 0)
                message(FATAL_ERROR "Borrowed algorithms ${target}/O${level}/${mode}: ${errors}")
            endif()
        endforeach()
    endforeach()
endforeach()

function(reject name body expected)
    set(work "${OUTPUT_DIR}/${name}")
    file(MAKE_DIRECTORY "${work}")
    file(WRITE "${work}/dmm.manifest" "module borrowed/${name}\ndmm 2026-10-04-dev\n")
    file(WRITE "${work}/main.dmm" "package main; import (stdlib \"stdlib/core\" \"stdlib/algorithms\"); struct Resource { var value:i32; destructor {} } ${body}\n")
    execute_process(COMMAND "${COMPILER}" --emit=obj "${work}/main.dmm" -o "${work}/main.o"
        RESULT_VARIABLE status ERROR_VARIABLE errors TIMEOUT 15)
    if(status EQUAL 0 OR NOT errors MATCHES "${expected}")
        message(FATAL_ERROR "Expected rejection ${name} (${expected}): ${status}: ${errors}")
    endif()
endfunction()
set(storage "var storage:Resource[2]=[Resource{value:1},Resource{value:2}]; var view:Resource[]=storage;")
reject(shared_mutation "func change(value:&Resource)->bit { (*value).value+=1; return true; } func main()->void { ${storage} algorithms.any(&view,change); }" "borrow|mutable|shared")
reject(shared_consumption "func steal(value:&Resource)->bit { var owner=*value; return owner.value>0; } func main()->void { ${storage} algorithms.any(&view,steal); }" "consum|reference|borrow")
reject(mutable_shared_view "func change(value:&mut Resource)->void { (*value).value+=1; } func main()->void { ${storage} var shared=&view; algorithms.forEachMut(shared,change); }" "convert|mutable|borrow")
reject(live_element "func change(value:&mut Resource)->void { (*value).value+=1; } func main()->void { ${storage} var element=&view[0]; algorithms.forEachMut(&mut view,change); var read=(*element).value; }" "borrow")
reject(view_retains_array "func consume(values:Resource[2])->void {} func main()->void { ${storage} consume(storage); var read=view[0].value; }" "borrow")
reject(overload_still_consumes "func consume(values:Resource[2])->void {} func consume(values:Resource[])->void {} func main()->void { var storage:Resource[2]=[Resource{value:1},Resource{value:2}]; consume(storage); var read=storage[0].value; }" "moved|consum")
reject(local_view_escape "func escape()->Resource[] { var storage:Resource[2]=[Resource{value:1},Resource{value:2}]; return storage; } func main()->void { var view=escape(); var read=view[0].value; }" "local|scope|escape|borrow")
reject(local_field_escape "struct View { var values:Resource[]; } func escape()->View { var storage:Resource[2]=[Resource{value:1},Resource{value:2}]; return View{values:storage}; } func main()->void { var view=escape(); var read=view.values[0].value; }" "local|scope|escape|borrow")
reject(local_named_field_escape "struct View { var values:Resource[]; } func escape()->View { var storage:Resource[2]=[Resource{value:1},Resource{value:2}]; var result=View{values:storage}; return result; } func main()->void { var view=escape(); var read=view.values[0].value; }" "local|scope|escape|borrow")
reject(once_predicate "func main()->void { ${storage} var owner=Resource{value:1}; var predicate=func [move owner](value:&Resource)->bit { var taken=owner; return taken.value==(*value).value; }; algorithms.any(&view,predicate); }" "once|callable|convert|type")
