cmake_minimum_required(VERSION 3.21)
file(MAKE_DIRECTORY "${OUTPUT_DIR}")
if(WIN32)
    set(libraries -lkernel32 -lucrt -lbcrypt)
    set(flags -Wl,--subsystem,console)
else()
    set(libraries -lm -pthread)
    set(flags -no-pie)
endif()
foreach(level 0 1)
    foreach(mode exe intel att obj)
        set(work "${OUTPUT_DIR}/system_${level}_${mode}")
        file(MAKE_DIRECTORY "${work}")
        set(program "${work}/program.exe")
        if(mode STREQUAL exe)
            set(options --emit=exe)
            set(artifact "${program}")
        elseif(mode STREQUAL obj)
            set(options --emit=obj)
            set(artifact "${work}/program.o")
        else()
            set(options --emit=asm "--syntax=${mode}")
            set(artifact "${work}/program.s")
        endif()
        execute_process(COMMAND "${COMPILER}" "-O${level}" ${options} --linker-driver "${ASSEMBLER}"
            "${SOURCE_DIR}/tests/stdlib/system/stdlib_system.dmm" -o "${artifact}"
            RESULT_VARIABLE status ERROR_VARIABLE errors TIMEOUT 60)
        if(NOT status EQUAL 0)
            message(FATAL_ERROR "System stdlib ${level}/${mode}: ${errors}")
        endif()
        if(NOT mode STREQUAL exe)
            execute_process(COMMAND "${ASSEMBLER}" "${artifact}" ${flags} ${libraries} -o "${program}"
                RESULT_VARIABLE status ERROR_VARIABLE errors TIMEOUT 30)
            if(NOT status EQUAL 0)
                message(FATAL_ERROR "System stdlib link ${level}/${mode}: ${errors}")
            endif()
        endif()
        execute_process(COMMAND "${program}" WORKING_DIRECTORY "${work}"
            RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE errors TIMEOUT 30)
        if(NOT status EQUAL 0 OR NOT output STREQUAL "" OR NOT errors STREQUAL "")
            message(FATAL_ERROR "System stdlib execution ${level}/${mode}: ${status} ${output} ${errors}")
        endif()
    endforeach()
endforeach()
# The same public import selects exactly one implementation for each target.
foreach(target elf coff)
    if(target STREQUAL elf)
        set(selected fs_linux.dmm)
        set(excluded fs_windows.dmm)
    else()
        set(selected fs_windows.dmm)
        set(excluded fs_linux.dmm)
    endif()
    foreach(level 0 1)
        set(artifact "${OUTPUT_DIR}/system_${target}_${level}.o")
        execute_process(COMMAND "${COMPILER}" --emit=obj "--target=${target}" "-O${level}"
            --dump-tokens "${artifact}.tokens" "${SOURCE_DIR}/tests/stdlib/system/stdlib_system.dmm" -o "${artifact}"
            RESULT_VARIABLE status ERROR_VARIABLE errors TIMEOUT 60)
        if(NOT status EQUAL 0)
            message(FATAL_ERROR "Target-selected stdlib ${target}/O${level}: ${errors}")
        endif()
        file(READ "${artifact}.tokens" tokens)
        if(NOT tokens MATCHES "${selected}" OR tokens MATCHES "${excluded}")
            message(FATAL_ERROR "Public fs import selected the wrong target implementation")
        endif()
    endforeach()
endforeach()
