cmake_minimum_required(VERSION 3.21)
include("${CMAKE_CURRENT_LIST_DIR}/source_fixture.cmake")
set(work "${OUTPUT_DIR}/struct_initializers")
file(MAKE_DIRECTORY "${work}")
set(fixture "${CMAKE_CURRENT_LIST_DIR}/execution/structs/named_initializers")
file(COPY "${fixture}/dmm.manifest" DESTINATION "${work}")
file(COPY_FILE "${fixture}/named_initializers.dmm" "${work}/main.dmm")
file(READ "${fixture}/named_initializers.expected" expected)
if(CMAKE_HOST_WIN32)
    set(host_target coff)
else()
    set(host_target elf)
endif()
foreach(target elf coff)
    foreach(level 0 1)
        foreach(syntax intel att)
            set(output "${work}/${target}_${level}_${syntax}")
            execute_process(COMMAND "${COMPILER}" "--target=${target}" "-O${level}" "--syntax=${syntax}"
                --emit=asm --dump-ast "${output}.ast" --dump-ir "${output}.ir" -o "${output}.s" "${work}/main.dmm"
                RESULT_VARIABLE result ERROR_VARIABLE errors TIMEOUT 30)
            if(NOT result EQUAL 0)
                message(FATAL_ERROR "Struct initializer lowering failed (${target}/${level}/${syntax}): ${errors}")
            endif()
            file(READ "${output}.ast" ast)
            file(READ "${output}.ir" ir)
            if(NOT ast MATCHES "dmm-ast-v6" OR NOT ast MATCHES "struct-literal" OR
               NOT ast MATCHES "initializer-field=\"x\"" OR
               NOT ir MATCHES "dmm-ir-v6" OR NOT ir MATCHES "opcode=struct-literal")
                message(FATAL_ERROR "Struct initializer dump metadata is missing")
            endif()
            if(target STREQUAL host_target)
                execute_process(COMMAND "${COMPILER}" "--target=${target}" "-O${level}" "--syntax=${syntax}"
                    --emit=exe -o "${output}.exe" "${work}/main.dmm"
                    RESULT_VARIABLE result ERROR_VARIABLE errors TIMEOUT 30)
                if(NOT result EQUAL 0)
                    message(FATAL_ERROR "Struct initializer executable failed: ${errors}")
                endif()
                execute_process(COMMAND "${output}.exe" RESULT_VARIABLE result OUTPUT_VARIABLE actual TIMEOUT 15)
                string(REPLACE "\r\n" "\n" actual "${actual}")
                if(NOT result EQUAL 0 OR NOT actual STREQUAL expected)
                    message(FATAL_ERROR "Struct initializer execution failed (${level}/${syntax}): ${actual}")
                endif()
            endif()
        endforeach()
    endforeach()
endforeach()

function(reject name source diagnostic)
    dmm_test_write("${work}/main.dmm" "${source}")
    foreach(target elf coff)
        execute_process(COMMAND "${COMPILER}" --ide "--target=${target}" --formatError "${work}/main.dmm"
            --dump-ast "${work}/${name}_${target}.ast"
            RESULT_VARIABLE result ERROR_VARIABLE errors TIMEOUT 20)
        if(result EQUAL 0 OR NOT errors MATCHES "${diagnostic}")
            message(FATAL_ERROR "${name}/${target} was not rejected correctly: ${errors}")
        endif()
    endforeach()
endfunction()
set(pair "struct Pair { var x:int; var y:int; } ")
reject(missing "${pair}func main() -> int { var p = Pair{x: 1}; return 0; }" "Missing field")
reject(duplicate "${pair}func main() -> int { var p = Pair{x: 1, x: 2, y: 3}; return 0; }" "Duplicate field")
reject(unknown "${pair}func main() -> int { var p = Pair{x: 1, y: 2, z: 3}; return 0; }" "Unknown field")
reject(wrong_type "${pair}func main() -> int { var p = Pair{x: \"bad\", y: 2}; return 0; }" "incompatible with its field type")
reject(unknown_type "func main() -> int { var p = Missing{x: 1}; return 0; }" "complete struct value type")
reject(opaque "extern \"system\" { struct Opaque; } func main() -> int { var p = Opaque{}; return 0; }" "complete struct value type")
reject(enum "enum E { A } func main() -> int { var p = E{}; return 0; }" "complete struct value type")
reject(union_empty "extern \"system\" { union U { pub var x:i32; pub var y:double; } } func main() -> int { var p = U{}; return 0; }" "exactly one field")
reject(union_multiple "extern \"system\" { union U { pub var x:i32; pub var y:double; } } func main() -> int { var p = U{x: 1, y: 2.0}; return 0; }" "exactly one field")
reject(move_twice "struct R { var n:int; destructor {} } struct P { var a:R; var b:R; } func main() -> int { var r = R{n: 1}; var p = P{a: r, b: r}; return 0; }" "ownership was moved")
reject(slice_owner "struct H { var view:int[]; } func main() -> int { var h = H{view: [1, 2]}; return 0; }" "bind temporary slice backing")
reject(slice_alias "struct H { var view:int[]; } func main() -> int { var owner:int[] = [1, 2]; var h = H{view: owner}; owner = [3, 4]; return h.view[0]; }" "borrow")
reject(array_view "struct H { var view:int[]; } func main() -> int { var owner:int[2] = [1, 2]; var h = H{view: owner}; owner = [3, 4]; return h.view[0]; }" "borrow")
reject(borrowed_move "struct R { var n:int; destructor {} } struct H { var r:R; } func main() -> int { var r = R{n: 1}; var loan = &r; var h = H{r: r}; return loan.n; }" "borrow")
file(MAKE_DIRECTORY "${work}/types")
dmm_test_write("${work}/types/types.dmm" "package types; pub struct Public { pub var x:int; var hidden:int; } struct Private { pub var x:int; }")
reject(private_field "import \"dmm.test/named_initializers/types\"; func main() -> int { var p = types.Public{x: 1, hidden: 2}; return 0; }" "private to its defining package")
reject(private_type "import \"dmm.test/named_initializers/types\"; func main() -> int { var p = types.Private{x: 1}; return 0; }" "private to its defining package")
dmm_test_write("${work}/types/types.dmm" "package types; pub struct Pair { pub var x:int; pub var values:int[2]; } pub struct Box<T> { pub var value:T; }")
dmm_test_write("${work}/main.dmm" "import \"dmm.test/named_initializers/types\"; func main() -> int { var p = types.Pair{values: [2, 3], x: 1}; var b = types.Box<types.Pair>{value: p}; return b.value.values[1] - 3; }")
execute_process(COMMAND "${COMPILER}" --emit=exe -O1 -o "${work}/imported.exe" "${work}/main.dmm"
    RESULT_VARIABLE result ERROR_VARIABLE errors TIMEOUT 30)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "Imported struct initializer failed: ${errors}")
endif()
execute_process(COMMAND "${work}/imported.exe" RESULT_VARIABLE result TIMEOUT 15)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "Imported struct initializer produced wrong values")
endif()

file(APPEND "${work}/dmm.manifest" "features = [\"async\"]\n")
dmm_test_write("${work}/main.dmm"
    "import \"stdlib\"; struct R { var n:int; destructor { stdlib.println(n); } } struct H { var r:R; var n:int; }\n"
    "async func number() -> int { return 5; } async func run() -> int { var h = H{r: R{n: 101}, n: number().await()}; return h.n - 5; }\n"
    "func main() -> int { return block_on(run()); }\n")
foreach(level 0 1)
    execute_process(COMMAND "${COMPILER}" "-O${level}" --emit=exe -o "${work}/async_${level}.exe" "${work}/main.dmm"
        RESULT_VARIABLE result ERROR_VARIABLE errors TIMEOUT 30)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "Async struct initializer failed: ${errors}")
    endif()
    execute_process(COMMAND "${work}/async_${level}.exe" RESULT_VARIABLE result OUTPUT_VARIABLE actual TIMEOUT 15)
    string(REPLACE "\r\n" "\n" actual "${actual}")
    if(NOT result EQUAL 0 OR NOT actual STREQUAL "101\n")
        message(FATAL_ERROR "Async struct initializer/destruction failed: ${actual}")
    endif()
endforeach()
