#include "backend.h"

#include "asm_optimizer.h"
#include "errorHandler.h"
#include "parser.h"

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

static TokenStream *ast_token_stream(const AstProgram *program) {
    if (program->token_count > (size_t) INT32_MAX ||
        program->token_count > SIZE_MAX / sizeof(Token)) return NULL;
    TokenStream *stream = calloc(1, sizeof(*stream));
    if (stream == NULL) return NULL;
    stream->tokens = calloc(program->token_count, sizeof(*stream->tokens));
    if (stream->tokens == NULL && program->token_count != 0) {
        free(stream);
        return NULL;
    }
    stream->count = (int) program->token_count;
    stream->capacity = stream->count;
    for (size_t i = 0; i < program->token_count; i++) {
        stream->tokens[i].type = program->tokens[i].type;
        memcpy(stream->tokens[i].value, program->tokens[i].lexeme, MAX_TOKEN);
        stream->tokens[i].line = program->tokens[i].span.begin.line;
        stream->tokens[i].column = program->tokens[i].span.begin.column;
    }
    return stream;
}

static void destroy_token_stream(TokenStream *stream) {
    if (stream == NULL) return;
    free(stream->tokens);
    free(stream);
}

static void write_escaped_string(FILE *output, const char *text) {
    for (size_t i = 0; text[i] != '\0'; i++) {
        unsigned char c = (unsigned char) text[i];
        switch (c) {
            case '\n': fputs("\\n", output); break;
            case '\t': fputs("\\t", output); break;
            case '\r': fputs("\\r", output); break;
            case '\\': fputs("\\\\", output); break;
            case '"': fputs("\\\"", output); break;
            default:
                if (c >= 32 && c < 127) fputc(c, output);
                else fprintf(output, "\\%03o", c);
        }
    }
}

static int report_output_error(const AstProgram *program, const char *message,
                               const char *output_path) {
    error_report(global_error_handler, SEVERITY_ERROR, 0, 0, ERROR_CATEGORY_CODEGEN,
                 ERR_CODEGEN_OUTPUT_FAILED, program->source_path, message, output_path);
    return 0;
}

static int write_assembly(const AstProgram *program, const Parser *parser,
                          const BackendOptions *options, const char *output_path) {
    FILE *output = fopen(output_path, "w");
    if (output == NULL) return report_output_error(program, "Could not create output file '%s'", output_path);

    time_t now = time(NULL);
    struct tm *local = localtime(&now);
    char datetime[64] = "unknown";
    if (local != NULL) (void) strftime(datetime, sizeof(datetime), "%Y-%m-%d %H:%M:%S", local);

    fprintf(output, "# Generated by Philipp01105's Compiler\n");
    fprintf(output, "# Source: %s\n", program->source_path);
    if (!options->deterministic) fprintf(output, "# Date: %s\n", datetime);
    fprintf(output, "# Target Format: %s\n", options->target_format == TARGET_COFF ? "COFF" : "ELF");
    fprintf(output, "# Syntax: %s\n", options->syntax_mode == SYNTAX_INTEL ? "Intel" : "AT&T");
    if (options->syntax_mode == SYNTAX_INTEL) fprintf(output, "    .intel_syntax noprefix\n");
    fprintf(output, "    .text\n");

    if (options->target_format == TARGET_COFF) {
        fprintf(output, "    .def    printf; .scl    2; .type   32; .endef\n");
        fprintf(output, "    .def    putchar; .scl    2; .type   32; .endef\n");
        fprintf(output, "    .section .rdata,\"dr\"\n");
    } else {
        fprintf(output, "    .section .rodata\n");
    }

    fputs(".LC_int_format:\n    .ascii \"%d\\0\"\n", output);
    fputs(".LC_float_format:\n    .ascii \"%f\\0\"\n", output);
    fputs(".LC_double_format:\n    .ascii \"%lf\\0\"\n", output);
    fputs(".LC_char_format:\n    .ascii \"%c\\0\"\n", output);
    fputs(".LC_char_input_format:\n    .ascii \" %c\\0\"\n", output);
    fputs(".LC_string_format:\n    .ascii \"%s\\0\"\n", output);
    fputs(".LC_pointer_format:\n    .ascii \"%p\\0\"\n", output);
    fputs(".LC_string_input_format:\n    .ascii \"%255[^\\n]\\0\"\n", output);
    fputs(".LC_newline:\n    .ascii \"\\n\\0\"\n\n", output);

    if (parser->string_literal_count > 0) {
        fputs("# String literals\n", output);
        for (int i = 0; i < parser->string_literal_count; i++) {
            fprintf(output, ".LC%d:\n    .ascii \"", parser->string_literals[i].id);
            write_escaped_string(output, parser->string_literals[i].text);
            fputs("\\0\"\n", output);
        }
        fputc('\n', output);
    }

    if (parser->float_literal_count > 0) {
        fputs("# Float/Double constants\n    .align 4\n", output);
        for (int i = 0; i < parser->float_literal_count; i++) {
            const char *value = parser->float_literals[i].value;
            fprintf(output, ".LC_float_%d:\n", parser->float_literals[i].id);
            const char *point = strchr(value, '.');
            int is_double = point != NULL && strlen(point) > 8;
            if (is_double) {
                double number = strtod(value, NULL);
                unsigned long long bits;
                memcpy(&bits, &number, sizeof(bits));
                fprintf(output, "    .quad 0x%016llx    # double %s\n", bits, value);
            } else {
                float number = strtof(value, NULL);
                unsigned int bits;
                memcpy(&bits, &number, sizeof(bits));
                fprintf(output, "    .long 0x%08x    # float %s\n", bits, value);
            }
        }
        fputc('\n', output);
    }

    fputs("    .bss\n    .align 8\n_scanfString_buffer:\n    .space 256\n\n", output);
    if (parser->code_pos > 0) fputs(parser->code_buffer, output);
    fputs("    .text\n", output);
    fputs(parser->function_code_buffer, output);

    if (fclose(output) != 0) return report_output_error(program, "Failed while writing output file '%s'", output_path);
    if (cleanup_assembly_file(output_path) != 0) {
        return report_output_error(program, "Assembly cleanup pass failed for '%s'", output_path);
    }
    return 1;
}

int backend_emit_file(const AstProgram *program, const BackendOptions *options,
                      const char *output_path) {
    if (program == NULL || options == NULL || output_path == NULL) return 0;
    TokenStream *stream = ast_token_stream(program);
    if (stream == NULL) {
        error_report(global_error_handler, SEVERITY_FATAL, 0, 0, ERROR_CATEGORY_CODEGEN,
                     ERR_CODEGEN_OUTPUT_FAILED, program->source_path,
                     "Out of memory while lowering AST");
        return 0;
    }

    Parser *lowering = create_parser(stream);
    if (lowering == NULL) {
        destroy_token_stream(stream);
        error_report(global_error_handler, SEVERITY_FATAL, 0, 0, ERROR_CATEGORY_CODEGEN,
                     ERR_CODEGEN_OUTPUT_FAILED, program->source_path,
                     "Out of memory while creating backend state");
        return 0;
    }
    lowering->debug_mode = options->debug;
    lowering->target_format = options->target_format;
    lowering->syntax_mode = options->syntax_mode;
    set_target_format(options->target_format);

    int success = parse_program(lowering, program->source_path);
    if (success) success = write_assembly(program, lowering, options, output_path);
    if (success && options->debug) {
        printf("  [+] Assembly code generated: %s\n", output_path);
        printf("      - Code size: %d Bytes\n", lowering->function_code_pos);
        printf("      - String literals: %d\n", lowering->string_literal_count);
        printf("      - Float literals: %d\n", lowering->float_literal_count);
        printf("      - AST declarations: %zu\n", program->declaration_count);
    }

    free_parser(lowering);
    destroy_token_stream(stream);
    return success;
}
