#include "ir_emitter_internal.h"
#include "ir_names.h"
#include "runtime_calls.h"
#include "native_runtime.h"
#include "errorHandler.h"

#include <errno.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

int map_quoted(FILE *output, const char *text) {
    if (fputc('"', output) == EOF) return 0;
    for (const unsigned char *p = (const unsigned char *) (text == NULL ? "" : text); *p; p++) {
        if (*p == '"' || *p == '\\') {
            if (fputc('\\', output) == EOF || fputc(*p, output) == EOF) return 0;
        } else if (*p == '\n') {
            if (fputs("\\n", output) == EOF) return 0;
        } else if (*p == '\r') {
            if (fputs("\\r", output) == EOF) return 0;
        } else if (*p == '\t') {
            if (fputs("\\t", output) == EOF) return 0;
        } else if (*p < 0x20) {
            if (fprintf(output, "\\x%02x", *p) < 0) return 0;
        } else if (fputc(*p, output) == EOF) return 0;
    }
    return fputc('"', output) != EOF;
}


static int emit_file(Emitter *emitter, int deterministic) {
    FILE *output = emitter->output;
    if (!emitter->native) {
        fputs("# Generated by Philipp01105's Compiler\n", output);
        fprintf(output, "# Source: %s\n", emitter->module->program->source_path);
        if (!deterministic) {
            time_t now = time(NULL);
            struct tm *local = localtime(&now);
            char datetime[64] = "unknown";
            if (local != NULL)
                (void) strftime(datetime, sizeof(datetime),
                                "%Y-%m-%d %H:%M:%S", local);
            fprintf(output, "# Date: %s\n", datetime);
        }
        fputs("# Lowering: typed IR\n", output);
        fprintf(output, "# Target Format: %s\n# Syntax: %s\n",
                emitter->target == TARGET_COFF ? "COFF" : "ELF",
                emitter->syntax == SYNTAX_INTEL ? "Intel" : "AT&T");
        if (emitter->syntax == SYNTAX_INTEL) fputs("    .intel_syntax noprefix\n", output);
        if (emitter->target == TARGET_COFF) {
            fputs("    .section .rdata,\"dr\"\n", output);
        } else {
            fputs("    .section .rodata\n", output);
        }
        if (emitter->target == TARGET_COFF)
            for (size_t r = 0; r < runtime_call_count(); r++) {
                const RuntimeCall *runtime = runtime_call_at(r);
                int duplicate = 0;
                for (size_t previous = 0; previous < r; previous++)
                    if (strcmp(runtime_call_at(previous)->link_name, runtime->link_name) == 0) duplicate = 1;
                if (!duplicate)
                    fprintf(output, "    .def %s; .scl 2; .type 32; .endef\n", runtime->link_name);
            }
    } else emitter->native->section = NATIVE_RODATA;
    write_labelf(emitter, ".LIR_empty_string_0:\n");
    write_cstring(emitter, "");
    write_labelf(emitter, ".LIR_int_format_0:\n");
    write_cstring(emitter, "%lld");
    write_labelf(emitter, ".LIR_uint_format_0:\n");
    write_cstring(emitter, "%u");
    write_labelf(emitter, ".LIR_char_format_0:\n");
    write_cstring(emitter, "%c");
    write_labelf(emitter, ".LIR_float_format_0:\n");
    write_cstring(emitter, "%f");
    write_labelf(emitter, ".LIR_string_format_0:\n");
    write_cstring(emitter, "%s");
    for (size_t f = 0; f < emitter->module->function_count; f++) {
        const IrFunction *function = &emitter->module->functions[f];
        for (size_t i = 0; i < function->instruction_count; i++) {
            const IrInstruction *instruction = &function->instructions[i];
            if (instruction->opcode == IR_OP_CONSTANT && instruction->type == TYPE_STRING) {
                write_labelf(emitter, ".LIR_string_%zu_%zu:\n", f,
                             instruction->result);
                write_cstring(emitter, ast_program_lexeme(function->source_program,
                                                          instruction->auxiliary_token));
            }
        }
    }
    for (size_t e = 0; e < emitter->module->enum_count; e++) {
        const IrEnum *enumeration = &emitter->module->enums[e];
        for (size_t a = 0; a < enumeration->variant_argument_count; a++) {
            const IrEnumArgument *argument = &enumeration->variant_arguments[a];
            if (argument->type_id >= emitter->module->type_count) continue;
            const IrType *type = &emitter->module->types[argument->type_id];
            if (type->kind != IR_TYPE_PRIMITIVE || type->primitive != TYPE_STRING) continue;
            write_labelf(emitter, ".LIR_enum_%zu_%zu:\n", e, a);
            write_cstring(emitter, ast_program_lexeme(enumeration->source_program,
                                                      argument->token));
        }
        for (size_t field = 0; field < enumeration->field_count; field++) {
            write_labelf(emitter, ".LIR_enum_field_%zu_%zu:\n", e, field);
            if (enumeration->fields[field].type_id >= emitter->module->type_count) return 0;
            const IrType *field_type =
                    &emitter->module->types[enumeration->fields[field].type_id];
            if (field_type->kind != IR_TYPE_PRIMITIVE) return 0;
            for (size_t variant_index = 0;
                 variant_index < enumeration->variant_count; variant_index++) {
                const IrEnumVariant *variant = &enumeration->variants[variant_index];
                size_t argument_index = variant->first_argument + field;
                if (field >= variant->argument_count ||
                    argument_index >= enumeration->variant_argument_count)
                    return 0;
                const IrEnumArgument *argument =
                        &enumeration->variant_arguments[argument_index];
                if (field_type->primitive == TYPE_STRING) {
                    if (emitter->native) {
                        char symbol[128];
                        snprintf(symbol, sizeof(symbol), ".LIR_enum_%zu_%zu", e, argument_index);
                        (void) native_reference(emitter->native, symbol, NATIVE_ADDR64,
                                                emitter->native->sections[NATIVE_RODATA].size, 0);
                        write_quad(emitter, 0);
                    } else fprintf(output, "    .quad .LIR_enum_%zu_%zu\n", e, argument_index);
                } else if (field_type->primitive == TYPE_DOUBLE) {
                    union {
                        double value;
                        uint64_t bits;
                    } converted = {
                        strtod(ast_program_lexeme(enumeration->source_program,
                                                  argument->token), NULL)
                    };
                    if (argument->negative) converted.value = -converted.value;
                    write_quad(emitter, converted.bits);
                } else if (field_type->primitive == TYPE_FLOAT) {
                    union {
                        float value;
                        uint32_t bits;
                    } converted = {
                        (float) strtod(ast_program_lexeme(enumeration->source_program,
                                                          argument->token), NULL)
                    };
                    if (argument->negative) converted.value = -converted.value;
                    write_quad(emitter, converted.bits);
                } else {
                    IrInstruction literal = {.auxiliary_token = argument->token};
                    long long value = constant_value(enumeration->source_program, &literal);
                    if (argument->negative) value = -value;
                    write_quad(emitter, (uint64_t) value);
                }
            }
        }
    }
    for (size_t g = 0; g < emitter->module->global_count; g++)
        if (emitter->module->globals[g].string) {
            write_labelf(emitter, ".LIR_global_string_%zu:\n", g);
            write_cstring(emitter, emitter->module->globals[g].string);
        }
    if (emitter->native) emitter->native->section = NATIVE_DATA;
    else fputs("    .data\n    .balign 8\n", output);
    for (size_t g = 0; g < emitter->module->global_count; g++) {
        const IrGlobal *global = &emitter->module->globals[g];
        const SemanticSymbol *symbol = &emitter->module->semantics->symbols[global->symbol_id];
        char label[4096];
        if (!global_label(symbol, label, sizeof(label))) return 0;
        if (emitter->native) {
            if (!native_define(emitter->native, label, symbol->declaration->is_public, 0)) return 0;
        } else {
            if (symbol->declaration->is_public) fprintf(output, "    .globl %s\n", label);
            fprintf(output, "%s:\n", label);
        }
        if (global->string) {
            if (emitter->native) {
                char string[64];
                snprintf(string, sizeof(string), ".LIR_global_string_%zu", g);
                native_reference(emitter->native, string, NATIVE_ADDR64, emitter->native->sections[NATIVE_DATA].size,
                                 0);
                write_quad(emitter, 0);
            } else fprintf(output, "    .quad .LIR_global_string_%zu\n", g);
        } else {
            size_t slots = type_slots(emitter->module, global->type_id);
            if (!slots || slots > 1048576) return 0;
            write_quad(emitter, global->bits);
            for (size_t slot = 1; slot < slots; slot++) write_quad(emitter, 0);
        }
    }
    if (emitter->native) emitter->native->section = NATIVE_TEXT;
    else fputs("    .text\n", output);
    for (size_t f = 0; f < emitter->module->function_count; f++) {
        const IrFunction *function = &emitter->module->functions[f];
        size_t declarations = 0;
        size_t aggregate_results = 0;
        size_t aggregate_parameters = 0;
        for (size_t i = 0; i < function->instruction_count; i++)
            if (function->instructions[i].opcode == IR_OP_DECLARE) {
                size_t slots = type_slots(emitter->module, function->instructions[i].type_id);
                if (slots == 0 || declarations > SIZE_MAX - slots) return 0;
                declarations += slots;
            } else if ((function->instructions[i].opcode == IR_OP_CALL || function->instructions[i].opcode ==
                        IR_OP_ENUM_CONSTRUCT || function->instructions[i].opcode == IR_OP_SLICE) &&
                       is_inline_structure(emitter->module,
                                           &function->instructions[i])) {
                size_t slots = type_slots(emitter->module,
                                          function->instructions[i].type_id);
                if (slots == 0 || aggregate_results > SIZE_MAX - slots) return 0;
                aggregate_results += slots;
            }
        for (size_t p = 0; p < function->parameter_count; p++) {
            if (!type_is_structure(emitter->module, function->parameters[p].type_id)) continue;
            size_t parameter_slots = type_slots(emitter->module,
                                                function->parameters[p].type_id);
            if (parameter_slots == 0 || aggregate_parameters > SIZE_MAX - parameter_slots)
                return 0;
            aggregate_parameters += parameter_slots;
        }
        size_t parameter_slots = parameter_storage_slots(function);
        if (function->next_value > SIZE_MAX - parameter_slots ||
            function->next_value + parameter_slots > SIZE_MAX - declarations)
            return 0;
        size_t slots = function->next_value + parameter_slots + declarations;
        if (slots > SIZE_MAX - aggregate_results) return 0;
        slots += aggregate_results;
        if (slots > SIZE_MAX - aggregate_parameters) return 0;
        slots += aggregate_parameters;
        if (slots > (8U * 1024U * 1024U - 8U) / 8U) return 0;
        size_t bytes = slots * 8U;
        emitter->function = function;
        emitter->function_index = f;
        emitter->declaration_count = declarations;
        emitter->frame_size = ((bytes + 15U) & ~(size_t) 15U) + 8U;
        if (!emit_function(emitter)) return 0;
    }
    return 1;
}

int x86_64_emit_ir_file(const IrModule *module, TargetFormat target,
                        SyntaxMode syntax, int deterministic,
                        const char *output_path, const char *source_map_path) {
    if (!valid_module(module) || output_path == NULL) return 0;
    FILE *output = fopen(output_path, "w");
    if (output == NULL) {
        error_report(global_error_handler, SEVERITY_ERROR, 0, 0, ERROR_CATEGORY_CODEGEN,
                     ERR_CODEGEN_OUTPUT_FAILED, module->program->source_path,
                     "Could not open assembly output '%s': %s", output_path, strerror(errno));
        return 0;
    }
    SourceMapWriter map = {0};
    if (source_map_path != NULL) {
        map.output = fopen(source_map_path, "w");
        if (map.output == NULL) {
            int saved_errno = errno;
            fclose(output);
            (void) remove(output_path);
            error_report(global_error_handler, SEVERITY_ERROR, 0, 0, ERROR_CATEGORY_CODEGEN,
                         ERR_CODEGEN_OUTPUT_FAILED, module->program->source_path,
                         "Could not open source-map output '%s': %s", source_map_path, strerror(saved_errno));
            return 0;
        }
        if (fputs("dmm-source-map-v1\nsource path=", map.output) == EOF ||
            !map_quoted(map.output, module->program->source_path) ||
            fputs("\n", map.output) == EOF)
            map.failed = 1;
    }
    Emitter emitter = {
        .module = module,
        .target = target,
        .syntax = syntax,
        .output = output,
        .source_map = source_map_path == NULL ? NULL : &map
    };
    int success = emit_file(&emitter, deterministic);
    if (success && (!module->program->package_name || !strcmp(module->program->package_name, "main")))
        success = native_runtime_assembly(output, target);
    int assembly_io_error = ferror(output);
    if (fclose(output) != 0) assembly_io_error = 1;
    int map_io_error = map.output != NULL && ferror(map.output);
    if (map.output != NULL && fclose(map.output) != 0) map_io_error = 1;
    int saved_errno = errno;
    if (assembly_io_error || map_io_error || map.failed) success = 0;
    if (!success) (void) remove(output_path);
    if (!success && source_map_path != NULL) (void) remove(source_map_path);
    if (assembly_io_error || map_io_error)
        error_report(global_error_handler, SEVERITY_ERROR, 0, 0, ERROR_CATEGORY_CODEGEN,
                     ERR_CODEGEN_OUTPUT_FAILED, module->program->source_path,
                     "Could not write %s output '%s': %s", assembly_io_error ? "assembly" : "source-map",
                     assembly_io_error ? output_path : source_map_path, strerror(saved_errno == 0 ? EIO : saved_errno));
    return success;
}

int x86_64_lower_native(const IrModule *module, TargetFormat target, NativeObject *object, FILE *source_map) {
    if (!valid_module(module)) {
        native_error(object, "Invalid IR module");
        return 0;
    }
    SourceMapWriter map = {.output = source_map};
    if (source_map) fputs("dmm-native-map-v1\n", source_map);
    Emitter emitter = {
        .module = module, .target = target, .native = object,
        .source_map = source_map ? &map : NULL
    };
    int success = emit_file(&emitter, 1);
    return success && !object->failed && !map.failed;
}

