function(dmm_network_test_source input output)
    file(READ "${input}" source)
    string(REPLACE "import \"stdlib/core/executor\";" "" source "${source}")
    string(REPLACE "import \"stdlib/native/threading\";" "" source "${source}")
    string(REPLACE "    \"stdlib/core/executor\"\n" "" source "${source}")
    string(REPLACE "    \"stdlib/native/threading\"\n" "" source "${source}")
    string(REPLACE "import (\n);\n" "" source "${source}")
    string(REPLACE "executor.__dmm_async_" "testAsync_" source "${source}")
    string(REPLACE "threading.__dmm_async_" "testAsync_" source "${source}")
    file(WRITE "${output}" "${source}")
endfunction()
