#ifndef DMM_LANGUAGE_TYPES_H
#define DMM_LANGUAGE_TYPES_H

#define MAX_TOKEN 512

typedef enum {
    TOKEN_KEYWORD_FUNC, TOKEN_KEYWORD_VAR, TOKEN_KEYWORD_RETURN,
    TOKEN_KEYWORD_FOR, TOKEN_KEYWORD_IF, TOKEN_KEYWORD_ELSE,
    TOKEN_KEYWORD_WHILE, TOKEN_KEYWORD_PRINT, TOKEN_KEYWORD_PRINTLINE,
    TOKEN_KEYWORD_BREAK, TOKEN_KEYWORD_CONTINUE, TOKEN_KEYWORD_STRUCT,
    TOKEN_KEYWORD_ENUM, TOKEN_KEYWORD_IMPORT, TOKEN_KEYWORD_STATIC,
    TOKEN_KEYWORD_RESERVE, TOKEN_KEYWORD_FREE, TOKEN_KEYWORD_GC,
    TOKEN_TYPE_INT, TOKEN_TYPE_CHAR, TOKEN_TYPE_BYTE, TOKEN_TYPE_BIT,
    TOKEN_TYPE_FLOAT, TOKEN_TYPE_DOUBLE, TOKEN_TYPE_STRING, TOKEN_TYPE_VOID,
    TOKEN_IDENTIFIER, TOKEN_NUMBER, TOKEN_FLOAT_LITERAL, TOKEN_CHAR_LITERAL,
    TOKEN_STRING_LITERAL, TOKEN_PLUS, TOKEN_MINUS, TOKEN_STAR, TOKEN_SLASH,
    TOKEN_PERCENT, TOKEN_EQUAL, TOKEN_EQUAL_EQUAL, TOKEN_BANG_EQUAL,
    TOKEN_LESS, TOKEN_LESS_EQUAL, TOKEN_GREATER, TOKEN_GREATER_EQUAL,
    TOKEN_AMP_AMP, TOKEN_PIPE_PIPE, TOKEN_BANG, TOKEN_AMPERSAND,
    TOKEN_PLUS_EQUAL, TOKEN_MINUS_EQUAL, TOKEN_STAR_EQUAL, TOKEN_SLASH_EQUAL,
    TOKEN_PLUS_PLUS, TOKEN_MINUS_MINUS, TOKEN_LPAREN, TOKEN_RPAREN,
    TOKEN_LBRACE, TOKEN_RBRACE, TOKEN_LBRACKET, TOKEN_RBRACKET,
    TOKEN_SEMICOLON, TOKEN_COMMA, TOKEN_COLON, TOKEN_ARROW, TOKEN_DOT,
    TOKEN_HASH, TOKEN_AT, TOKEN_COMMENT, TOKEN_NEWLINE, TOKEN_EOF, TOKEN_ERROR
} TokenType;

typedef enum {
    TYPE_INT, TYPE_CHAR, TYPE_BYTE, TYPE_BIT, TYPE_FLOAT, TYPE_DOUBLE,
    TYPE_STRING, TYPE_VOID, TYPE_UNKNOWN
} DataType;

typedef enum { TARGET_ELF, TARGET_COFF } TargetFormat;
typedef enum { SYNTAX_ATT, SYNTAX_INTEL } SyntaxMode;

#endif
